bazelbuild/rules_rust

- examples/fibonacci/BUILD
...to unbreak continuous integration, see http://ci.bazel.io/job/rules_rust/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/1/console.
> Mark experimental benchmark features manual-only

- rust/rust.bzl
Since the Rust rules have been deleted from @bazel_tools, we should use the
labels for the Rust binaries under this workspace instead.
> Fix labels for Rust binaries to use those under @io_bazel_rules_rust

- rust/rust.bzl
This repository name is not needed and Bazel seems to
have a bug that it cannot refer to the main repository
under its name.
> Remove repository name for rust dependencies

- rust/rust.bzl
This fixes the rust tests on ci.bazel.io.
> Use short_path for runfiles tree references

- README.md
tag = 0.0.1 does not work for the latest bazel (version 0.3.0)
> Update tag in README

- CONTRIBUTORS
- rust/rust.bzl
I've mirrored your files for guaranteed reliability, courtesy of Google Cloud Storage.
In the future, you can mirror these files too with the following command. Although you need to ask @damienmg for write access to the bucket. Or just email me the URL you want mirrored and I'll happily do it.
```bash
bzmirror() {
local url="${1:?url}"
if [[ "${url}" =~ ^([^:]+):([^:]+):([^:]+)$ ]]; then
url="http://repo1.maven.org/maven2/${BASH_REMATCH[1]//.//}/${BASH_REMATCH[2]}/${BASH_REMATCH[3]}/${BASH_REMATCH[2]}-${BASH_REMATCH[3]}.jar"
fi
local dest="gs://bazel-mirror/${url#http*//}"
local desturl="http://bazel-mirror.storage.googleapis.com/${url#http*//}"
local name="$(basename "${dest}")"
wget -O "/tmp/${name}" "${url}" || return 1
gsutil cp -a public-read "/tmp/${name}" "${dest}" || return 1 …
```
> Use Bazel mirror to download externals

- rust/rust.bzl
Without that, the C++ wrapper doesn't get shipped in the OS X Sandbox.
> Set the C++ crosstool files as input to the rust compile action

- rust/rust.bzl
Add it to all the necessary action for `bazel test //...`
to pass all tests on Darwin.
Fixes #20.
> Add crosstool files input to more action

- README.md
- rust/rust.bzl
I have mirrored the Rust 1.11 releases on `gs://bazel-mirror/static.rust-lang.org/dist`.
> Update to Rust 1.11. Bump version for rules_rust in README to 0.0.3.

- test/test_rules.bzl
I'm working on updating the execution root structure (see https://github.com/bazelbuild/bazel/issues/1681), which makes manually building the prefix unnecessary. I've left the strip_prefix("external/" code for backwards compatibility,
but it should be able to be removed in the future.
> Make rust rules use workspace root as-is if it's in the correct form

- examples/matrix/BUILD
> Add "-std=c99" to matrix examples to fix compilation bugs.

- README.md
- rust/rust.bzl
See go/bazel-downloader for more information. This feature was made
possible by https://github.com/bazelbuild/bazel/commit/ed7ced0018dc5c5ebd6fc8afc7158037ac1df00d
> Recommend redundant URLs for installation

- test/BUILD
In the future string representations of file object will be different and it will look like `<generated file path/to/file.txt>`, therefore the test has been changed to check for this optional additional angular bracket.
> Make rule tests compatible with the new string representations in Skylark

- rust/BUILD
- rust/repositories.bzl
- rust/rust.bzl
- rust/toolchain.bzl
This allows rust targets to only depend on (and thus download) the
toolchains that are used, dynamically chosen based on the current target
platform.
This requires use of Bazel 0.5.4, and will not work with earlier releases of Bazel.
Fixes #14.
> Update rules_rust to use Bazel's toolchains feature.

- rust/repositories.bzl
The `1.15.1` compiler used in the Rust rules is quite outdated at this point. This updates the compiler version to the most recent release, `1.20.0`.
The URLs point directly at the rust-lang.org site instead of the Bazel mirror site. If you upload the newer compiler to that site I can update the URLs as necessary.
> Update compiler toolchain to 1.20.0.

- WORKSPACE
For compatibility with the future versions of Bazel (namely: it won't be allowed to have the deprecated `set` function even in the parts of the code that are not executed).
> Update rules_sass to the latest version

- README.md
- rust/rust.bzl
Fixes links in the documentation for the correct location of the rust_repositories macro.
See https://github.com/bazelbuild/rules_rust/pull/45#issuecomment-296577998
> Update documentation with the right load() for rust_repositories.

- examples/hello_runfiles/BUILD
- examples/hello_runfiles/data/sample.txt
- examples/hello_runfiles/src/lib.rs
- examples/hello_runfiles/src/main.rs
- rust/rust.bzl
Setting data wasn't actually being made available to tests, this fixes that.
> Fix 'data' field not being made available to rust_test rule.

- examples/hello_runfiles/src/lib.rs
Apparently runfiles under macos have an important difference from Unix (and I presume, windows): I believe they live directly in the working directory, not "$target_name.runfiles"
This is a sloppy fix that changes the mechanics of the test according to the target os.
Notice: @mfarrugi
EDIT: Fix silly mistake regarding runfiles explanation: "data" is the data file itself.
> Fix runfiles test: Macos runfiles are quite different

- examples/hello_runfiles/src/lib.rs
- rust/rust.bzl
- rust/toolchain.bzl
This PR replaces "/bin/bash" with the more general "/usr/bin/env bash". This is necessary on platforms that don't have `bash` in `/bin`, namely BSD and esoteric linux distributions such as Guix and NixOS.
FWIW: This is a pervasive problem is Bazel. My own build rules for Bazel apply a [multi thousand line patch](https://github.com/acmcarther/essentials/blob/master/nix/packages/bazel/fix_shebangs.patch) just to let Bazel build on NixOS. I'm OK with this PR being closed if you feel this is too much of a niche problem.
> Update shebang to use env

- README.md
- examples/hello_lib/BUILD
- rust/repositories.bzl
- rust/rust.bzl
- rust/toolchain.bzl
Removes the hard coded rust_lib output, and declares the output file within the rust_library_impl. This lets us vary the file extension based on the toolchain -- OSX produces `.dylib` where linux would produce `.so`, for example.
Original description follows:
---
Tentatively addresses #36.
WIP: Need tests and understand platform implications
@davidzchen: Do we need the additional complexity of a hidden build rule? This change seems to work on my platform to produce dylibs that can be loaded correctly.
I've no idea how to handle different platforms. I added it as an additional attr, but I think a `config_setting` probably makes more sense.
> Support crate_type file extensions more fully

- examples/ffi/c_calling_rust/BUILD
- examples/ffi/c_calling_rust/lib.rs
- examples/ffi/c_calling_rust/main.c
> Add example of c calling rust

- README.md
The last iteration of this fix only fixed the path to the status page -- we also need to fix the SVG url.
cc: @buchgr
> Make badge use master status (part II)

- rust/repositories.bzl
Upgrades Rust to take advantage of newer features, namely incremental compilation:
https://github.com/rust-lang/rust/blob/master/RELEASES.md
> Update Rust to 1.24.1

- rust/rust.bzl
Both the documentation and the error message say that it is possible for `rust_binary` targets to depend on `cc_library` targets. Currently, trying to do so results in an error.
I believe this one small change is all that is necessary. I have tested this with my own project and it appears to work but I am unfamiliar enough with Bazel and Skylark that I am not 100% certain that it is correct.
> Allow `rust_binary` to depend on `cc_library`

- README.md
- rust/rust.bzl
- rust/toolchain.bzl
Some existing rust code depends on those environment variables being
defined at compile-time using the env!() macro.
This inject the environment variables listed at https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates.
and make "version" an attribute of all rust_* rules.
> Add default cargo environment variable to the execution

- rust/repositories.bzl
Tested with local docker build
This was broken by #90. @acmcarther @nlopezgi
> Fix remote build

- .bazelci/presubmit.yml
- WORKSPACE
- rust/repositories.bzl
Partially fixes some tests disabled in https://github.com/bazelbuild/rules_rust/pull/111
Resolves (partially) https://github.com/bazelbuild/rules_rust/issues/112 EXCEPT for runfiles.
@xingao267, @mfarrugi 
EDIT:
I have to say, this build caching is totally amazing:
See [build results latest commit](https://buildkite.com/bazel/rules-rust-rustlang/builds/152#902b1e98-4f07-4ecf-ad8e-d02741d92378). It didn't have to run any of the tests since the tests from the last commit were still valid as you would expect under local execution.
> Fix RBE by including codegen-backends from rustc/

- examples/ffi/rust_calling_c/BUILD
- rust/rust.bzl
- rust/toolchain.bzl
Not the cleanest way to do it, but I wanted to avoid a larger refactor.
> Fix rust_doc rule with transitive native dependencies.

- examples/ffi/c_calling_rust/BUILD
- examples/ffi/rust_calling_c/c/matrix_test.c
- examples/hello_runfiles/src/lib.rs
Removes a little noise from `bazel test @examples//... ...`
(Cherrpicked out of #108)
> Fix warnings in examples.

- rust/BUILD
> Define the toolchain_type used by rust rules.

- rust/private/rustc.bzl
- rust/toolchain.bzl
The target triplet is coming from the toolchain and should be passed
along to rustc.
> Set the target triplet when invoking rustc

- rust/private/rustc.bzl
This should make debug binaries come out (closer to) identical when built by different users or machines.
See also https://github.com/rust-lang/cargo/issues/5505
PWD was usually something like `/home/marco/.cache/bazel/_bazel_marco/5e2375638c8763207dcac6c950a3684d/sandbox/linux-sandbox/14/execroot/`, which is a transient path. This should already be cause debugging problems, if there are any.
Edit:
This is visible w/ `strings`, eg:
```
>> bazel run -s -c dbg //tools/runfiles:runfiles_test && strings bazel-bin/tools/runfiles/runfiles_test | grep -e $USER -e bazel
/checkout/src/liballoc/raw_vec.rsio_bazel_rules_rust/tools/runfiles/data/sample.txtExample Text!assertion failed: `(left == right)`
/home/marco/.cache/bazel/_bazel_marco/4e38d4394f29c071904de81d6fb3e103/sandbox/linux-sandbox/1/exec …
```
> Add --remap-path-prefix=$PWD to make dbg builds more reproducible.

- rust/repositories.bzl
This change add the STATIC_RUST_URL environment variable to overwrite
the URL to https://static.rust-lang.org when downloading the rust
toolchain. This let the user specify using --action_env a mirror of
static.rust-lang.org instead.
This is particularly useful in China where https://static.rust-lang.org
is really slow. For chinese user, the best way to proceed after this
change is to add the following line in your ~/.bazelrc:
```
build --action_env STATIC_RUST_URL=http://mirrors.ustc.edu.cn/rust-static
```
> STATIC_RUST_URL sets the static.rust-lang.org URL

- examples/hello_lib/BUILD
- rust/private/rustc.bzl
PR #151 broke some usage of those flags that make `cargo raze` build file not work any more.
This PR adds those 2 flag to a library so we notice those breakage. It allow the change for "rustc_flags" and fix the "features" argument.
As a consequence passing `["--arg value"]` to rustc_flags no longer works but that's fine (it's a reasonable breaking change). One should either do `["--arg", "value"]` or `["--arg=value"]`.
> Test rustc flag and feature flags

- .bazelci/presubmit.yml
- rust/private/rustdoc_test.bzl
- test/chained_direct_deps/BUILD
- test/chained_direct_deps/mod3.rs
Add tests that fails with:
error[E0463]: can't find crate for
--> test/chained_direct_deps/mod3.rs:4:1
|
4 | extern crate mod1;
| ^^^^^^^^^^^^^^^^^^ can't find crate
And fix it.
> Fix rust_doc_test with transitive dependencies and add tests for it

- proto/README.md
- proto/proto.bzl
proto_compile was the name from rules_proto and proto_library is the
actual correct name for native proto support in Bazel.
> doc: change reference to proto_compile into proto_library

- rust/private/rustc.bzl
Should fix bazelbuild/continuous-integration#379
> Pass -p to mkdir to make sure we do not fails if bazel already created the output directory

- WORKSPACE
- proto/proto.bzl
- proto/repositories.bzl
- proto/toolchain.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc.bzl
- rust/private/rustdoc_test.bzl
Many of the changes were made using Buildifier (which is why the files
are reformatted).
Also, update some of the dependencies
Progress towards #161
> Cleanups for compatibility with future Bazel releases

- proto/repositories.bzl
http_archive are faster and better caching support compared
to git_repository.
> Use http_archive for protobuf repository

- proto/proto.bzl
- proto/toolchain.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc.bzl
- rust/private/rustdoc_test.bzl
- rust/repositories.bzl
- rust/toolchain.bzl
This gets us from
```
bazel-20 test //... --all_incompatible_changes --incompatible_disable_deprecated_attr_params=false --incompatible_depset_is_not_iterable=false --incompatible_depset_union=false --incompatible_new_actions_api=false
```
to 
```
bazel-20 test  --all_incompatible_changes //... @examples//... --incompatible_disable_deprecated_attr_params=false --incompatible_new_actions_api=false
```
Remaining issues:
```
>> bazel-20 test  --all_incompatible_changes //... @examples//... --keep_going
INFO: Invocation ID: deecf474-694f-4adc-9995-b09b2a5fc850
DEBUG: /home/marco/.cache/bazel/_bazel_marco/4e38d4394f29c071904de81d6fb3e103/external/bazel_skylib/skylark_library.bzl:23:1: WARNING: skylark_library.bzl is deprecated and will go away in the future, please use bzl_library.bzl instead. …
```
> More bazel --incompatible fixes (#161)

- proto/README.md
* Arguments should be vararg, not a list
* rust_proto_toolchain no longer accepts *_compile_deps
> Fix register toolchains example code

- proto/proto.bzl
- proto/toolchain.bzl
The generated rust file for `my-file.proto` is `my_file.rs`.
Declared outputs for *_proto and *_grpc rules should reflect this.
> Change dash to underscore in generated filenames

- rust/private/rustc.bzl
- test/build_env/BUILD
- test/build_env/src/manifest_dir_file.txt
- test/build_env/tests/manifest_dir.rs
Several popular crates, as well as some source code has a habit of using `env!("CARGO_MANIFEST_DIR")` to find files in a crate. This causes things like google/cargo-raze#71.
Following @acmcarther suggestions this is an attempt at solution 3, which appears to handle (ab)uses of `CARGO_MANIFEST_DIR` I have tested (tera, askuma).
> Establish `CARGO_MANIFEST_DIR`

- rust/repositories.bzl
Noticed this was missing when I went to use it..
> Take 'default_edition' as an optional parameter of BUILD_for_rust_toolchain.

- bindgen/repositories.bzl
...otherwise it fails when imported from a repository
> Fix the label for Clang's BUILD file

- bindgen/bindgen.bzl
Surprised it has worked this far :)! Include directories are explicitly defined and can't be derived from the filenames of headers. I ran into this with a pretty complex graph of `cc_library`s.
> Pass in correct include directories to bindgen

- rust/private/rust.bzl
- rust/private/rustc.bzl
This explicitly adds a `linker_script` option to `rust_binary` as suggested in the bottom of #204.
It's fundamentally identical to adding the ldscript to data and then adding `--codegen=link-args=-T$(location //:ldscript)` to `rustc_flags`, but now without the hassle of figuring that out yourself.
> Add linker_script option to rust_binary

- examples/ffi/rust_calling_c/BUILD
- examples/ffi/rust_calling_c/simple/BUILD
- examples/fibonacci/BUILD
- examples/hello_lib/BUILD
- examples/hello_out_dir/BUILD
- examples/per_platform_printer/BUILD
- rust/private/rust.bzl
- test/chained_direct_deps/BUILD
- test/conflicting_deps/BUILD
- test/inline_test_with_deps/dep/BUILD
- test/inline_test_with_deps/dep/src/lib.rs
- test/inline_test_with_deps/test/BUILD
- test/inline_test_with_deps/test/src/lib.rs
- test/inline_test_with_deps/test_with_srcs/BUILD
- test/inline_test_with_deps/test_with_srcs/src/extra.rs
- test/inline_test_with_deps/test_with_srcs/src/lib.rs
- tools/runfiles/BUILD
Due to the way unit tests are handled with the rules, it is tricky for a
unit test to have additional deps.
Consider some source code like such
```rust
fn some_fn() -> u32 {
2
}
mod tests {
use super::some_fn();
// This following line is not going to work
use pretty_assertions::assert_eq;
#[test]
fn test_is_2() {
assert_eq!(1, some_fn());
}
}
```
With a build function like so
```python
rust_library(
name = "example",
srcs = ["lib.rs"]
)
rust_test(
name = "example_test",
deps = [
":example",
"//third_party/rust:pretty_assertion",
],
)
```
Presently, due to the handling of ‟unit tests” the extra deps will
conflict with rust_rules ideas about how to identify the test, and give
an error along the lines of
```
attribute srcs: No lib.rs or example_test.rs source file found.
```
With this change …
> Make it possible for unit tests to have dev deps

- bindgen/bindgen.bzl
This fixes the issue raised in https://github.com/bazelbuild/rules_rust/issues/218.
Depsets are not backed by hash sets do not have a trivial check for existence. Thus we need to explicitly flatten the depset into a list of headers before we see if the header is in the set.
I'm not clear enough on how bindgen works to propose a more elegant fix. Doing this check at all requires flattening to a list, and I don't know how/if we could avoid doing this check.
> Fix failure to build without iterable depset

- proto/proto.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
Currently if you're using an artifacted compiler the Rust rules will complain that they can't find the linker script. This is because it is not a dependency.
I'm pretty sure there's a correct way to do this with the new toolchain system but I was looking around and saw that people mostly stuck with this with some TODOs to find a better way.
I tried to get it using `ctx.toolchains` but that doesn't actually have files, it seems.
> Add cc toolchain files to rustc dependencies (for linker)

- bindgen/bindgen.bzl
Fixes #218's newly reported problem.
I don't think there's a way to actually test this without having more comprehensive unit tests, which I don't have time to work on right now.
> Fix failure to build without iterable depset pt. 2

- rust/private/legacy_cc_starlark_api_shim.bzl
There are two changes in Bazel 0.27:
- .libraries_to_link will return a depset
- direct iteration over depset will be forbidden
For compatibility, we add a (temporary) type test.
> Update code for compatibility to Bazel 0.27

- proto/proto.bzl
- proto/toolchain.bzl
In addition, this makes it possible to fix http://github.com/bazelbuild/bazel/issues/7157 (patch upcoming)
> Make rust_proto_library work with proto_library rules using import_prefix / strip_import_prefix .

- WORKSPACE
- rust/repositories.bzl
This is needed for the change in Bazel --incompatible_disallow_empty_glob
> Add allow_empty to glob, as the patterns don't necessarily match something

- rust/private/legacy_cc_starlark_api_shim.bzl
- rust/private/rustc.bzl
This PR makes sure that rustc action also takes declared environment
variables from the C++ toolchain when constructing the action. This way
the C++ toolchain can start using more environment variables without
breaking rust.
> Use C++ environment variables when constructing link command line

- rust/private/rustc.bzl
This provides the directories containing the rust standard library (or libcore) as linker arguments to rustc, so the compiler can also find them if they are not in the standard location. This is especially useful when you want to download the different toolchain and target parts in your workspace and construct a custom toolchain from that.
Passing these arguments should be harmless when the standard libraries are in their regular paths.
Adding tests with a custom toolchain would be a bit of a hassle, but I'm willing to write those if you think it would be worth it.
I believe this also fixes #213.
> Explicitly provide rustc the paths to the standard library.

- docs/index.md
- proto/toolchain.bzl
- rust/platform/platform.bzl
- rust/platform/triple_mappings.bzl
- rust/toolchain.bzl
https://github.com/bazelbuild/bazel/issues/8622
> Migrate rules_rust for incompatible_use_platforms_repo_for_constraints

- rust/private/dummy_cc_toolchain/dummy_cc_toolchain.bzl
This avoids a problem where rustc_compile_action() tries to use the
`all_files` property of the cc_toolchain.
This problem only occurs after turning on the following Bazel flag:
--incompatible_enable_cc_toolchain_resolution
The dummy cc toolchain is only used for building for wasm32.
> fix: add all_files to the dummy cc_toolchain

- rust/private/rust.bzl
- rust/private/transitions.bzl
I didn't actually notice that #240 closed #205, so I figure since the transition literally only deals with transitioning on `proc-macro` it should probably be called that.
@acmcarther if the reason for it has nothing to do with #205 please ignore this PR.
> Rename wasm_transition to relate to what it actually does

- rust/private/dummy_cc_toolchain/BUILD
The compatible_with statements in this repository are mostly explicit
about the repository the target refers to, even if it is the main
repository @io_bazel_rules_rust itself. So so in rust/private/dummy_cc_toolchain
as well.
Fixes #271
> rust/private/dummy_cc_toolchain: be explicit about the repository

- rust/repositories.bzl
If anyone is using `load_arbitrary_tool` in other parts of their system (hint: I am) it would be nice to let them provide a sha256 to use.
> Add sha256 argument to load_arbitrary_tool

- rust/private/rust.bzl
- rust/private/rustc.bzl
This PR makes it possible to define and depend on Rust targets whose `name` contains hyphen instead of underscore, primarily intended for case-matching names of third party libraries.
Example:
```bazel
rust_library(
name = "thiserror-impl",
srcs = glob(["vendor/thiserror-impl-1.0.11/src/**/*.rs"]),
crate_type = "proc-macro",
deps = [
"//third-party:proc-macro2",
"//third-party:quote",
"//third-party:syn",
],
)
```
Tested with https://github.com/dtolnay/cxx/pull/37.
> Support hyphens in target names

- rust/private/rustc.bzl
I occasionally see different versions of a crate (...like `syn` and friends) being compiled at the same time, which looks confusing if you're not aware of it.
> Include crate versions in progress messages

- examples/proto/BUILD
- examples/proto/lib.rs
- examples/proto/main.rs
- rust/private/rust.bzl
- rust/private/transitions.bzl
The rust_library rule specifies a cfg option.  This performs transitions
in order to support WASM.  Other rules, such as rust_binary, do not have
this configuration, which causes Bazel to build and link some libraries
into the final binary twice, resulting in compilation errors.  This is
detailed in pull request #294 and issue #300.  The issue was introduced
in commit 7cde1e46.
This adds the example from @colin353 in PR #294 as an example that would
otherwise fail.
Fixes #300
> Add cfg = proc_macro_host_transition to all rules

- examples/hello_macro/BUILD
- examples/hello_macro/src/lib.rs
- examples/hello_macro/tests/greeting.rs
- rust/private/rustdoc.bzl
- Added a no-op proc macro to "examples".
- While adding this macro, the following error message came from
"rust_doc":
warning: Trying to document proc macro crate without passing
'--crate-type proc-macro to rustdoc
To resolve this issue, the rust_doc rule was modified to propagate
the underlying crate type.
> Add proc macro example, propagate crate-type through rustdoc

- rust/repositories.bzl
Having no extra triples is a sensible default.
> Define default value for extra_target_triples

- rust/private/rust.bzl
I had a situation where a rust_library target contained both `src/cratename.rs` (the intended crate root) and `src/some/coincidental/inner/cratename.rs`. It seems fine to prefer the shortest one in this case, rather than a random one.
> When inferring crate root, take the match with shortest filepath

- proto/proto.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- test/build_env/BUILD
- test/build_env/tests/arbitrary_env.rs
Rules that call `rustc` setup environment variables in line with `cargo`'s behaviour (see the [documentation here](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates)). However they don't allow passing in additional environment variables that may be required at compile time, such as the [`PROTOC` variable in `prost-build`](https://github.com/danburkert/prost/blob/2de785aca480779ab0d4442d4bc91a696e3e6c89/prost-build/src/lib.rs#L689).
This PR adds the `rustc_env` attribute to the common attribute set, allowing it to be set in the following rules:
- `rust_benchmark`
- `rust_binary`
- `rust_library`
- `rust_test`
Variables are provided in a string dictionary, and will be merged into the generated environment overriding existing …
> rustc: add arbitrary environment variables

- rust/private/rust.bzl
- rust/rust.bzl
- test/rust_test_binary/BUILD
- test/rust_test_binary/scripts/exec_with_test_env.sh
- test/rust_test_binary/tests/rust_test_that_requires_wrapping.rs
I have a case where I would like to build a rust binary exactly as output by `rust_test`, but not call it directly. Instead, I have a [`sh_test`](https://docs.bazel.build/versions/master/be/shell.html#sh_test) rule that will be the entrypoint for the test, acting as a test runner and setting up environment variables required by the test code.
This already works (amazing!), but I don't want to run the binary output by `rust_test` directly, as it will fail without the setup performed in the `sh_test` rule. This happens when running all tests with:
```bash
bazel test //...
```
In this PR, I have added the new rule  `rust_test_binary` which is simply the definition of `rust_test` with `test = True` removed, and docs updated.
If there's a way to make this an argument of the existing …
> rust: add rust_test_binary rule

- rust/repositories.bzl
rust_repository_set is a very convenient function to specify all of the
necessary http_repository rules and workspace setup calls.  It however,
forces the edition of rust to be 2015 in the calls of
BUILD_for_rust_toolchain from _load_rust_stdlib.
This change does the following:
* Adds an edition attr to rust_toolchain_repository (default: 2015)
* Adds an edition parameter to rust_repository_set (default: None)
* Adds documentation for rustfmt_version for both
* Throws in some buildifer fixes of function definitions
> Allow edition to be specified in rust_repository_set

- rust/repositories.bzl
My team uses the `build --incompatible_disallow_empty_glob` flag in our .bazelrc. When using `rust_repositories(version = "nightly", iso_date = "2020-05-15")` in our BUILD file, the build fails with the error:  
```
glob pattern 'lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/*.so' didn't match anything, but allow_empty is set to False.
```
This glob is part of the rustc_lib filegroup. This PR adds allow_empty to that glob, similar to the change made in #245.
> Fix rustc_lib srcs glob and allow it to be empty.

- rust/private/rust.bzl
- rust/private/rustc.bzl
- test/test_env/BUILD
- test/test_env/src/main.rs
- test/test_env/tests/run.rs
Since 1.43 cargo will set `CARGO_BIN_EXE`-prefixed env vars for each binary your crate depends on, so you can access them in integration tests.
Also, output binary names with the same name as the target, rather than replacing `-`s with `_`s, to better emulate how Cargo works.
> Support CARGO_BIN_EXE env vars

- rust/private/rust.bzl
- rust/private/rustc.bzl
We had an opportunity to put out binary without specifying `crate_type` as `bin`. 
In this case, we should add configurable crate_type and a flag to put out binary whenever.
With this patch, we can tackle this situation.
> add flag to allow putting out binary whenever

- cargo/cargo_build_script.bzl
serde-json relies on CARGO_CFG_TARGET_ARCH
Debugging is easier with backtraces
> Set a couple more env vars for build scripts

- README.md
- rust/repositories.bzl
Hopefully this will make it clear that the 2018 edition needs to be
explicitly specified.  This caught me by surprise initially, and seems
to have popped up in a few other areas.
See google/cargo-raze#165
> Add edition to rust_repositories, and update README

- cargo/cargo_build_script.bzl
Otherwise rustc crashes on launch
> Include rustc deps when running build scripts

- rust/private/rustc.bzl
Functionally, this code should be identical.
However, it (hopefully) is easier to read, and makes
subcomponents of the rustc command (parsing args, env, etc)
easier to generalize.
> Refactor rustc_compile_action

- WORKSPACE
- cargo/cargo_build_script.bzl
- cargo/cargo_build_script_runner/bin.rs
- cargo/cargo_build_script_runner/lib.rs
- examples/WORKSPACE
- examples/hello_sys/BUILD
- examples/hello_sys/bzip2-0.3.3.BUILD
- examples/hello_sys/bzip2-sys-0.1.9+1.0.8.BUILD
- examples/hello_sys/cc-1.0.54.BUILD
- examples/hello_sys/pkg-config-0.3.17.BUILD
- examples/hello_sys/src/main.rs
- examples/hello_sys/test.sh
- examples/hello_sys/workspace.bzl
- rust/private/clippy.bzl
- rust/private/rustc.bzl
And absolute paths are redacted into $EXEC_ROOT-relative paths
This mirrors Cargo's behaviour of accumulating link flags and passing
them to the linker - otherwise there's not much point in sys libraries
outputting them.
This currently over-adds out_dirs and link flags to all actions, rather
than just those that will invoke the linker - we can reduce that if we
have a clear indication of what targets will invoke a linker, but I
wanted to go with a safe-but-over-invalidating solution rather than
picking a bad heuristic.
Commits are separately useful to review.
Depends on https://github.com/bazelbuild/rules_rust/pull/343 (the first commit of this PR).
I have a WIP PR which removes both the new usage of system `tar` and the existing usages in the PR by building small implementations of `tar` …
>  Link flags are passed to transitive rdeps

- rust/repositories.bzl
Working with the Rust compiler crates requires the rustc-dev component. This is distributed separately from the standard library. This PR adds a new option to download the rustc-dev component which defaults to False. The component is only distributed with nightly Rust, so the `version` option must be set to "nightly".
> feat: Support downloading nightly rustc-dev components

- rust/private/rustc.bzl
The error message refers to `proc-macro-deps`, which is a string that only exists in this file. Updating the reference to say `proc_macro_deps` which is a common string in the repo and is well documented.
> Clarify error message

- cargo/cargo_build_script.bzl
- cargo/cargo_build_script_runner/bin.rs
- cargo/cargo_build_script_runner/lib.rs
Rather than discarding lines which are not directives to cargo, print
them.
Also, print a friendly message, rather than a backtrace, if the build
script itself exits non-0.
> Preserve and tidy stdout on failure

- cargo/cargo_build_script.bzl
- cargo/cargo_build_script_runner/bin.rs
> Remove run shell from build scripts runner

- cargo/cargo_build_script.bzl
- examples/ffi/c_calling_rust/BUILD
- rust/platform/triple_mappings.bzl
- rust/private/clippy.bzl
- rust/private/rustc.bzl
- rust/repositories.bzl
- rust/toolchain.bzl
Its minor but since `CcInfo` now exists we can state `staticlib` to be a statlclib and `cdylib` to be the relevant `.so`
> Export `CcInfo` for `staticlib` & `cdylib` allowing rust outputs to be used in c++ rules

- cargo/cargo_build_script_runner/bin.rs
It failed to parse empty depenv files due to how 'split' function works.
> Fix .depenv file parsing after #329

- examples/hello_lib/BUILD
- rust/private/rustc.bzl
The current code is failing for any cdylib or staticlib with
a rust dependency (without CcInfo provider).
Fixes #368.
> Do not add CcInfo from dependencies that don't have them

- rust/repositories.bzl
After nightly Rust builds after 2020-05-22 do not have the `libLLVM-10-*version*-nightly.so` dylib included with the normal rust-nightly gzip due to rust-lang/rust#70838. Therefore, nightly builds after this date need to download and extract the llvm-tools gzip to ensure this dylib is available.
> fix: Download llvm tools for nightly builds after 2020-05-22

- cargo/cargo_build_script.bzl
This is used e.g. by the protobuf crate build script.
> Provide CARGO_PKG_NAME and CARGO_PKG_VERSION* for build scripts

- WORKSPACE
Updating Skylib makes the repository build with --incompatible_disable_depset_items, which is planned for Bazel 4.0.
> Update Skylib dependency

- rust/private/rust.bzl
Its minor but I think time has passed on this usage, and we should pull the warning for backward compat
> Lint: Pull old warning for `rust_test`

- rust/private/rustdoc_test.bzl
Using File.path breaks builds with --nolegacy_external_runfiles option
as the gnerated script has use `external/rust/bin/rustdoc` that
referrers to legacy runfiles and File.short_path uses `../rust/bin/rustdoc`
> Fix rustdoc path in rustdoc_test with --nolegacy_external_runfiles option

- examples/ffi/c_calling_rust/BUILD
- examples/ffi/c_calling_rust/lib.rs
- proto/proto.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
This is a small fix I discovered where a `staticlib` or `cdylib` claims to export `CcInfo` for test crates.
Instead of mapping this all the way through (I am not sure what depending on a `rust_test` would mean) we just ignore / disallow `CcInfo` for test contexts.
> Fix `CcDep` info related to `rust_test`

- examples/WORKSPACE
- rust/repositories.bzl
Previously this was pulling from a list of known shas, but this list is
non-exhaustive, and needs to be updated every rust release.  This allows
the shas to be specified in rust_toolchain_repository,
rust_repository_set, rust_repositories.
> Allow sha256 values to be specified in rust_toolchain_repository

- .bazelignore
- WORKSPACE
- docs/BUILD
- docs/WORKSPACE
- docs/docs_deps.bzl
- docs/docs_repositories.bzl
- docs/update_docs.sh
- examples/WORKSPACE
- examples/examples_deps.bzl
- examples/examples_extra_deps.bzl
- examples/examples_repositories.bzl
- examples/ffi/rust_calling_c/c/matrix_test.c
- proto/repositories.bzl
- rust/repositories.bzl
This pull request contains various cleanup/quality-of-life improvements for the repository by clearly grouping and defining dependencies for the `docs` and `examples` workspaces. Ultimately, the files that are created in here can be moved entirely into their neighboring `WORKSPACE` files once https://github.com/bazelbuild/bazel/issues/1943 has been closed.
> Reorganized sub-workspace dependencies

- rust/repositories.bzl
This allows for `cargo` to be used from scripts which may want to invoke
`cargo`, while coupling the version used with the rest of the toolchain
used for the build.
> Extract cargo from rust toolchain tar

- renovate.json
This is a followup to the conversation in #407 
`renovate.json` is unused and should therefore be removed.
> Removed unused file

- proto/proto.bzl
- rust/private/clippy.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc_test.bzl
- rust/private/utils.bzl
- wasm_bindgen/wasm_bindgen.bzl
Changes:
- Added documentation containing type information for a large number of macros
- Cleans up `doc` attributes so stardoc renders cleaner
- Adds new pages to the `docs/update_docs.sh` output
- Rearranged a few macros to reduce code duplication
- Fixed some incompatibility warnings/buildifier defects
@acmcarther @mfarrugi @damienmg @smklein @dfreese
I would hugely appreciate if all code owners would take a look at 548d62ff981ab3569a10d6a515ac4f555d4ff134 and provide suggestions on how the documentations can be improved. I'm very bad at writing docs and this was largely a learning exercise for me so some of the docs may not be as clear as they should be. There are a few I was totally unsure of what to write (namely `get_compilation_mode_opts`, `_determine_lib_name`, `rust_toolchain`, …
> Improved internal and external documentation

- rust/platform/triple_mappings.bzl
Fixes:
ERROR: An error occurred during the fetch of repository 'rust_darwin_x86_64':
Traceback (most recent call last):
File "/private/var/tmp/_bazel_dae/5bd71d68278317a4c19e40755fc15392/external/io_bazel_rules_rust/rust/repositories.bzl", line 549, column 50, in _rust_toolchain_repository_impl
build_components.append(_load_rust_stdlib(ctx, target_triple))
File "/private/var/tmp/_bazel_dae/5bd71d68278317a4c19e40755fc15392/external/io_bazel_rules_rust/rust/repositories.bzl", line 477, column 41, in _load_rust_stdlib
stdlib_build_file = BUILD_for_stdlib(target_triple)
File "/private/var/tmp/_bazel_dae/5bd71d68278317a4c19e40755fc15392/external/io_bazel_rules_rust/rust/repositories.bzl", line 253, column 42, in BUILD_for_stdlib
binary_ext = system_to_binary_ext(system),
File …
> support iOS cross compile

- WORKSPACE
- bindgen/bindgen.bzl
- cargo/cargo_build_script.bzl
- docs/WORKSPACE
- docs/docs_deps.bzl
- docs/docs_repositories.bzl
- docs/docs_transitive_deps.bzl
- docs/flatten.md
- docs/rust_proto.md
- examples/WORKSPACE
- examples/examples_deps.bzl
- examples/examples_repositories.bzl
- examples/examples_transitive_deps.bzl
- proto/proto.bzl
- proto/repositories.bzl
- proto/toolchain.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc_test.bzl
- rust/repositories.bzl
- rust/rust.bzl
- wasm_bindgen/wasm_bindgen.bzl
- workspace.bzl
This change takes more out of #420 and addresses some buildifier defects and structural inconsistencies.
The way docs and examples had their `WORKSPACE` setup didn't fully rely on `io_bazel_rules_rust` to provide all it's dependencies. This has now been updated. The only thing required to use `rules_rust` is to call `rust_repositories` and `rust_workspace` in your WORKSPACE which is now demonstrated within the project.
I apologize for this PR being larger than I'd like. A lot of this was pulled out of #420. Going forward, it should be easier to make each commit represent a fixed buildifier defect.
> Addressed additional Buildifier defects

- rust/repositories.bzl
The Windows toolchain was ignoring the default provided to rust_repositories(), always using edition 2015, which caused errors about crates being unavailable if extern crate references were not in the code.
> rust_repositories() was not honoring edition default on Windows

- cargo/cargo_build_script.bzl
- rust/private/rustc.bzl
On Windows, MSVC requires INCLUDE to be set to the path of the standard
include files. Not sure if this is the best solution, but it solved issues with
missing includes mentioned in #423 for me.
> pass compile environment into build script

- cargo/cargo_build_script_runner/lib.rs
If the build script outputs enough, it fills up the stdout pipe,
blocks, and wait() never returns. Windows has a smaller pipe buffer,
so when compiling the blake3 crate for example, the compile gets stuck
after a few files have been compiled with the cc crate.
> fix deadlock while waiting for build script output

- rust/private/rustc.bzl
> Not generating CcInfo when out_binary is True

- .bazelci/presubmit.yml
- rust/repositories.bzl
Before this change, `rust-lld` is not found in RBE environment because they are not part of toolchain definition. This PR adds `rust-lld` and its runtime dependencies into toolchain definition, so they can work in RBE / docker-sandbox.
> Include wasm-lld in toolchain

- wasm_bindgen/raze/Cargo.toml
- wasm_bindgen/raze/overrides/backtrace-sys-0.1.29.BUILD
- wasm_bindgen/raze/remote/backtrace-sys-0.1.29.BUILD
This is something that should have been in #433 
See https://github.com/bazelbuild/rules_rust/pull/433#discussion_r505670820
> Updated wasm-bindgen backtrace dependency

- examples/hello_macro/BUILD
- examples/hello_macro/src/lib_2018.rs
- rust/private/rustc.bzl
This is done implicitly by cargo.
> Add --extern proc_macro for 2018 crates

- cargo/cargo_build_script.bzl
The existing rustc_env attribute is useful when the provided env var
will not differ between machines, but is not practical when each
user of the build script may require a different value, such as passing
in a custom path to a tool on their machine.
Fixes the issue mentioned in
https://github.com/bazelbuild/rules_rust/pull/314#issuecomment-624524139
by starting from the default environment. I did not make a change in rustc.bzl,
so this only applies to build scripts at the moment.
> support --action_env vars in build scripts

- rust/platform/platform.bzl
use -msvc variant on Windows
Both the standard Rust installer, and rust_repositories() in this repo
default to the -msvc platform. Since it is the default on Windows,
this change comments out the -gnu variant instead.
This change (along with some fixes in cargo raze) allows crates with
msvc-specific build deps to compile. I do not know enough about Bazel
to say if it will have any unintended side effects, but it seems to
work for me, and allows a moderate sized project with about 250
crate dependencies to compile using the default toolchain.
> use -msvc variant on Windows

- cargo/cargo_build_script.bzl
- examples/cargo/build_script.rs
Various crates expect to be able to access files relative to the
crate root, and we were giving them the parent directory (eg __main__)
instead. An example crate that fails to compile without this change
is blake3.
> run build scripts in the crate folder instead of the workspace

- bindgen/bindgen.bzl
- cargo/cargo_build_script.bzl
- proto/proto.bzl
- proto/toolchain.bzl
- wasm_bindgen/wasm_bindgen.bzl
https://docs.bazel.build/versions/master/skylark/rules.html#configurations
> Note: Historically, Bazel didn’t have the concept of execution platforms, and instead all build actions were considered to run on the host machine. Because of this, there is a single “host” configuration, and a “host” transition that can be used to build a dependency in the host configuration. Many rules still use the “host” transition for their tools, but this is currently deprecated and being migrated to use “exec” transitions where possible.
> 
> There are numerous differences between the “host” and “exec” configurations:
> 
> - “host” is terminal, “exec” isn’t: Once a dependency is in the “host” configuration, no more transitions are allowed. You can keep making further configuration transitions once you’re …
> Switching "host" configurations to "exec"

- docs/BUILD
- rust/private/rustc.bzl
- workspace.bzl
We use a synthetic `bazel_version` repository to make the Bazel version
available in more contexts (see [bazelbuild/bazel#8305][i8305]). But
some other repositories do so, too, with the same repository name and a
different repository structure. In particular, it is not currently
possible to use `rules_rust` and certain versions of `upb` (downstream
of protobuf) in the same repository, due to their definition here:
https://github.com/protocolbuffers/upb/blob/c1357afb2e39df671d89eaec49033b5329f36a3e/bazel/repository_defs.bzl#L7-L10
An easy workaround is to disambiguate the name. It looks much easier to
change `rules_rust` than to change `upb` and update its long chain of
workspace dependencies, hence this patch. :-)
See my comment on #268 for more details and a full repro: …
> Rename `bazel_version` repository to avoid conflict

- rust/private/rustc.bzl
- test/transitive_lib/BUILD
- test/transitive_lib/build.rs
- test/transitive_lib/dll_user.rs
- test/transitive_lib/dll_user_user.rs
@illicitonion Would you mind looking over this and seeing if it's sane? It's modifying code that was added in a previous pull request of yours: https://github.com/bazelbuild/rules_rust/pull/346
I use a crate for creating Python extension modules called pyo3. It has code in it like this:
```
#[cfg_attr(windows, link(name = "pythonXY"))]
extern "C" {
pub fn PyNode_Compile(arg1: *mut _node, arg2: *const c_char) -> *mut PyCodeObject;
```
Its build.rs script locates the relevant library name, and spits out a link flag that maps it to the alias:
```
-lpythonXY:python38
```
The pyo3 crate compiles successfully, but when I attempt to compile a crate that depends on pyo3 on Windows, the build fails, complaining that the above alias has been provided but there are no mentions of pythonXY in my …
> add buildscript link flags only to parent crate

- rust/private/rustc.bzl
Bazel 3.7.0 introduced a change (301b96b223b0c0) in the way it reports
file paths for external packages. This ensures that rules_rust sets the
right value for CARGO_MANIFEST_DIR both for Bazel < 3.7.0 and >= 3.7.0.
Note that if this changed once, it might change again, so the right
thing to do is to use a bazel API to do that work once it's available.
> Correct CARGO_MANIFEST_DIR values for Bazel <3.7.0

- cargo/cargo_build_script.bzl
- docs/BUILD
- docs/README.md
- docs/all.bzl
- docs/flatten.md
- docs/rust_proto.md
- proto/toolchain.bzl
- rust/private/rustc.bzl
- rust/private/utils.bzl
- wasm_bindgen/repositories.bzl
Added some missing documentation from #468 and #469
> Updated documentation

- workspace.bzl
Summary:
When upgrading to Bazel 3.0.0, I saw:
> Bazel 3.0.0 is too old to use with rules_rust, please use at least
> Bazel 3.0.0, preferably newer.
We need to check `version >= min_version`, not `version > min_version`.
Test Plan:
From `examples/`, running `bazel query //hello_world/...` fails before
this patch and passes after it at Bazel version 3.0.0. It also still
fails at 2.1.0 and still passes at 3.7.0.
wchargin-branch: permit-exactly-min-version
> workspace: fix off-by-one in version check

- bindgen/repositories.bzl
I was trying to setup some testing on various versions of bazel when I
kept running into this issue that causes bazel query to error out.
However, the error handling is specifc to earlier 3.X series versions of
bazel.  Prior to this patch, this causes and error:
```
bazel-3.4.0 query -- //... - @examples//...
```
however, this does not error out:
```
bazel-3.5.0 query -- //... - @examples//...
```
which is why rules_rust tests are probably still passing.
This removes the unintentional paren, which removes the issue in all 3.X
cases that I tested.
> Remove incorrect paren in bingen repositories

- .bazelci/presubmit.yml
This is currently 3.0.0, but given discussion that I have seen, that was
probably too aggressive.  However, until we test against our minimum
supported version, it isn't going to be reasonable to provide releases
as suggested by #415.
> Add a CI target on the minimum supported version of bazel

- cargo/cargo_build_script_runner/bin.rs
build_script_runner was gathering details based on the host platform
instead of the target platform. This was causing a cross-compile of the
ring crate to fail to link, as it was making build-time decisions based
on the host OS instead of the target one.
> use target platform for CARGO_CFG_TARGET_*

- rust/private/clippy.bzl
- rust/private/rust.bzl
Prior to this PR, bin crates with more than one file in srcs would fail with this error:
```
$ bazel build --aspects=@io_bazel_rules_rust//rust:rust.bzl%rust_clippy_aspect --output_groups=clippy_checks //...
INFO: Invocation ID: c3647be4-e5fe-4f90-a1a4-c9a84c17c45c
ERROR: /home/user/repo/BUILD:5:12: in @io_bazel_rules_rust//rust:private/clippy.bzl%rust_clippy_aspect aspect on rust_binary rule //foo:bar:
Traceback (most recent call last):
File ".../io_bazel_rules_rust/rust/private/clippy.bzl", line 53, column 26, in _clippy_aspect_impl
root = crate_root_src(ctx.rule.attr, srcs = rust_srcs)
File ".../io_bazel_rules_rust/rust/private/rust.bzl", line 115, column 13, in crate_root_src
fail("No {} source file found.".format(" or ".join(file_names)), "srcs")
Error in fail: attribute srcs: No …
```
> Fix root detection in clippy for bin crates

- proto/proto.bzl
- proto/toolchain.bzl
Some small cleanup to make the rules more readable
> Updated `grpc` flag to `is_grpc` to make it more apparent it's a bool

- rust/private/clippy.bzl
- rust/private/rustc.bzl
Skipping linking for clippy can dramatically accelerate results. Local testing in my repo shows a speedup anywhere from 30-70% with real time going from ~12-15s -> 4-8s for leaf targets. Larger targets will generally reap greater results from skipping linking.
> Skip linking for clippy aspect for faster builds

- bindgen/bindgen.bzl
- examples/hello_lib/tests/greeting.rs
- rust/private/clippy.bzl
Currently warnings from rustc such as an unused import are printed
during first execution, but they do not fail the build. If cargo users
run clippy again, the same warnings get printed, but with Bazel nothing
is shown, as the previous success is cached.
This patch changes all warnings into errors, with the rationale being
that if we're failing for any clippy warning, it probably makes sense
to fail for rustc warnings as well.
If there is objection to this change, I'd be happy with some way to
customize the behaviour instead, but was not sure how that might be done.
> fail build on any warnings when running clippy

- cargo/cargo_build_script.bzl
- examples/env_locations/BUILD
- examples/env_locations/main.rs
- rust/private/rustc.bzl
- rust/private/utils.bzl
The ${pwd} resolution in build_script_env is necessary during the compilation stage as well, as otherwise we can't use things like include_str!() on generated files. Starting with a test that demonstrates the issue; will follow up with a fix.
> Allow usage of $(location ...) in rustc_env as well, to include_str!() generated files.

- cargo/cargo_build_script.bzl
- examples/hello_lib/BUILD
- proto/toolchain.bzl
- rust/private/rust.bzl
Right now if you have a rust_test/benchmark which has -s in the name,
you get an error that the output file wasn't created by the action.
This renames a `rust_test` in examples to hit the bug, and then fixes it.
> Perform - to _ replacement in test output names

- docs/rust.md
This PR is related to #482.
I fixed a minor mistakes in the sample code.
> fix: change test for `greet` method, instead of `greeting`

- cargo/cargo_build_script_runner/bin.rs
- cargo/cargo_build_script_runner/lib.rs
I was trying to read through this code and found it a bit hard to follow. This (to me) makes it a bit more readable. There should otherwise be no functional change here.
> Slight cleanup of `cargo_build_script_runner` + ran rustfmt

- rust/repositories.bzl
Any repository rule that attempts to use this macro is required to have have a `"sha256s": attr.string_dict()` attribute. This should not be required (and is inconsistent with the current documentation of the macro). This PR fixes that.
> Fixed issue where repository_ctx for `load_arbitrary_tool` required `sha256s` attribute.

- examples/cargo/lib.rs
- examples/ffi/rust_calling_c/src/matrix.rs
- rust/private/clippy.bzl
Unit tests with a 'crate = ...' argument have no rust_srcs, so
clippy was not running for them.
> support clippy aspect in unit tests as well

- docs/flatten.md
- docs/rust_repositories.md
- rust/repositories.bzl
environment variable `STATIC_RUST_URL` will work as before.
> #550 rust_toolchain_repository: add urls to enable project specific rust file server mirrors

- cargo/cargo_build_script.bzl
- cargo/cargo_build_script_runner/bin.rs
- cargo/cargo_build_script_runner/lib.rs
This prevents noisy output from `cargo_build_script` from being printed to the terminal, instead two log files are generated (`stdout`, `stderr`) which contain the raw output of the underlying `build.rs` script
Currently users see something similar to the following output when they use `cargo_build_script`:
(note, uplaoded as a file because there's a lot of output)
[big_output.log](https://github.com/bazelbuild/rules_rust/files/5777780/big_output.log)
In general, this masks important information in a sea of arbitrary log lines. The changes in this PR update the output to:
```output
INFO: From CargoBuildScriptRun external/cargo_raze__libssh2_sys__0_2_20/libssh2_sys_build_script.out_dir:
Build Script Warning: libssh2/src/bcrypt_pbkdf.c:84:46: warning: expression does not compute the number …
```
> cargo_build_script now only prints warnings to stderr.

- WORKSPACE
- rust/repositories.bzl
- test/deps.bzl
- test/load_arbitrary_tool/BUILD.bazel
- test/load_arbitrary_tool/load_arbitrary_tool_test.bzl
In https://github.com/bazelbuild/rules_rust/pull/545 I fixed an issue where `load_arbitrary_tool` could not be used in repository rules that did not specify particular attributes. This issue was then reintroduced in https://github.com/bazelbuild/rules_rust/issues/551. This PR fixes the issue again and adds a test to prevent this from happening again in the future.
> Fixed regression in `load_arbitrary_tool` causing it to require attrs

- bindgen/BUILD
- bindgen/raze/BUILD.bazel
- bindgen/raze/remote/BUILD.bindgen-0.55.1.bazel
- docs/BUILD
- docs/all.bzl
- docs/flatten.md
- docs/rust_bindgen.md
- docs/rust_proto.md
- docs/rust_wasm_bindgen.md
- proto/BUILD
- proto/raze/BUILD.bazel
- proto/raze/remote/BUILD.grpc-compiler-0.6.2.bazel
- proto/raze/remote/BUILD.protobuf-codegen-2.8.2.bazel
- rust/private/utils.bzl
- util/BUILD.bazel
- wasm_bindgen/BUILD
- wasm_bindgen/raze/BUILD.bazel
- wasm_bindgen/raze/remote/BUILD.assert_cmd-1.0.2.bazel
- wasm_bindgen/raze/remote/BUILD.cc-1.0.66.bazel
- wasm_bindgen/raze/remote/BUILD.difference-2.0.0.bazel
- wasm_bindgen/raze/remote/BUILD.docopt-1.1.0.bazel
- wasm_bindgen/raze/remote/BUILD.leb128-0.2.4.bazel
- wasm_bindgen/raze/remote/BUILD.multipart-0.15.4.bazel
- wasm_bindgen/raze/remote/BUILD.wait-timeout-0.2.0.bazel
- wasm_bindgen/raze/remote/BUILD.wit-schema-version-0.1.0.bazel
- wasm_bindgen/repositories.bzl
Due to the changes released in `cargo-raze 0.9.0`, we can now generate documentation for `.bzl` files that load a `crates.bzl` file generated by `cargo-raze`. This PR updates the `wasm-bindgen` outputs and the documentation.
edit: I expanded the scope of this change to also include the `*_repositories` macros from the `bindgen` and `proto` rules since the delta was small enough.
> Added missing macros to rendered documentation

- examples/ffi/rust_calling_c/c/BUILD
Avoid build artifacts name conflict after `supports_dynamic_linker` feature was removed from cc toolchain for macOS
Context: https://github.com/bazelbuild/bazel/issues/4341#issuecomment-762576370
> Fix test target on macOS with Bazel@HEAD

- bindgen/README.md
- docs/index.md
- proto/README.md
I forgot some docs in #500 This fixes them.
> Regenerate documentation

- docs/index.md
As it's written, it currently doesn't work be cause the commit is behind https://github.com/bazelbuild/rules_rust/commit/1fe23158e5316c17b2ee2a252ee7165c5d83cc93
> Fixed revision referenced in docs

- rust/private/rustc.bzl
This was left out by mistake during an earlier refactor.
> Determinism fix

- docs/BUILD
- docs/docs_deps.bzl
- docs/docs_transitive_deps.bzl
- docs/flatten.md
- docs/rust_repositories.md
- examples/examples_deps.bzl
- examples/examples_repositories.bzl
- examples/examples_transitive_deps.bzl
- wasm_bindgen/repositories.bzl
- wasm_bindgen/wasm_bindgen.bzl
This does more or less the same thing as [@rules_nodejs//packages/labs/protobufjs:ts_proto_library.bzl](https://github.com/bazelbuild/rules_nodejs/blob/1689fa185f9006dba198c079d848be18dceec38c/packages/labs/protobufjs/ts_proto_library.bzl#L115-L149) but this change drops the legacy provider syntax.
closes https://github.com/bazelbuild/rules_rust/issues/443
> Fixed legacy-provider-syntax for wasm_bindgen

- .gitignore
- BUILD
- bindgen/bindgen.bzl
- cargo/cargo_build_script.bzl
- examples/cargo/BUILD
- examples/env_locations/BUILD
- examples/ffi/rust_calling_c/c/BUILD
- examples/ffi/rust_calling_c/simple/BUILD
- examples/proto/helloworld/greeter_client/BUILD
- examples/proto/helloworld/greeter_server/BUILD
- proto/proto.bzl
- proto/toolchain.bzl
- rust/BUILD
- rust/common.bzl
- rust/platform/BUILD
- rust/private/BUILD
- rust/private/clippy.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc.bzl
- rust/private/rustdoc_test.bzl
- rust/rust.bzl
- test/process_wrapper/BUILD
- test/rustfmt/rustfmt_generator.bzl
- wasm_bindgen/wasm_bindgen.bzl
This PR achieves the following:
* buildifier bzl-visibility check was not detecting violations as it assumes `private` package, not just a directory
* adds `//rust:common.bzl` file where all the publicly available and supported API for writing custom rules interacting with Rust will reside
* the private package now sets the stability expectations, and it forces us to think about API layering and abstractions.
This turned out to be much bigger PR than expected :(
> Add //rust/private/BUILD (therefore create a package there)

- proto/proto.bzl
- rust/private/clippy.bzl
- rust/private/common.bzl
- rust/private/providers.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc.bzl
- rust/private/rustdoc_test.bzl
- rust/rust.bzl
This PR introduces a `rust_common` struct that will be used to access the Rust Sandwich API (the term first introduced in https://bazel.build/designs/2016/08/04/extensibility-for-native-rules.html and used ever since, for example https://blog.bazel.build/2017/03/07/java-sandwich.html :)
The motivation for this change:
* to provide a single place for other rule authors where they can see what APIs are available.
* to enable rule authors to make their custom rules interacting with Rust rules backwards and forwards compatible using the `hasattr` function. `hassattr` only works on struct fields, not on globals.
The plan is to eventually refactor uses of all private APIs to go trough `rust_common`.
Credit goes to brave owners of `rules_swift` who discovered how useful this approach is the hard …
> Introduce rust_common struct

- rust/private/rustc.bzl
Nothing crazy, just noticed a missing `doc` attr from https://github.com/bazelbuild/rules_rust/pull/525 and wanted to add it.
And FYI. Lists will print with proper formatting.
```python
print("{} expected a value in `{}` but got `{}`".format(
ctx.label,
_error_format_values,
raw,
))
```
```output
DEBUG: /Users/user/Code/rules_rust/rust/private/rustc.bzl:862:10: //:error_format expected a value in `["human", "json", "short"]` but got `human`
```
> Slight cleanup and added some documentation.

- cargo/cargo_build_script.bzl
- rust/private/clippy.bzl
- rust/private/rustc.bzl
- rust/private/utils.bzl
Currently `rules_rust` won't link against the C++ standard library in case
C++ toolchain is the `static_link_cpp_runtimes` feature (therefore when
it uses `cc_toolchain.static_runtime_lib` and `cc_toolchain.dynamic_runtime_lib`
attributes to declare which version of C++ static library should be
linked into the final binary).
This PR modifies `add_native_link_flags` to also look into the
C++ toolchain and depend on C++ standard library from there.
While there, I moved the `get_cc_toolchain` function to the `utils.rs`,
to be consistent with the handling of the Rust toolchain.
> Pass C++ runtime lib when C++ toolchain declares it

- BUILD
This is required for Google internal workflows, hopefully it won't bother other users.
> Export the LICENSE file

- docs/BUILD
- docs/all.bzl
- docs/defs.md
- docs/flatten.md
- docs/index.md
- rust/BUILD
- rust/defs.bzl
- rust/private/rust.bzl
- test/unit/native_deps/native_deps_test.bzl
This PR splits rust_library into multiple smaller rules:
* rust_library: rust_library will represent a non-transitive library
similar to how cc_library, java_library and others behave. It will
always provide CrateInfo, and depending on it will always mean you can
access the crate from source. Once we support dynamic linking we can
consider producing both rlib and dylib from rust_library, but let's
leave that for another discussion.
* rust_static_library: this will only provide CcInfo and it will
represent an archive of all transitive objects, both Rustc-made and
native.
* rust_shared_library: this will only provide CcInfo and it will
represent an shared library of all transitive objects, both Rustc-made
and native.
* rust_proc_macro: similar to rust_library, but with different
crate_type …
> Split rust_library and add //rust:defs.bzl

- rust/platform/platform.bzl
Add alias for OSX to "macos" to match the modern name for the OS.
> Added `//rust/platform:macos` alias

- README.md
Fix markdown syntax for the Rust programming language.
The link was using a link definition without link.
Since all other links use inline style, this commit also follows this style.
> Add Missing link definition in README.md

- rust/private/rust.bzl
- rust/private/rustc.bzl
ld can handle .rlib archives, since they're really just standard ar(1)
archives like a .a file with some extra metadata. As a result, we can avoid
using staticlib crates when building mixed C++/Rust binaries.
This doesn't correctly handle libstd et al (yet), or deal with some generated
symbols that rustc produces when it drives the linking step, but it's a start.
> rules_rust: make it possible to use non-staticlib rust_library targets in c++ deps

- rust/private/rustc.bzl
- test/unit/native_deps/native_deps_test.bzl
Build scripts may add -l flags to dependees, and without the relevant -L
flags those -l flags may fail to resolve, causing build failures.
> Add -L but not -l to rlib compilations

- rust/private/rustc.bzl
This should have been a part of https://github.com/bazelbuild/rules_rust/pull/576.
> Add -Lnative flags for C++ runtime library

- .bazelci/presubmit.yml
- test/BUILD
- test/unit/cc_info/cc_info_test.bzl
I realized we don't run tests on Windows. This PR fixes that. While there I also enabled tests on RBE.
> Increase CI coverage

- bindgen/bindgen.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc_test.bzl
- rust/private/utils.bzl
- test/unit/native_deps/alwayslink.cc
- test/unit/native_deps/native_deps_test.bzl
In order to do this, we have to inline get_libs_for_static_executable so we
can interact with the LibraryToLink entity as we're categorizing staticlibs.
Fixes #325.
> rustc: correctly handle alwayslink staticlibs

- rust/private/rustc.bzl
I tripped on --incompatible_disable_depset_items which appears to be
on by default at work.
> rustc: pass depset as transitive depset, rather than direct

- rust/private/rust.bzl
The ability to build Wasm libraries as executables is needed to support
WASI reactors (Wasm executables with multiple entrypoints).
This is a temporary workaround, and we should be able to use crate-type
"bin" when a proper support for WASI reactors (rust-lang/rust#79997) is
stabilised is Rust.
This feature was added in #312, and most recently broken in #592.
Signed-off-by: Piotr Sikora <piotrsikora@google.com>
> Re-add support for building Wasm libraries as executables.

- rust/toolchain.bzl
Part of the work on #635, but not sufficient to fix it.
> Add cpp toolchain requirement for rust_toolchain

- rust/private/rust.bzl
- rust/private/rustc.bzl
Was trying to remove uses of to_list() where possible.  While this
change doesn't have any serious effect, the hope is it sets up future
changes that do start to remove more of them.
> Move assert out of compile actions

- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/private/utils.bzl
- test/build_env/BUILD.bazel
- test/build_env/tests/custom_crate_name.rs
As part of this change, I've moved the formerly private `_crate_name` function from rust.bzl to utils.bzl and renamed it to `crate_name_from_attr`.
I've also had to add a `hasattr(attr, "crate_name")` check to this function because `rustc_compile_action` (which calls through to `_get_rustc_env`) gets called from the implementation of the Rust proto rules, and those don't have a `crate_name` attribute (and it wouldn't make sense to add one either).
> Respect `crate_name` attribute when setting CARGO_CRATE_NAME.

- rust/private/rustc.bzl
- rust/private/rustdoc_test.bzl
It appears to already be a depset, just happens to be flattened.  It's
not a part of the external API, so, in theory, this should have an
effect.
> Change transitive_libs in DepInfo to a depset

- .github/workflows/crate_universe.yaml
https://github.com/bazelbuild/rules_rust/actions/runs/726775754 succeeded but actually failed to push changes to the `main` branch which should have generated a failure. This change fixes that.
> Fixed error handling in crate_universe build script.

- crate_universe/defs.bzl
---
d73366b feat(crate_universe): use REPIN or RULES_RUST_REPIN to enable pinning
Make the pinning controlling env var match what was recently done in
rules_jvm_external ([1][]).
You can use `REPIN=1` (or any other value) to repin all your lockfiles,
or `RULES_RUST_REPIN=1` (or any other value) to only repin your
rules_rust lockfiles.
[1]: https://github.com/bazelbuild/rules_jvm_external/blob/b2e061d6ceaa81d48a513530f48c2df403ba7dbc/coursier.bzl#L340
<br/>
> feat(crate_universe): use REPIN or RULES_RUST_REPIN to enable pinning

- bindgen/README.md
The link was broken by the recent `BUILD` -> `BUILD.bazel` rename.
> Update link in README.md

- .github/workflows/crate_universe.yaml
This github action should not run on forks. This prevents each job from being kicked off in cases where users open a PR from their fork if they make changes on their `main` branch.
> crate_universe github actions no longer run on forks

- .github/workflows/crate_universe.yaml
We need to work out how users should consume these binaries, but for now
this reliably fails so let's stop doing it.
Instead, `cat` out what the the contents of the generated file _would_
be, for easy copy and paste by people working on the rules.
> Remove commit and push step of actions

- .github/workflows/crate_universe.yaml
- crate_universe/README.md
- crate_universe/deps.bzl
This creates a pre-release with the following message
I've also added a `README` to explain to users how to use the rule in it's current state.
> Updated tag message for crate_universe releases

- docs/flatten.md
- docs/rust_proto.md
- proto/proto.bzl
- proto/repositories.bzl
- proto/toolchain.bzl
- wasm_bindgen/repositories.bzl
Users looking to register their own toolchain sometimes stumble over the fact that every use of `rust_grpc_library` or `rust_proto_library` now requires them to also add the appropriate targets to the `rust_deps` attributes. This is easily missed and not necessary. Instead, these dependencies should be added to the `@rules_rust//proto:toolchain` being used so there's a single source of truth for all the dependencies required by these rules.
Additionally, this allows users to optionally __not__ register the default toolchain in cases where they want to define their own but would like to ensure other dependencies are brought in.
closes https://github.com/bazelbuild/rules_rust/issues/483
> Moved proto deps into toolchain to avoid confusing boiler plate code

- WORKSPACE.bazel
- crate_universe/Cargo.lock
- crate_universe/Cargo.toml
- crate_universe/defs.bzl
- crate_universe/src/config.rs
- crate_universe/src/consolidator.rs
- crate_universe/src/main.rs
- crate_universe/src/parser.rs
- crate_universe/src/renderer.rs
- crate_universe/src/resolver.rs
- crate_universe/src/serde_utils.rs
- crate_universe/tests/integration.rs
- crate_universe/tests/renderer.rs
- examples/crate_universe/uses_sys_crate/lockfile.lock
- rust/repositories.bzl
Notable changes in this PR:
- `crate_universe` `lockfile` attributes are now rendered as json files instead of starlark dumps
- `crate_universe_resolver` now accepts a `repository_dir` argument for the path to the new repository. This should be preferable to a single output file for all dependencies.
- The `cargo-raze` dependenciy has been updated to a pin which implements the required sorting and de-serialization.
- Formatted `use` declarations
- Updated dependencies
- `CARGO` and `RUSTC` environment variables are now ignored in determining the digest. This should be safe given that `cargo version` is an input to generating the lockfile hash.
- `repository_template` has been renamed to `crate_registry_template`, which is more correct.
- The …
> `crate_universe` now renders json formatted lockfiles

- crate_universe/BUILD.bazel
- crate_universe/defs.bzl
- crate_universe/private/BUILD.bazel
- crate_universe/src/config.rs
- crate_universe/src/consolidator.rs
- crate_universe/src/resolver.rs
- docs/BUILD.bazel
- docs/all.bzl
- docs/crate_universe.md
- docs/defs.md
- docs/docs_repositories.bzl
- docs/flatten.md
- docs/rust_proto.md
- docs/rust_repositories.md
- docs/rust_wasm_bindgen.md
Additionally, this renames `crate.override.extra_rust_env_vars` to `crate.override.extra_rustc_env_vars` to be more consistent with the behavior of that field
> Add generated docs for `crate_universe`

- docs/BUILD.bazel
- docs/flatten.md
- docs/index.md
- docs/rust_analyzer.md
- docs/rust_analyzer.vm
- docs/rust_wasm_bindgen.md
- docs/rust_wasm_bindgen.vm
- rust/private/rust_analyzer.bzl
- tools/rust_analyzer/BUILD.bazel
- tools/rust_analyzer/deps.bzl
Special thanks to @yagehu for writing the bulk of the `rust-analyzer` docs (https://github.com/bazelbuild/rules_rust/pull/649)!!
The changes here reduce the noise in the top landing page of the docs and move rule specific information into the page that covers them.
> Updated wasm-bindgen docs and added rust-analyzer docs 

- .bazelci/presubmit.yml
We already disable all sys crates from our tests, so this is keeping in
that fashion. Looks like the issues here aren't crate_universe specific.
> Run basic crate_universe example on Windows

- cargo/cargo_build_script_runner/lib.rs
- test/build_env/src/build.rs
- test/build_env/tests/cargo.rs
> Escape trailing backslashes in build script env vars

- .bazelci/presubmit.yml
- docs/BUILD.bazel
- docs/flatten.md
- docs/index.md
- docs/rust_clippy.md
- docs/rust_clippy.vm
- rust/private/clippy.bzl
The `_rust_sources` check seems redundant here. [CrateInfo](https://github.com/bazelbuild/rules_rust/blob/feaeb7ab712da45c1c94f7950e799d79e367ddeb/rust/private/providers.bzl#L17-L32) has a `srcs` field which should contain the exact same data and because the implementation filters for targets which only contain the `CrateInfo` provider, this should be limited to targets which have a `srcs` attribute that only accept `.rs` files:
https://github.com/bazelbuild/rules_rust/blob/feaeb7ab712da45c1c94f7950e799d79e367ddeb/rust/private/rust.bzl#L660-L669
Happy to hear a good reason why we shouldn't use `CrateInfo.srcs` though.
Additionally, this adds a top level section for `rust_clippy` to the docs.
> Removed redundant check for srcs in clippy

- docs/flatten.md
- docs/rust_wasm_bindgen.md
- examples/wasm/BUILD.bazel
- examples/wasm/hello_world_wasm_test.js
- examples/wasm/main.rs
- rust/private/rust.bzl
- rust/private/rustc.bzl
- wasm_bindgen/wasm_bindgen.bzl
This allows specifying a `target` like `web` or `nodejs` in `wasm_bindgen` and ensures that you can build a wasm `rust_shared_library`.
Closes #627
> wasm_bindgen: Add support for non-bundler target configs

- docs/flatten.md
- docs/rust_analyzer.md
- docs/rust_clippy.md
- docs/symbols.bzl
The links for `rust_analyzer_aspect` and `rust_clippy_aspect` lead to nothing. This fixes that by actually rendering those docs
> Added missing aspects to documentation

- bindgen/bindgen.bzl
I tried setting the examples to manual while testing another change and found this. `rust_bindgen_library` targets should support tags
> Allow tags to be applied to bindgen libraries.

- rust/rust_common.bzl
It seems there should be a single source of truth here? The only difference seems to be in the docs for the parameters:
```diff
diff --git a/rust/private/providers.bzl b/rust/private/providers.bzl
index 53bfbc8..549e371 100644
--- a/rust/private/providers.bzl
+++ b/rust/private/providers.bzl
@@ -18,15 +18,15 @@ CrateInfo = provider(
doc = "A provider containing general Crate information.",
fields = {
"aliases": "Dict[Label, String]: Renamed and aliased crates",
-        "deps": "depset[Provider]: This crate's (rust or cc) dependencies' providers.",
+        "deps": "List[Provider]: This crate's (rust or cc) dependencies' providers.",
"edition": "str: The edition of this crate.",
"is_test": "bool: If the crate is being compiled in a test context",
"name": "str: The name of this crate.", …
```
> Deduplicate the CrateInfo provider

- docs/flatten.md
- docs/rust_analyzer.md
- docs/rust_analyzer.vm
- docs/rust_repositories.md
- rust/repositories.bzl
This is a tar containing a huge number of files (hundreds of thousands)
which can take double-digit seconds to extract.
It's only used for rust analyzer support, so hide this behind a flag
people can opt in to if they want.
> rustc_src is optional

- WORKSPACE.bazel
- examples/examples_deps.bzl
- rust/private/rust_analyzer.bzl
- rust/repositories.bzl
In this PR we remove hardcoded assumption about where rust-analyzer support code looks for rustc sources, and instead read that information from the `rust_toolchain.rustc_src`. We also handle the case when rustc sources are actually in the main repository, so there is no need to use the `__EXEC_ROOT__/` prefix for its path.
> Ask rust_toolchain for rustc_src in rust_analyzer.bzl

- WORKSPACE.bazel
- docs/flatten.md
- docs/rust_repositories.md
- examples/examples_deps.bzl
- rust/private/rust_analyzer.bzl
- rust/repositories.bzl
- rust/toolchain.bzl
This PR renames the existing, but quite recently added attribute of `rust_toolchain` from `rustc_src` to `rustc_srcs`. The latter is more common in the Bazel ecosystem.
I mistyped the attribute name a few times myself, and also got feedback from colleagues that they did so as well :)
> Rename rustc_src to rustc_srcs for bazel consistency

- docs/cargo_build_script.md
- docs/crate_universe.md
- docs/defs.md
- docs/page.bzl
- docs/rust_analyzer.md
- docs/rust_bindgen.md
- docs/rust_clippy.md
- docs/rust_doc.md
- docs/rust_proto.md
- docs/rust_repositories.md
- docs/rust_wasm_bindgen.md
This helps developers avoid accidentally sending PRs against generated content.
Based on upstream template https://github.com/bazelbuild/stardoc/blob/master/stardoc/templates/markdown_tables/header.vm
> Include generated comment in docs

- tools/rustfmt/srcs/main.rs
Close #744 
`//tools/rustfmt` has been built successfully using following `.bazelrc`.
```
build --aspects=@rules_rust//rust:defs.bzl%rust_clippy_aspect
build --output_groups=+clippy_checks
```
> Fix clippy warnings for //tools/rustfmt

- tools/rust_analyzer/BUILD.bazel
- tools/rust_analyzer/main.rs
- tools/rustfmt/BUILD.bazel
The command `bazel run @rules_rust//tools/rust_analyzer:gen_rust_project` fails when run configuring `.bazelrc` like bellow.
```
build --aspects=@rules_rust//rust:defs.bzl%rust_clippy_aspect
build --output_groups=+clippy_checks
```
> Fix clippy warnings for //tools/rust_analyzer:gen_rust_project

- rust/private/rustfmt.bzl
I forgot to add this attribute in the initial PR. Now the check should appropriately use the configured `rustfmt.toml` file.
> `rustfmt_aspect` now appropriately uses a config

- rust/repositories.bzl
Sometime over the past year the layout of rustc-dev's nightly release has changed.
> Fix rustc-dev

- crate_universe/CONTRIBUTING.md
- examples/crate_universe/README.md
This adds a README.md to the `examples/crate_universe` directory in order to explain that the `RULES_RUST_CRATE_UNIVERSE_BOOTSTRAP` environment variable
must be set to `true` in order for the examples to "just work."
It also removes reference to `bootstrap.sh` from the
`crate_universe/CONTRIBUTING.md` file since `bootstrap.sh` no longer exists.
> [crate_universe] Add README to `examples/crate_universe` directory

- .bazelci/presubmit.yml
- tools/runfiles/runfiles.rs
These are typically used on Windows when using symlinks which are needed
for directory based runfiles is not possible.
Fixes https://github.com/bazelbuild/rules_rust/issues/616.
> Add support for manifest based runfiles.

- examples/ffi/rust_calling_c/c/BUILD.bazel
Seems the RBE toolchain is not working well with C++ dynamic mode tests.
Rather than struggling through the complicated fixing of the toolchain
we tell Bazel to not use dynamic mode.
Fixes https://github.com/bazelbuild/rules_rust/issues/589.
> Fix @examples//ffi/rust_calling_c/c/native_matrix_test on RBE.

- rust/private/rustc.bzl
Runtime linking with rpaths works correctly on darwin with only this change, for dylibs that have the correct extension (dylib) and the correct rpath configuration. Runtime linking against dynamic libraries created by bazel targets remains broken, due to them not having install names set correctly. That is fixed by using --incompatible_macos_set_install_name after https://github.com/bazelbuild/bazel/pull/13427.
I have attached a zip file with a simple example workspace demonstrating this.
[example.zip](https://github.com/bazelbuild/rules_rust/files/6641587/example.zip)
Run:
```bash
(cd lib; ./build.sh)
bazel run //:main
```
> Enables runtime linking for darwin platforms

- docs/defs.md
- docs/flatten.md
- rust/private/rust.bzl
`assert_eq!` can't be called on the result of `fn greet()` as written. Fixes #777.
> Correct test example code.

- rust/private/rust.bzl
As written, this function produces duplicate test rules if used in macros. This patch aims to make it easy to run integration tests with different `crate_features`, via a macro.
> Make it easier to use rust_test_suite in macros.

- crate_universe/README.md
It took me quite a while to figure out how to use it based on the
existing examples, as some files and functions had been renamed, and
I overlooked the call to pinned_rust_install().
> update crate_universe docs

- rust/private/rustc.bzl
Nothing major, small cleanup here since I have plans to make changes in this section of code.
> Added small helper internal function to improve readability

- rust/private/rust.bzl
- rust/private/utils.bzl
The functionality here would be useful elsewhere so I thought it should go in `utils.bzl` and I thought it'd be clearer to borrow the term [dedent](https://docs.python.org/3/library/textwrap.html#textwrap.dedent) from python.
> Promoted internal `_tidy` function to the utils module as `dedent`

- rust/private/clippy.bzl
I find it easier to identify this file at a glance using `.clippy.ok` since I generally assume something with `_clippy` is a real target.
> Made clippy's output file more look less like a target.

- rust/platform/platform.bzl
- rust/platform/triple_mappings.bzl
This information really ought to be public or at least consumable by other modules in `//rust`. But I think it's fine to expose publicly. There's a similar list in [cargo-raze](https://github.com/google/cargo-raze/blob/ee2effee5b6c95cfcfd5e496677ce61dcd35c472/impl/src/util.rs#L27-L50) which needs to be in sync with this so having it be part of the public API would be a good improvement.
> Exposed supported platform triples lists

- rust/platform/triple_mappings.bzl
Specify extensions for android system.
This is a drive-by fix. We don't currently have any android tests here and I didn't test it manually, but I think it's correct.
(original conversation: https://github.com/bazelbuild/rules_rust/pull/797#discussion_r660884773)
> Add missing android extensions

- cargo/cargo_build_script_runner/bin.rs
I think it's good to call out that arguments are expected to be a file, so suffixing with `_file` feels like the right thing to do. This also allows the code to maintain proper snake case and not conflict with other variables in the same scope.
Additionally, I updated the error formatting a bit.
> Minor cleanup of `cargo_build_script` source code.

- proto/proto.bzl
- rust/private/common.bzl
- rust/private/rust.bzl
The `rust_common.create_crate_info` macro creates a `CrateInfo` provider through a macro which allows for the rules to maintain better backwards compatibility when making changes to `CrateInfo`.
> Added `rust_common.create_crate_info`

- docs/BUILD.bazel
- docs/flatten.md
- docs/rust_repositories.md
- docs/symbols.bzl
- rust/defs.bzl
- rust/private/common.bzl
- rust/private/providers.bzl
- rust/private/repository_utils.bzl
- rust/toolchain.bzl
This reduces the complexity of the toolchain itself making it lighter weight and allows the rest of the code to otherwise treat the rust stdlib artifact as a general filegroup but benefit from from having additional required files used for compilation/linking.
> Added `rust_stdlib_filegroup` rule, a helper for creating toolchains

- .bazelci/presubmit.yml
- bindgen/BUILD.bazel
- bindgen/bindgen.bzl
- bindgen/repositories.bzl
- docs/flatten.md
- docs/rust_bindgen.md
- rust/private/rustc.bzl
Prior to this PR, bindgen is broken on macOS 11.4 because it cannot find the file `/usr/lib/libstdc++.6.dylib` (it's a broken symlink).
As far as I can tell, what this code is trying to do is invoke `clang` with `LD_LIBRARY_PATH` so that it reads the libraries specified in the toolchain. On macOS, this variable name is actually `DYLD_LIBRARY_PATH` so this wasn't really working at all before on macOS -- probably the system libraries were being used instead. I'm not sure if you can detect the OS from inside a rule, so I'm setting both LD_LIBRARY_PATH and DYLD_LIBRARY_PATH because I don't think it hurts anything, but if there's a better way to write it I'm happy to change.
The bindgen toolchain is also kind of weird because it asks for a label to a library like `libstdc++.dylib` but there's …
> Use the libraries included with the clang distribution for bindgen

- docs/flatten.md
- docs/rust_doc.md
- examples/ffi/rust_calling_c/BUILD.bazel
- examples/fibonacci/BUILD.bazel
- examples/hello_lib/BUILD.bazel
- examples/hello_world/BUILD.bazel
- examples/proc_macro/BUILD.bazel
- rust/private/rustdoc.bzl
- rust/private/rustdoc_test.bzl
- test/chained_direct_deps/BUILD.bazel
- tools/runfiles/BUILD.bazel
In an effort to keep our naming conventions consistent, the `crate` attribute was added to the `rustdoc` rules.
Requires:
- https://github.com/bazelbuild/rules_rust/pull/807
- https://github.com/bazelbuild/rules_rust/pull/803
closes https://github.com/bazelbuild/rules_rust/issues/512
> Added `crate` attribute to `rustdoc` rules (deprecated `dep`)

- crate_universe/README.md
- docs/BUILD.bazel
- docs/crate_universe.md
- docs/crate_universe.vm
This is a followup from https://github.com/bazelbuild/rules_rust/pull/778. I think all README's should redirect to the docs to avoid duplicate data. Ideally the docs would *all* come straight from the `*.bzl` files but that would require a refactor in how `rules_rust` generates docs.
> Moved `crate_universe` documentation from README into docs

- docs/BUILD.bazel
- docs/flatten.md
- docs/settings.md
- docs/symbols.bzl
- rust/BUILD.bazel
- rust/rust.bzl
- rust/settings/BUILD.bazel
- rust/settings/incompatible.bzl
This PR adds some elementary infrastructure for incompatible flags.
> Add incompatible flag for splitting rust_library

- test/clippy/BUILD.bazel
- test/unit/clippy/BUILD.bazel
- test/unit/clippy/clippy_test.bzl
This should ensure the extra flags to the clippy action are always set and the marker is always created.
> Added unit tests for `rust_clippy_aspect`

- rust/private/rustc.bzl
- test/unit/native_deps/native_deps_test.bzl
This revives https://github.com/bazelbuild/rules_rust/pull/264 and is aiming to address https://github.com/bazelbuild/rules_rust/issues/78. A lot has changed since the original PR in a good way: currently, I believe we don't need to do anything special about non-direct transitive deps; we just have to iterate over all direct `deps`' `CcInfo`s and collect their `linkopts` since they include merged `CcInfo`s from their transitive deps.
> propagate linkopts from (transitive) native dependencies

- test/unit/crate_name/crate_name_test.bzl
- test/unit/native_deps/native_deps_test.bzl
This updates unit test code to use `tut.actions` consistently as a follow-up to https://github.com/bazelbuild/rules_rust/pull/849#discussion_r675486935.
> cleanup: use `tut.actions` consistently across unit tests

- rust/toolchain.bzl
When a tool is needed to help build the target, the corresponding attribute should specify a transition to an exec configuration. This enables the rules to work in certain cross-compilation environments.
related documentation: https://docs.bazel.build/versions/main/skylark/rules.html#configurations
> ensures rust binary tools are run in an exec configuration

- rust/toolchain.bzl
Creating this PR in response to https://github.com/bazelbuild/rules_rust/pull/855#issuecomment-886484229
> Add `exec` configuration to `rust_toolchain::rustc_lib`

- proto/proto.bzl
- rust/private/clippy.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
This removes the `crate_type` argument in internal implementations, replacing uses with `crate_info.type` where appropriate, as a followup to https://github.com/bazelbuild/rules_rust/pull/858#discussion_r679825635.
> cleanup: replace crate_type argument with crate_info.type

- rust/private/repository_utils.bzl
Previously, the default url template for downloading toolchains
was always present as the first place to download tools from. This
prevents overriding the default location for the tools so that an
internal mirror can be used.
Fixes #867
> Make url overrides for downloading toolchains work.

- cargo/cargo_build_script.bzl
Minor cleanup of `cargo_build_script.bzl`
> Use `//rust:defs.bzl` for `cargo_build_script.bzl`

- WORKSPACE.bazel
- docs/BUILD.bazel
- docs/docs_deps.bzl
- docs/docs_transitive_deps.bzl
- docs/flatten.md
- docs/rules_proto_stub/proto/BUILD.bazel
- docs/rules_proto_stub/proto/defs.bzl
- docs/rust_proto.md
- docs/rust_proto.vm
- docs/symbols.bzl
- examples/examples_repositories.bzl
- proto/patches/BUILD.bazel
- proto/patches/README.md
- proto/patches/com_google_protobuf-v3.10.0-bzl_visibility.patch
- proto/patches/rules_proto-bzl_visibility.patch
- proto/repositories.bzl
- proto/transitive_repositories.bzl
Not all dependencies are currently provided by the `@rules_rust//proto` modules. This PR updates the proto rules to provide these missing dependencies via a new `rules_proto_transitive_repositories` macros.
The setup instructions have been updated accordingly in the generated docs.
This change may contain a breaking change for some users who've only loaded `rules_proto_repositories` and not called `@com_google_protobuf//:protobuf_deps.bzl%protobuf_deps` in their workspace. The fix for this is to simply call `rules_proto_transitive_repositories` as documented in the updated docs.
> Update `//proto` rules to provide all required dependencies.

- .bazelci/presubmit.yml
It's by no means ideal to disable these tests but there's currently no known solution and this is blocking all other PRs to the project. As far as I'm aware, `rust_doc_test` continues to work on some (the previous) windows environments but additional work will need to be done to update this rule to consistently work everywhere.
related to:
- https://github.com/bazelbuild/rules_rust/issues/887
> Temporarily disable `rust_doc_test` targets on windows

- COMPATIBILITY.md
This document proposes a backward compatibility policy for `rules_rust` and tries to find a balance between:
*   being able to add new features and improve the rule implementation through backwards incompatible changes
*   giving reliability guarantees to our existing and new users
As of 2021-07-08 the [Bazel backward compatibility](https://docs.bazel.build/versions/main/backward-compatibility.html) policy can be summarized as:
*   Bazel LTS releases are cut approximately every 9 months and are supported for 3 years. Each LTS release increments the major version number.
*   Bazel rolling releases are cut approximately once a week and can contain breaking changes. There are no guarantees of stability between rolling releases, or between a rolling release and the current LTS. In other …
> Define backwards compatibility policy for `rules_rust`

- docs/flatten.md
- docs/rust_repositories.md
- rust/private/repository_utils.bzl
- rust/repositories.bzl
- test/unit/repository_utils/repository_utils_test.bzl
This allows e.g.
```
rust_repositories(
edition = "2018",
include_rustc_srcs = True,
version = "1.54.0",
rustfmt_version = "nightly",
iso_date = "2021-08-16",
)
```
> Only consider iso_date arg in preparing URL if specific version provided

- examples/sys/basic/Cargo.toml
- examples/sys/basic/raze/BUILD.bazel
- examples/sys/basic/raze/crates.bzl
- examples/sys/basic/raze/remote/BUILD.bzip2-0.3.3.bazel
- examples/sys/basic/raze/remote/BUILD.bzip2-sys-0.1.9+1.0.8.bazel
- examples/sys/complex/Cargo.toml
- examples/sys/complex/raze/BUILD.bazel
- examples/sys/complex/raze/crates.bzl
- examples/sys/complex/raze/remote/BUILD.cc-1.0.69.bazel
- examples/sys/complex/raze/remote/BUILD.foreign-types-0.3.2.bazel
- examples/sys/complex/raze/remote/BUILD.form_urlencoded-1.0.1.bazel
- examples/sys/complex/raze/remote/BUILD.git2-0.13.12.bazel
- examples/sys/complex/raze/remote/BUILD.idna-0.2.3.bazel
- examples/sys/complex/raze/remote/BUILD.jobserver-0.1.23.bazel
- examples/sys/complex/raze/remote/BUILD.libgit2-sys-0.12.21+1.1.0.bazel
- examples/sys/complex/raze/remote/BUILD.libssh2-sys-0.2.21.bazel
- examples/sys/complex/raze/remote/BUILD.libz-sys-1.1.3.bazel
- examples/sys/complex/raze/remote/BUILD.log-0.4.14.bazel
- examples/sys/complex/raze/remote/BUILD.openssl-0.10.32.bazel
- examples/sys/complex/raze/remote/BUILD.openssl-sys-0.9.60.bazel
- examples/sys/complex/raze/remote/BUILD.tinyvec-1.3.1.bazel
- examples/sys/complex/raze/remote/BUILD.unicode-bidi-0.3.5.bazel
- examples/sys/complex/raze/remote/BUILD.unicode-normalization-0.1.19.bazel
- examples/sys/complex/raze/remote/BUILD.url-2.2.2.bazel
- examples/sys/complex/repositories.bzl
- examples/sys/sys_deps.bzl
In order to get the `sys` package buildable on windows, there needs to be a shorter prefix for the repositories being generated here. Windows has that dumb MAX_PATH character limit which results in tools (`cl.exe`) claiming a file does not exist.
> Regenerated cargo-raze outputs for sys examples

- .github/workflows/release_begin.yaml
- cargo/cargo_bootstrap.bzl
- crate_universe/bootstrap.bzl
- crate_universe/defs.bzl
- proto/toolchain.bzl
- rust/private/common.bzl
- rust/private/repository_utils.bzl
- rust/repositories.bzl
- rust/toolchain.bzl
This should help keep the use of these variables consistent everywhere.
> Added `default_edition` and `default_version` to `rust_common`

- docs/rust_analyzer.md
- docs/rust_analyzer.vm
The targets to rust_analyzer need to be visible to the root rust_analyzer. Unfortunately, because rust_analyzer is a singular rule at the source of the repo, any package_gorup based visibility will lead to cycles in the build graph. Thus, the rules must have //visibility:public.
See conversation in #905
> Document visibility requirements

- docs/index.md
Most times when I search for `rules_rust` trying to get to the github page, I get to the docs instead. This link would reduce the amount of scrolling or re-querying I have to do.
> Added link to github repo in docs

- rust/private/rustc.bzl
- test/unit/common.bzl
- test/unit/exports/BUILD.bazel
- test/unit/exports/exports_test.bzl
- test/unit/exports/lib_a/BUILD.bazel
- test/unit/exports/lib_a/src/lib.rs
- test/unit/exports/lib_b/BUILD.bazel
- test/unit/exports/lib_b/src/lib.rs
- test/unit/exports/lib_c/BUILD.bazel
- test/unit/exports/lib_c/src/lib.rs
In an effort to make the the rules more testable, the `--extern` flags, which were previously:
```
['--extern', 'crate=some/path/to/libcrate.rlib']
```
have been updated to: 
```
['--extern=crate=some/path/to/libcrate.rlib']
```
Additionally, a test has been added to test regressions in accessibility to symbols in dependencies and transitive dependencies of a target. [re-exports](https://doc.rust-lang.org/reference/items/use-declarations.html#use-visibility) (ie `pub use ...`) for example.
> Update formatting of `--extern` flags passed to `rustc`

- docs/flatten.md
- docs/rust_proto.md
- proto/proto.bzl
As the rule now seems to be loaded with name `rust_proto_library`, docs should use the up-to-date name when giving usage examples.
> Fix docs to use up-to-date rule name

- wasm_bindgen/repositories.bzl
- wasm_bindgen/wasm_bindgen.bzl
[rules_nodejs](https://github.com/bazelbuild/rules_nodejs) made some updates to the names of some symbols. This PR picks those up so `rules_rust` may also benefit.
> Updated `rules_nodejs` for wasm_bindgen rules

- docs/flatten.md
- docs/rust_wasm_bindgen.md
- wasm_bindgen/wasm_bindgen.bzl
I was recently working through getting a use for this setup and there were some issues which made this difficult for non-frequent Bazel users. This change aims to improve messaging to make this experience better.
> Improved `rust_wasm_bindgen` error messaging

- rust/repositories.bzl
closes https://github.com/bazelbuild/rules_rust/issues/917
> Prevent multiple calls to `rust_repositories` from redefining toolchains

- cargo/cargo_build_script.bzl
I use [cpp crate](https://docs.rs/cpp/0.5.6/cpp/) to integrate Rust and C++ code in my project which depends on `cc` crate.
`cc` relies on [CXX env variable](https://github.com/alexcrichton/cc-rs#c-support) to find `cpp` compiler.
This PR sets this env variable along with `CC`.
> add CXX var to configure cpp compiler

- test/unit/extra_rustc_flags/extra_rustc_flags_test.bzl
unittest.bzl does a configuration transition, and with Bazel 5.0
repository-relative labels will be interpreted not as in the main
repository, but as in the repository of the transition. For us it means
we have to explicitly specify which repository we mean in our test.
> Fix a unit test for Bazel 5.0

- .bazelci/presubmit.yml
This PR adds tasks for running our standard battery using current Bazel
rolling release. These tasks are only informative, they will not stop a
PR from submitting, but it's good to keep an eye on these and fix
quickly so we are prepared to incoming incompatible changes in Bazel.
This PR:
* adds Windows task
* adds Macos task
* adds Ubuntu 20.04 with Clang task
* adds RBE with Ubuntu 16.04 task (although I'm not sure why we still are on 16.04 there :)
* removes Ubuntu 20.04 without aspects task (not necessary)
> Add CI tasks for rolling bazel version

- .bazelci/presubmit.yml
- WORKSPACE.bazel
`rbe_autoconfig` doesn't support Bazel 5.0.0+. Use `rbe_preconfig` instead.
> Use rbe_preconfig for RBE toolchain config

- cargo/cargo_build_script_runner/bin.rs
- test/cargo_build_script/build.rs
Also add the `--sysroot` flag if needed
This is needed for in-tree CXX values because we chdir before execing the build script binary.
Fixes #950
> Absolutify CXX as well as CC 

- util/process_wrapper/utils.cc
This fixes the following warning which I found when building on Linux
```
INFO: From Compiling util/process_wrapper/utils.cc:
external/rules_rust/util/process_wrapper/utils.cc: In function 'bool process_wrapper::ReadStampStatusToArray(const StrType&, std::vector<std::pair<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> > >&)':
external/rules_rust/util/process_wrapper/utils.cc:113:21: warning: comparison of integer expressions of different signedness: 'int' and 'std::vector<std::__cxx11::basic_string<char> >::size_type' {aka 'long unsigned int'} [-Wsign-compare]
113 |   for (int i = 0; i < stamp_block.size(); ++i) {
|                   ~~^~~~~~~~~~~~~~~~~~~~
```
> Fix C++ compilation warning

- bindgen/bindgen.bzl
- docs/flatten.md
- docs/rust_bindgen.md
- examples/bindgen/BUILD.bazel
Fixes https://github.com/bazelbuild/rules_rust/issues/992, but it is worth noting that this behavior has existed for a long time and could result in files that were previously being formatted becoming unformatted if toolchains are not specifying the rustfmt parameter when they do want formatted code. The unformatted code is still perfectly valid, and this behavior change matches [the documentation](https://bazelbuild.github.io/rules_rust/rust_bindgen.html#rust_bindgen_toolchain).
> Allow rust_bindgen rules to disable rustfmt with an attr

- cargo/cargo_build_script_runner/BUILD.bazel
- cargo/cargo_build_script_runner/bin.rs
These variables are documented as being available:
https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts
The latest rusqlite depends on CARGO_CFG_WINDOWS to be defined
in order to link correctly: https://github.com/rusqlite/rusqlite/pull/961
> declare CARGO_CFG_(WINDOWS|UNIX) in build scripts

- rust/private/rustc.bzl
Currently, action_env is not passed through to rustc actions, which means that variables like `DEVELOPER_DIR` needed in some cases on macOS cannot be passed through. This PR passes action_env through to rustc actions.
Similar to existing code at https://github.com/bazelbuild/rules_rust/blob/e2f0fccda912daac686b533ad77c5bc5d2f2ddb7/cargo/cargo_build_script.bzl#L68
> Make action_env work for rustc actions

- rust/private/repository_utils.bzl
- rust/repositories.bzl
Trying to add `rustc_srcs` to toolchains using `--repo_env=RULES_RUST_TOOLCHAIN_INCLUDE_RUSTC_SRCS=true` leads to the assets being downloaded but not wired up to the toolchain. This PR allows the `RULES_RUST_TOOLCHAIN_INCLUDE_RUSTC_SRCS` environment variable to correctly set `rust_toolchain.rustc_srcs`
> Fixed environment not configuring rustc_srcs on toolchains

- rust/private/rustc.bzl
- rust/private/utils.bzl
- test/unit/versioned_libs/BUILD.bazel
- test/unit/versioned_libs/a.rs
- test/unit/versioned_libs/b.c
- test/unit/versioned_libs/versioned_libs_analysis_test.bzl
- test/unit/versioned_libs/versioned_libs_unit_test.bzl
#513 fixed an issue that prevented linking against a versioned library (using a version suffix on linux) but didn’t address a problem with `get_lib_name` that prevents from linking against certain libraries that happen to include the version number **before** the extension, such as `libpython3.8.dylib` on macos.
Before this patch, we would attempt to link `-lpython3` (since it would cut the filename up to the first `.` in the library name) and thus failing whereas after the diff it correctly links against `-lpython3.8`.
Also removed the `_has_dylib_ext` function that seems to be a leftover that was added in #808 but left unused after #820.
> Better handling of versioned library filenames

- tools/runfiles/runfiles.rs
Bazel sets the `$TEST_SRCDIR` environment variable telling tests the "absolute path to the base of the runfiles tree", see [the test encyclopedia](https://docs.bazel.build/versions/main/test-encyclopedia.html#initial-conditions).
That should in general be the more reliable way to determine the runfiles directory (when available), I think, but the current logic also does not always work when running tests internally at Google.
> tools/runfiles: use $TEST_SRCDIR when available

- rust/private/rustc.bzl
Even with #1030 I still seem to experience build errors due to the argument list being too long. This change ensures that arguments are written to a param file should they exceed the maximum length on the current platform.
> Use a param file when invoking rustc since the argument list can become too large

- tools/rust_analyzer/lib.rs
With this we will have a place where we can `sed` our way through differences between Bazel and (Google internal) Blaze.
> Extract SYSROOT_SRC_FILE_RUNFILES_PREFIX constant

- rust/private/rust_analyzer.bzl
- tools/rust_analyzer/BUILD.bazel
- tools/rust_analyzer/aquery.rs
- tools/rust_analyzer/raze/BUILD.bazel
- tools/rust_analyzer/raze/Cargo.raze.lock
- tools/rust_analyzer/raze/Cargo.toml
- tools/rust_analyzer/raze/crates.bzl
- tools/rust_analyzer/raze/remote/BUILD.either-1.6.1.bazel
- tools/rust_analyzer/raze/remote/BUILD.itertools-0.10.1.bazel
- tools/rust_analyzer/rust_project.rs
This PR addresses the issue https://github.com/bazelbuild/rules_rust/issues/1032.
When there were multiple build targets sharing the same source, their crate specs were consolidated into one, and their `display_name` depended on the result of aquery. Since the `display_name` is actually a target name, it caused a mismatch between the `display_name` and the actual crate name referenced by the Rust source, leading to unresolved import errors.
To eliminate the possibility of the name mismatch, this PR changes to set a library's `display_name` when consolidating crate specs. This change resolved the unresolved import errors of Rust Analyzer in [my reproduction repository of the issue](https://github.com/reiyw/rules_rust_1032_repro).
> rust-analyzer: Set a library's `display_name` when consolidating crate specs

- rust/private/rustc.bzl
- test/unit/common.bzl
- test/unit/native_deps/native_deps_test.bzl
Right now we pass `--codegen=linker` flags and all C++ linkopts to rustc even when we know those are not needed, because rustc will not use them. This is true when producing `rlib` and `lib` crate types.
> Do not use linker for compiling rlibs

- util/process_wrapper/system_windows.cc
I noticed that rustc was panicking with an unexpected null handle when running a `rust_clippy` target on Windows (see below for panic).
I remember that we were specifically setting a `--stderr-file` or `--stdout-file` and I looked at how the process wrapper was actually setting these when invoking rustc/clippy-driver. We are altering the `STARTUPINFO` struct to pass specific file handles for whatever stream we are interested in (see https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/ns-processthreadsapi-startupinfoa for docs).
Setting `hStdInput`, `hStdOutput` or `hStdError` requires setting `STARTF_USESTDHANDLES` on the `dwFlag`. However, the docs say that while setting this flag, *all* three streams should be set on the `STARTUPINFO` to a handle or …
> Fix rustc panic on Windows due to how stdout/stderr are set up in the process wrapper

- docs/flatten.md
- docs/rust_repositories.md
- rust/private/rustc.bzl
- rust/toolchain.bzl
- test/unit/cc_info/cc_info_test.bzl
I believe this is the most principled solution to the problem discussed in #870, #951, #955, and #1030.
The problem was that `rust_library`-like rules need to provide `CcInfo`, they need to pass `stdlib_linkflags` to the linker, and they didn't know if there was another `rust_library`-like rule that did it already, so they had to add those flags themselves.
This PR solves the problem by providing a `CcInfo` from the `rust_toolchain`. All `rust_library`-like rules can depend on this provider, and luckily, `user_link_flags` will then be expanded only once.
Closes #951, #955, #1030
If you were using the `rust_toolchain.stdlib_linkflags` field before, please replace it with `rust_toolchain.cc_info.linking_context.linker_inputs.to_list()[0].user_link_flags`.
> Provide CcInfo with stdlib_linkopts from rust_toolchain

- .bazelci/presubmit.yml
So it's easier to add a task that tests an incompatible flag
> Add incompatible_changes package and exempt it from default CI tests

- util/label/label.rs
This PR enhances the label parsing library (label.rs) to allow it to support implicit targets (e.g. `//foo/bar` has an implicit target of `bar`, and is equivalent to `//foo/bar:bar`), and to expose whether the label that was parsed was absolute (e.g. to distinguish `//foo` and `foo`).
I also reworked some of the implementation of `consume_package_name`, to make it a little more idiomatic and easier to follow (IMO).
> Enhance label.rs to support implicit targets and expose absolute-ness.

- docs/flatten.md
- docs/providers.md
- docs/rust_repositories.md
- rust/private/providers.bzl
- rust/toolchain.bzl
- test/unit/toolchain/config.txt
- test/unit/toolchain/toolchain_test.bzl
This adds location expansion of stdlib_linkflags with respect to the
rust_lib attribute. This allows us to, e.g., have a linker flag that
refers to a native dependency target label declared in rust_lib.
> toolchain: support location expansion for stdlib_linkflags

- .bazelci/presubmit.yml
This reverts #1050
Since this commit I learned that one can test incompatible changes through transitions as in #1057. Thus, we don't need a separate directory for easier testing.
> Revert "Add test/incompatible_changes package and exempt it from default CI tests

- cargo/cargo_build_script_runner/lib.rs
Cargo 1.50 added support for `cargo:rustc-link-arg` and `cargo:rust-link-arg-bins` instructions in build script output (`rustc-cdylib-link-arg` has been supported since 1.35 and `cargo:rustc-link-arg-bin` was later added in 1.54).
The build script runner currently prints a warning when `rustc-cdylib-link-arg` is used but entirely ignores the other ones (likely setting them as `BuildScriptOutput::DepEnv` since this is the default branch).
This patch adds support for the `cargo:rustc-link-arg` instruction and prints an warning when `cargo:rust-link-arg-bins` and `cargo:rust-link-arg-bin` are used, just like `rustc-cdylib-link-arg`.
Note that `cargo:rustc-link-arg` is important because `cargo` errors when `cargo:rustc-flags` is used for anything that isn't a `-l` or `-L` flag (nb: this is …
> Support `cargo:rustc-link-arg=FLAG` instruction in build script runner

- cargo/cargo_build_script.bzl
- cargo/cargo_build_script_runner/bin.rs
These are sometimes invoked by -sys crates.
> cargo_build_script: Populate LD and LDFLAGS

- rust/private/rust.bzl
- rust/settings/BUILD.bazel
- rust/toolchain.bzl
- test/unit/disable_custom_test_launcher/BUILD.bazel
- test/unit/disable_custom_test_launcher/disable_custom_test_launcher_test.bzl
- util/launcher/BUILD.bazel
relates to https://github.com/bazelbuild/rules_rust/issues/1069
> Added `incompatible_disable_custom_test_launcher`

- crate_universe/src/renderer.rs
- crate_universe/src/templates/defs.bzl.template
- crate_universe/src/templates/partials/git_repository.template
- crate_universe/src/templates/partials/http_archive.template
This allows individual repositories to be overridden by binding
replacement repositories as long as the same name is used.
The names we give to repositories are not currently part of the API
contract of crate_universe, but this can still be useful.
> Define remote repositories with maybe

- rust/settings/BUILD.bazel
- test/test_env_launcher/BUILD.bazel
- test/test_env_launcher/tests/run.rs
relates to https://github.com/bazelbuild/rules_rust/issues/1069
> Flip `incompatible_disable_custom_test_launcher`

- docs/flatten.md
- docs/rust_doc.md
- rust/private/rustdoc.bzl
- rust/private/rustdoc_test.bzl
This has been documented as deprecated for some time (https://github.com/bazelbuild/rules_rust/pull/799). Cleaning this up to improve the error messaging for users.
> Removed deprecated `dep` attribute from `rustdoc` rules

- rust/platform/triple_mappings.bzl
- rust/repositories.bzl
When building on an Apple Silicon machine, a different target triple
is required to target the simulator:
https://doc.rust-lang.org/rustc/platform-support/aarch64-apple-ios-sim.html
As rules_rust currently ignores abi in triples, listing device
and simulator triples in a rust_repository_set() ends up always using
the first one. Adding this constraint allows a build to be switched
between targeting a device and targeting the simulator.
> add support for targeting iOS simulator on Apple Silicon

- tools/rust_analyzer/aquery.rs
For workspace members, a crate_spec is generated for both opt and debug configurations, but when a build is executed, proc-macros are built and used only in the opt configuration. This can result in rust-analyzer looking for the proc macro in the fastbuild location when it was only created in the opt location. Rust analyzer will then be unable to find and use the dylib and code generated by the proc-macro will not have annotations.
This PR fixes the issue by preferring the proc_macro_dylib_path with the `-opt-exec-` path component when merging CrateSpecs.
> Fix proc_macro_dylib_path when they are built in both opt and debug

- docs/flatten.md
- docs/rust_repositories.md
- rust/toolchain.bzl
This will very slightly increase build times but applies basic
optimizations that will do things like make iterators _much_
faster. Since fastbuild is how people iterate most of the time, this
seems like a sensible default value.
> optimization: switch fastbuild opt default to 1 from 0

- cargo/cargo_build_script.bzl
This variable is set for the default profiles as described in https://doc.rust-lang.org/cargo/reference/profiles.html -- true for dev and false for release.
This is an environment variable cargo sets for build scripts documented here https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts
> Add DEBUG env var for running build scripts

- rust/private/rust.bzl
This is to be consistent with C++ rules: https://cs.opensource.google/bazel/bazel/+/master:src/main/java/com/google/devtools/build/lib/rules/cpp/CppRuleClasses.java;l=478?q=ccincludescanning.
> Replace host with exec configurations for grep_includes

- rust/platform/triple_mappings.bzl
Hello. Thanks maintainers. 
I made a demo that runs on an ARM Cortex M3 inside QEMU. I needed to add a few lines to `rules_rust` to correctly download the Cortex M3 (`thumbv7m-none-eabi`) rustlib.
Demo:
https://github.com/driftregion/bazel-c-rust-x86_linux-armv7_baremetal/blob/master/WORKSPACE#L32 
Related:
https://github.com/bazelbuild/rules_rust/issues/256
> add ARM Cortex M3 triple mappings

- test/build_env/tests/manifest_dir.rs
- test/unit/compile_data/compile_data.rs
These tests would fail on windows if you checked out the repo on a windows machine that used native line endings (`CRLF`, [see git documentation](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)).
> Fixed tests which relied on the git checkout's newline endings

- .bazelci/presubmit.yml
- examples/ffi/rust_calling_c/BUILD.bazel
Since moving to Bazel 4.0 as the min target, we can now use `target_compatible_with` to filter incompatible targets. This allows the target definitions themselves to describe what they currently support and makes it easier for contributors to test changes as they don't need to worry about targets that are known to not work for the platform failing.
The MacOS side of this can likely be removed in https://github.com/bazelbuild/rules_rust/pull/921 but since that's been there for some time, I think it's fine to add the flag here.
> Replaced CI flags with compatibility flags for incompatible targets

- WORKSPACE.bazel
- docs/BUILD.bazel
- docs/WORKSPACE.bazel
- docs/flatten.md
- docs/index.md
- docs/rust_repositories.md
- examples/WORKSPACE.bazel
- rust/repositories.bzl
This allows users to have more control over what repositories are created when setting up `rules_rust` in their workspace and conforms to the [bazel-contrib](https://github.com/bazel-contrib/rules-template/blob/f26177bcbdd9eeab373f23ca568c98704efddd3f/mylang/repositories.bzl) guide for Bazel rules.
> Added `rules_rust_dependencies` and `rust_register_toolchains` macros

- rust/private/rustc.bzl
- rust/private/utils.bzl
> fix is_exec_configuration() check

- BUILD.bazel
- docs/defs.md
- docs/flatten.md
- rust/defs.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- test/extra_exec_rustc_flags/BUILD.bazel
- test/extra_exec_rustc_flags/defs.bzl
- test/extra_exec_rustc_flags/lib.rs
- test/extra_exec_rustc_flags/lib_no_exec.rs
This is analogous to https://github.com/bazelbuild/rules_rust/commit/52e3ba4c99692b5354faff0fb1aa62ddf884024c but for the exec configuration. This is useful, e.g., when working in an environment similar to [the stage0 bootstrapping one](https://rustc-dev-guide.rust-lang.org/building/bootstrapping.html#complications-of-bootstrapping), where the beta (stable) toolchain is used to compile unstable sources with an additional `--cfg=bootstrap` flag to be passed everywhere in the exec configuration.
One tricky thing was testing: I didn't find a good way to emulate the testing for `extra_rustc_flags` from the above commit: checking that flags get applied in exec configuration requires digging through the actions of transitive dependencies of the target under test, and I didn't find a way to get …
> add extra_exec_rustc_flags build config

- cargo/cargo_build_script.bzl
- rust/private/rustc.bzl
- rust/private/toolchain_utils.bzl
- rust/toolchain.bzl
This should simplify the API of `rust_toolchain` and help avoid confusion for users defining their own toolchains and rules.
> Replace Targets and lists of files in `rust_toolchain` with depsets

- rust/private/rustc.bzl
- rust/private/rustdoc_test.bzl
- rust/private/toolchain_utils.bzl
- rust/toolchain.bzl
This change updates the `rust_toolchain` to calculate some paths instead of having each `Rustc` action do it.
> Calculate path values in the rust_toolchain construction

- examples/crate_universe/WORKSPACE.bazel
Relates to https://github.com/bazelbuild/rules_rust/issues/1120 and was the cause of a failure in https://buildkite.com/bazel/rules-rust-rustlang/builds/5283#7ad6df85-3e3e-4d17-b6dc-d9e806f04f9e
> Fix Windows long path issue in examples

- rust/toolchain.bzl
We use the equivalent toolchain._cc_toolchain attribute instead
> Remove toolchain._crosstool attribute

- rust/private/rustdoc.bzl
- rust/private/rustdoc_test.bzl
This change was split from https://github.com/bazelbuild/rules_rust/pull/1119#discussion_r800647996
> Fix `rust_doc_test` using execpath paths instead of rootpath

- .bazelci/presubmit.yml
https://github.com/bazelbuild/buildtools/issues/1044 tracks what I feel is more of a bug in the new [unused-variable](https://github.com/bazelbuild/buildtools/blob/5.0.0/WARNINGS.md#unused-variable) defect. I would like to avoid stamping things with `@unused` and creating cases where dead code can be forgotten about (see the issue for more details).
> pin buildifier

- tools/rustdoc/rustdoc_test_writer.rs
Minor cleanup but now the test runners are generated in a consistent way.
> Sort env vars when writing rust_doc_test runners for consistent outputs

- cargo/cargo_bootstrap.bzl
- cargo/private/cargo_utils.bzl
- crate_universe/defs.bzl
- crate_universe/private/util.bzl
- proto/proto.bzl
- rust/platform/triple_mappings.bzl
- rust/private/clippy.bzl
- rust/private/dummy_cc_toolchain/dummy_cc_toolchain.bzl
- rust/private/rust.bzl
- rust/private/rust_analyzer.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc.bzl
- rust/private/transitions.bzl
- rust/private/utils.bzl
- rust/toolchain.bzl
- test/extra_exec_rustc_flags/defs.bzl
- test/unit/force_all_deps_direct/force_all_deps_direct_test.bzl
- test/unit/location_expansion/location_expansion_test.bzl
- test/unit/native_deps/native_deps_test.bzl
- test/unit/use_libtest_harness/use_libtest_harness_test.bzl
Some things I think should be merged from running `buildivier 5.0.0`
> Addressed some new buildifier defects

- rust/toolchain.bzl
I find it easier to manage larger lists if they're sorted.
> Minor cleanup of `rust_toolchain`

- cargo/private/cargo_utils.bzl
There should be no change in behavior
> Minor cleanup of internal function

- proto/proto.bzl
This is related to #1008 and #1013, and fixes the `rust_proto_lib` rule type to also participate in first-party-crate-renaming, if renaming is enabled.
> Add renaming support to `rust_proto_library` targets.

- rust/private/utils.bzl
These comments are related to the migration described in #966. This issue is closed, so it looks like the migration is finished - so these comments are out of date.
> Clean up outdated comments in `transform_deps`.

- rust/private/rustc.bzl
- test/unit/native_deps/native_deps_test.bzl
This reverts rules_rust to use `-Lnative/-lstatic` instead of library paths per https://github.com/bazelbuild/rules_rust/issues/840#issuecomment-1044377538.
Note for submission: I'd like we hold this off until the related https://github.com/bazelbuild/rules_rust/pull/1148 is ready to be submitted so we can submit these closely together to ensure the examples added there do not regress over a large commit history window.
> logically revert https://github.com/bazelbuild/rules_rust/pull/841

- examples/ambiguous_deps/BUILD.bazel
- examples/ambiguous_deps/bin.rs
- examples/ambiguous_deps/cc_library_with_func.cc
- examples/ambiguous_deps/nonstandard_name_bin.rs
- examples/ambiguous_deps/x/BUILD.bazel
- examples/ambiguous_deps/x/exc.cc
- examples/ambiguous_deps/y/BUILD.bazel
- examples/ambiguous_deps/y/exc.cc
- rust/private/clippy.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc.bzl
- rust/private/utils.bzl
- test/unit/native_deps/native_deps_test.bzl
Depends on https://github.com/bazelbuild/rules_rust/pull/1147.
This addresses https://github.com/bazelbuild/rules_rust/issues/840 by creating symlinks to ambiguous native dependencies of a rust_binary that would otherwise cause the link to fail, as in the `example/`s added.
> create symlinks to ambiguous native dependencies

- rust/private/rust.bzl
- rust/private/transitions.bzl
- rust/private/utils.bzl
- rust/settings/BUILD.bazel
- util/import/BUILD.bazel
- util/import/fake_import_macro_impl.sh
This is related to #1008 and #1013. This PR aims to improve the UX of the import macro by not requiring every target to explicitly depend on the macro.
This PR adds an implicit attribute to every `rust_library` and `rust_binary` rule, which (if the `use_real_import_macro` flag is enabled) adds the `import` macro crate to the target's `proc_macro_deps`. If the `use_real_import_macro` flag is disabled (which is the default), the implicit attribute points to a no-op shell script, and nothing is added to the target's dependencies.
> Add a conditional implicit dependency on the import macro.

- .bazelci/presubmit.yml
- rust/private/rustc.bzl
- test/unit/native_deps/bar.cc
- test/unit/native_deps/native_action_inputs_test.bzl
This reverts commit 98bbf8d880d04bf00a602568b8ce812aaf68ed2e.
We're seeing some regressions with interactions between proc-macro and shared-libraries, chatted with @hlopko directly.
I left test/unit/native_deps/native_action_inputs_test.bzl as-is, as all the changes look like improvements and there are many conflicts otherwise.
> Revert "Add CI run with -c opt (#1144)"

- cargo/cargo_bootstrap.bzl
This should help users access the bootstrapped binary in a consistent way.
> Add alias for `cargo_bootstrap_repository` binaries

- .bazelrc
- .gitignore
- examples/.bazelrc
- examples/crate_universe/.bazelrc
This allows for easier local development and follows Bazel's recommended practices:
https://bazel.build/docs/best-practices#bazelrc-file
> If you want to support per-user options for your project that you do not want to check into source control, include the line:
> ```
> try-import %workspace%/user.bazelrc
> ```
> (or any other file name) in your workspace/.bazelrc and add user.bazelrc to your .gitignore.
> Add `user.bazelrc` support to each workspace.

- rust/private/repository_utils.bzl
All the code above this call treats rustfmt as optional, but then when
we make the BUILD for the rust toolchain, we unconditionally point at
the presumed rustfmt label.
At
https://github.com/bazelbuild/rules_rust/blob/59fab4e79f62bfa13551ac851a40696c24c0c3a4/rust/toolchain.bzl#L331-L335
we conditionally create a symlink based on whether the attribute is set,
but because we unconditionally set the attribute, this causes a hard
error failing to symlink to a non-existent file.
Instead, treat rustfmt as optional in this function too, so that the
code above and below properly convey the optionality to each other.
> Treat rustfmt as optional

- cargo/cargo_build_script.bzl
- cargo/cargo_build_script_runner/bin.rs
- docs/cargo.md
- docs/flatten.md
- test/cargo_build_script/BUILD.bazel
- test/cargo_build_script/build.rs
https://github.com/rust-lang/cargo/issues/9600 lead to the introduction of `CARGO_ENCODED_RUSTFLAGS` which was introduced to allow build scripts to access rust flags. This PR add this flag and sets `--sysroot` so crates like `autocfg` (which makes use of this flag [here](https://github.com/cuviper/autocfg/blob/1.1.0/src/lib.rs#L420-L426)) is correctly able to make use of the generated `rust_toolchain`. This avoids issues like the following for users who create toolchains from separate `rustc` and `rust_std` artifacts.
```
Use --sandbox_debug to see verbose messages from the sandbox
error[E0107]: this struct takes 3 generic arguments but 2 generic arguments were supplied
--> external/cargo_aliases__clap-3.0.0-beta.2/src/parse/matches/arg_matches.rs:77:22
|
77 |     pub(crate) args: …
```
> Allow `cargo_build_script` to forward rustc args to build scripts

- crate_universe/private/crates_vendor.bzl
- crate_universe/private/splicing_utils.bzl
- examples/crate_universe/extra_workspace_members/Cargo.Bazel.lock
- examples/crate_universe/multi_package/Cargo.Bazel.lock
- examples/crate_universe/no_cargo_manifests/Cargo.Bazel.lock
[cargo_toml::DependencyDetail](https://gitlab.com/crates.rs/cargo_toml/-/blob/v0.11.3/src/cargo_toml.rs#L504) currently looks for kebab-case variables to deserialize since that's the expectation from Cargo manifests. This change fixes splicing manifests to correctly contain `kebab-case` key values for crate specs.
This addresses part of https://github.com/bazelbuild/rules_rust/issues/1168
> Fixed `crate.spec` being ignored in `crate_universe` rules.

- docs/flatten.md
- docs/rust_repositories.md
- rust/toolchain.bzl
This was an oversight from https://github.com/bazelbuild/rules_rust/pull/1119. The `rust_toolchain.llvm_tools` attribute should actually be a `label` attribute to be consistent with other attributes like `rust_std` and `rustc_lib`.
> Make `rust_toolchain.llvm_tools` consistent with `rust_std`

- util/import/BUILD.bazel
Fixes https://github.com/bazelbuild/rules_rust/issues/1166.
> Cut loading time deps of the import macro

- rust/private/transitions.bzl
- util/process_wrapper/process_wrapper_fake.cc
This fixes a couple of issues we notice shortly after merging #1159
> Remove unused file and use the rules_rust transition allowlist.

- rust/platform/triple.bzl
- rust/platform/triple_mappings.bzl
- rust/repositories.bzl
In addition to host target, "wasm32-unknown-unknown" and "wasm32-wasi" targets are being installed, which includes downloading corresponding rust-std libraries. This CL allow specifying custom additional target triples by introducing a new parameter to rust_register_toolchains(), which defaults to ["wasm32-unknown-unknown" and "wasm32-wasi"] for compatibility. As an example, it is now possible to compile for Android if ["armv7-linux-androideabi"] is specified as an extra_target_triples.
Specifically for Android, most of the required infrastructure was already in place. For example, @rules_rust//rust/platform:triple_mappings.bzl already has all the necessary information to compile Android libraries (e.g. _SYSTEM_TO_STDLIB_LINKFLAGS). However, "armv7-linux-androideabi" is not a 'proper' …
> Allow specifying additional target triples in rust_register_toolchains() and fix androideabi system

- cargo/cargo_build_script.bzl
- test/cargo_build_script/build.rs
Downstream tools (in particular cc-rs) depend on them being set.
The particular use case that I noticed was broken was the macos deployment target (specified via the --macos_minimun_os Bazel option) wasn't being applied on binaries being built via cc-rs in a build.rs script. This was causing all sort of bugs such as symbols not being weakly linked since it was using the SDK version (the default) for the deployment target and bazel-built Rust binaries wouldn't load on older OS versions due to failures to resolve symbols at runtime, even though the deployment target was correctly set in Bazel.
> Populate CFLAGS and CXXFLAGS when invoking cargo build script.

- examples/shared_libs/BUILD.bazel
- examples/shared_libs/cc_library_with_func.cc
- examples/shared_libs/rust_shared_lib_with_static_dep.rs
- rust/private/utils.bzl
We were missing the static_library case while building under pic, as
demonstrated by the added example that was previously failing with an
error after get_preferred_artifact returned None.
> add static_library to get_preferred_artifact with pic

- version.bzl
Based on some of the rationale in https://github.com/bazelbuild/rules_rust/issues/415, this PR updates the version of `rules_rust` to a `0.X` version so the rules can begin to adopt proper semantic versioning with the end goal of eventually getting to a `1.0`.
> Updating `rules_rust` version to `0.1.0`.

- .github/workflows/release.yaml
We can see in the screenshot below that the `rules_rust.tar.gz` artifact is available as an action artifact.
> cache the release archive in release actions

- WORKSPACE.bazel
- crate_universe/3rdparty/BUILD.bazel
- crate_universe/crates.bzl
- crate_universe/crates_deps.bzl
- crate_universe/defs.bzl
- crate_universe/repositories.bzl
- crate_universe/tools/cross_installer/BUILD.bazel
- docs/WORKSPACE.bazel
- docs/crate_universe.md
- examples/crate_universe/WORKSPACE.bazel
This makes setup more consistent with `rules_rust` itself.
> Restrucutred `crate_universe` dependency macros

- cargo/cargo_build_script.bzl
Some build scripts use this. It is documented at
https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts
Fixes #1215
> Add NUM_JOBS env var to cargo build scripts

- rust/private/rust.bzl
- util/process_wrapper/BUILD.bazel
Stamping is not supported when building without process_wrapper:
https://github.com/bazelbuild/rules_rust/blob/8df4517d370b0c543a01ba38b63e1d5a4104b035/rust/private/rustc.bzl#L955
> fix `stamp = 0` in rust_binary_without_process_wrapper

- crate_universe/BUILD.bazel
- crate_universe/src/context/crate_context.rs
- crate_universe/src/splicing/splicer.rs
It seems https://github.com/rust-lang/rust-clippy/issues/8470 is no longer an issue in Bazel CI. My understanding is that this only impacts hosts with a particular `libstdc++` install. More details are in that issue.
> Fixed `crate_universe` clippy defects

- test/unit/linkstamps/linkstamps_test.bzl
- test/unit/native_deps/native_deps_test.bzl
Some tests assume that they are running in the rules_rust workspace.
Removing these assumptions allow us to run these tests from other bazel
workspaces.
For example, I help maintain https://github.com/grailbio/bazel-toolchain
and we check if cc toolchain that we configure is compatible with
rules_rust by running the unit tests in this repo.
> Fix some unit tests to run from another workspace

- crate_universe/BUILD.bazel
It seems that https://github.com/bazelbuild/rules_rust/pull/1206 fixed the error seen in https://github.com/bazelbuild/rules_rust/issues/980. This change enables the `rust_doc_test` target for `crate_universe`.
> Enabled `rust_doc_test` for `crate_universe`

- tools/BUILD.bazel
This is a reimplementation of https://github.com/bazelbuild/rules_rust/pull/1229 (credit goes to @roman-kashitsyn, thank you!) that I'd like to get merged so I can begin preparing a new release.
closes https://github.com/bazelbuild/rules_rust/pull/1229
> fix: distribute `//tools/rust_analyzer`

- crate_universe/private/splicing_utils.bzl
- crate_universe/src/cli/splice.rs
- crate_universe/src/splicing/splicer.rs
- examples/crate_universe/WORKSPACE.bazel
- examples/crate_universe/cargo_workspace/.cargo/config.toml
- examples/crate_universe/cargo_workspace/BUILD.bazel
- examples/crate_universe/cargo_workspace/Cargo.Bazel.lock
Uses of [`crates_repository::cargo_config = "//:.cargo/config.toml"`](https://github.com/bazelbuild/rules_rust/blob/0.1.0/crate_universe/private/crates_repository.bzl#L121-L123) would unfortunately cause that file to be deleted. This PR fixes that.
> Fixed `crates_repository` deleting `.cargo/config.toml` files.

- docs/index.md
Special thanks to @jfirebaugh! 
closes https://github.com/bazelbuild/rules_rust/pull/1225
closes https://github.com/bazelbuild/rules_rust/issues/1224
> Replace `rust_repositories` with `rust_register_toolchains` in docs

- docs/index.md
I don't think we need to update the pin for every release but `0.1.0` had some things missing from the release artifact so I think it'd be good to move to `0.2.0` where this is fixed.
> Updated repository pin in the docs

- proto/BUILD.bazel
- proto/raze/patch/BUILD.bazel
This error was observed using the release package:
```
INFO: Repository rules_rust_proto__protobuf__2_8_2 instantiated at:
/var/lib/buildkite-agent/builds/buildkite-linux-x86-64-1-6/metawork/metawork/WORKSPACE:87:24: in <toplevel>
/var/lib/buildkite-agent/.cache/bazel/buildkite-linux-x86-64-1-6/external/rules_rust/proto/repositories.bzl:55:41: in rust_proto_repositories
/var/lib/buildkite-agent/.cache/bazel/buildkite-linux-x86-64-1-6/external/rules_rust/proto/raze/crates.bzl:374:10: in rules_rust_proto_fetch_remote_crates
/var/lib/buildkite-agent/.cache/bazel/buildkite-linux-x86-64-1-6/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_archive defined at:
/var/lib/buildkite-agent/.cache/bazel/buildkite-linux-x86-64-1-6/external/bazel_tools/tools/buil …
```
> Fixed proto package in release artifact

- rust/private/rust.bzl
I noticed this while setting up rust_test_suite auto-generation at
work. Seems like a simple enough fix.
> rust_test_suite: ensure crate names are valid

- cargo/cargo_build_script_runner/BUILD.bazel
- util/process_wrapper/BUILD.bazel
These otherwise get built with the downstream repo's default edition, which is not necessarily correct.
Related to #1251.
> Set edition for process_wrapper and cargo_build_script_runner

- rust/platform/triple_mappings.bzl
When building for the armv7 android target, we would ideally specify a
cpu:armv7 constraint, but because of the linked bazel issue this is
currently hardcoded as arm in bazel's NDK setup. As far as I can tell
the platform we request for use with rules rust has to match the
constraints in bazel, otherwise it won't discover the NDK CC toolchain
for linking.
> Add workaround for arm vs armv7 android issue

- crate_universe/private/crate.bzl
- crate_universe/src/context/crate_context.rs
- docs/crate_universe.md
Propagate the build_script_tools attribute from the crate annotations to
the generated cargo_build_script rule.
> crate_universe: propagate build_script_tools

- rust/private/rust.bzl
- rust/repositories.bzl
- test/process_wrapper/BUILD.bazel
- test/process_wrapper/fake_rustc.rs
- test/process_wrapper/rustc_quit_on_rmeta.rs
- util/process_wrapper/BUILD.bazel
- util/process_wrapper/BUILD.tinyjson.bazel
- util/process_wrapper/main.rs
- util/process_wrapper/options.rs
- util/process_wrapper/output.rs
- util/process_wrapper/rustc.rs
This is a key component of supporting pipelining in rules_rust. The
bazel rules will (in a follow-up PR) configure rustc to run either to
completion for rules whose dependencies require the full rlib files or
until they emit the rmeta files if dependencies only require that.
This is safe to commit as there are no changes to user-visible behavior
until the new flags are used.
> process_wrapper: add support for terminating rustc after it emits rmeta.

- crate_universe/private/generate_utils.bzl
Fixes https://github.com/bazelbuild/rules_rust/issues/1277
> Don't leak additive build file content across crates

- docs/defs.md
- docs/flatten.md
- rust/private/rust.bzl
The example talks about `:hello_lib_test` which doesn't exist; the right name is `:greeting_test`.
> Fix target name in `rust_test` example.

- crate_universe/tools/BUILD.bazel
- crate_universe/tools/cross_installer/BUILD.bazel
- crate_universe/tools/urls_generator/BUILD.bazel
- util/BUILD.bazel
- util/import/BUILD.bazel
- util/import/fake_import_macro_impl.cc
- util/import/fake_import_macro_impl.sh
- util/process_wrapper/BUILD.bazel
Addresses https://github.com/bazelbuild/rules_rust/issues/1272#issuecomment-1109366990
> Fixed build issues in release artifact

- cargo/cargo_bootstrap.bzl
- cargo/private/cargo_utils.bzl
- crate_universe/private/crates_repository.bzl
- rust/platform/triple.bzl
If I have:
```python
triple = get_host_triple(repository_ctx)
f(triple.triple)
```
then `triple.triple` does not do a good job conveying what is going on; how the two things called `triple` (actually 3 if you count the function named `triple` as well) are different from one another.
To improve this in #1289 I added a `str` field to the triple struct, just duplicating the contents of the `triple` field but with a clearer name. In contrast to `triple.triple`, writing `f(triple.str)` is clearer to me and conveys "oh yeah `f` takes a string argument (as opposed to a struct) and `triple.str` is the string representation of the triple".
This PR removes the field `triple.triple` in favor of `triple.str` since there is no longer a reason to use the former.
> Remove `triple` field from triple struct in favor of `str`

- rust/private/rust_analyzer.bzl
> Use __EXEC_ROOT__ paths for genfiles in rust_analyzer aspect

- rust/private/rustc.bzl
`("bar" or "baz")` always evaluates to "bar", so this conditional ignores `"dylib"`. This seems unintended.
I don't have a particular test-case in mind for this; just noticed the oddity as I was browsing through the code.
cc @krasimirgg, who seems to have tweaked things around here recentlyish?
> rustc: fix a conditional

- rust/private/repository_utils.bzl
The commit https://github.com/bazelbuild/rules_rust/commit/841fc6fb82141576d91aecb1d3f2656d58b0ab71 for https://github.com/bazelbuild/rules_rust/pull/1284 broke the ability to use rust_register_toolchains with a nightly channel, see https://github.com/bazelbuild/rules_rust/commit/841fc6fb82141576d91aecb1d3f2656d58b0ab71#commitcomment-72310891.
I tracked the issue down to this line which was updated there. While using a dated nightly, these variables look like:
* tool_path:  `rust-nightly-x86_64-unknown-linux-gnu`
* tool_suburl:  `2022-04-06/rust-nightly-x86_64-unknown-linux-gnu`
Using tool_suburl causes the extract to fail like in the comment above:
`Prefix "2022-04-06/rust-nightly-x86_64-unknown-linux-gnu/rustc" was given, but not found in the archive. Here are possible prefixes for this …
> fix for using a nightly channel after commit 841fc6fb82141576d91aecb1d3f2656d58b0ab71

- rust/private/repository_utils.bzl
This var was removed in a previous commit in order to unify the
handling of the fetching of all assets.
> Remove doc about STATIC_RUST_URL env var.

- rust/repositories.bzl
We should be pulling in deps from crates.io as much as possible
since the downloads will usually be smaller, and we can avoid
a proliferation of remote locations for resources.
Fixes #1273
> Use tinyjson from crates.io instead of github.com.

- examples/WORKSPACE.bazel
- test/deps.bzl
This silences the following warnings (which are out of our control):
```
INFO: From Compiling Rust rlib libc (59 files):
warning: unnecessary trailing semicolon
--> external/libc/src/macros.rs:58:21
|
58 |             $($body);*
|                     ^ help: remove this semicolon
|
= note: `#[warn(redundant_semicolons)]` on by default
warning: unnecessary parentheses around assigned value
--> external/libc/src/unix/bsd/apple/mod.rs:345:38
|
345 | pub const LC_COLLATE_MASK: ::c_int = (1 << 0);
|                                      ^      ^
|
= note: `#[warn(unused_parens)]` on by default
help: remove these parentheses
|
345 - pub const LC_COLLATE_MASK: ::c_int = (1 << 0);
345 + pub const LC_COLLATE_MASK: ::c_int = 1 << 0;
|
warning: unnecessary parentheses around assigned value
--> …
```
> Address warnings for example/test dependencies

- docs/BUILD.bazel
- docs/WORKSPACE.bazel
- docs/flatten.md
- docs/rust_wasm_bindgen.md
- docs/symbols.bzl
- examples/WORKSPACE.bazel
- wasm_bindgen/repositories.bzl
This conforms to the changes made in https://github.com/bazelbuild/rules_rust/pull/1105
Note that the previous API of `rust_wasm_bindgen_repositories` is still supported but users should migrate off of this
> Updated wasm_bindgen dependencies API

- crate_universe/src/rendering/templates/module_bzl.j2
Previously, we would silently return `[]`. This is incorrect; a user
should not be attempting to get deps which weren't declared, and
silently doing so can lead to some frustrating debugging.
Fixes #1322.
> Error calling `all_crate_deps` without `Cargo.toml`

- rust/private/rustc.bzl
- test/unit/native_deps/native_deps_test.bzl
This is part of the work on https://github.com/bazelbuild/rules_rust/issues/1268.
Consider a case where we have a rust binary B that depends on a rust library R that depends on a native library N. With a recent nightly rustc that passes the native library via `-l` to the linker (not using `--whole-archive` as it used to) and a linker that checks for backward references, we can run into backward reference errors when N appears before R on the linker invocation. Example at https://github.com/rust-lang/rust/issues/81490#issuecomment-1116042481.
We came up with two approaches to deal with such cases: a "sandwich" one and one where we'd pass appropriate `-l` flags to rustc when building rust_libraries. This PR implements the "sandwich" one.
Under the "sandwich" approach, we modify the rustc …
> "sandwich" rlibs between native deps in linker order

- rust/private/rust.bzl
- rust/private/utils.bzl
- test/unit/crate_name/crate_name_test.bzl
Reverts bazelbuild/rules_rust#1334
This commit inadvertently changed the location (directory) of the output created by rustc. Before this change, a rust_binary target named `bin/foo` would create an executable named `foo` in a new subdirectory named `bin`. After this change, the same rust_binary target would create an executable named `bin_foo` in the normal blaze output directory.
The previous behavior is consistent with other bazel rule behavior (e.g. cc_binary), so rules_rust should keep that behavior. I'd like to roll this back, and create a new PR to handle slashes in a better way.
> Revert "Replace slashes with underscores in default crate names."

- rust/private/rustc.bzl
- rust/private/utils.bzl
- test/unit/crate_name/crate_name_test.bzl
This is another attempt at #1334, which sought to make "/" characters legal in Rust target names.
This PR differs from #1334 in how it handles build artifacts that are based on `crate_info.output`. There are a few places that currently assume that calling `ctx.actions.declare_file(...)` will always declare a file in the same directory as `crate_info.output`, i.e. as `ctx.actions.declare_file(ctx.label.name + ...)`. In a world where label names may include slashes (which is the case today!), this is not a safe assumption, since a slash in the target name causes bazel to create a subdirectory for the output.
Specifically, this PR fixes incorrect locations for the following items (when the target name includes a slash):
* PDB files
* dSYM files
* .lib files
This leaves a few things that look …
> Replace slashes with underscores in default crate names.

- rust/private/rust.bzl
This usage of `crate_name` is not needed, and should be removed, so that the underlying `rust_test` targets participate in the same naming scheme as is used by normal invocations of `rust_test`.
Proof that `crate_name` is not needed here:
First, note that `name_to_crate_name` just replaces "/" and "-" characters in the provided string with underscores. So, we can immediately replace `name_to_crate_name(test_name.replace("/", "_"))` with just `name_to_crate_name(test_name)`. Next, we trace through the call to `rust_test`: since this target does not use the `crate` attribute, it will go through the call to `compute_crate_name(...)` on line 381. Assuming we have removed the `crate_name` attribute, that function will skip the first if statement on utils.bzl:303, and compute the crate name as …
> Remove unnecessary `crate_name` usage in `rust_test_suite`.

- .bazelci/presubmit.yml
To unblock PRs, this disables a job that started failing seemingly out of nowhere (not related to changes in the repo).
> Temporarily disable windows job in CI.

- docs/flatten.md
- docs/rust_repositories.md
- rust/repositories.bzl
It's a really pedantic change, but is more consistent with bazel terminology.
> Use target instead of rule in rust_register_toolchains edition docs

- test/test_env_launcher/tests/run.rs
This appears to be a copy-paste error in #1079, since the assertion is
already is currently duplicated on line 26.
> Fix incorrect assertion in test_env_launcher test

- crate_universe/BUILD.bazel
- crate_universe/test_data/private/BUILD.bazel
- crate_universe/tools/cross_installer/BUILD.bazel
- rust/toolchain/BUILD.bazel
- test/current_toolchain_files/BUILD.bazel
The configuration of the `toolchain_tool` targets is up to however they're consumed. Claiming they're `exec` is misleading.
> Renamed toolchain files targets

- rust/private/toolchain_utils.bzl
- rust/private/utils.bzl
- rust/toolchain.bzl
- rust/toolchain/BUILD.bazel
- test/unit/toolchain_make_variables/BUILD.bazel
- test/unit/toolchain_make_variables/main.rs
- test/unit/toolchain_make_variables/toolchain_make_variables_test.bzl
See https://github.com/bazelbuild/bazel/issues/14009#issuecomment-921960766
> Added TemplateVariableInfo to rust_toolchain

- .clang-format
- examples/ambiguous_deps/cc_library_with_func.cc
- examples/ffi/rust_calling_c/c/matrix.h
- examples/ffi/rust_calling_c/c/matrix_test.c
- examples/shared_libs/cc_library_with_func.cc
- test/linker_inputs_propagation/baz.cc
- test/linker_inputs_propagation/foo_shared.cc
- test/linker_inputs_propagation/foo_shared.h
- test/process_wrapper/process_wrapper_tester.cc
- test/unit/proc_macro/leaks_deps/native/native.cc
- test/unit/win_interface_library/bin.cc
- test/versioned_dylib/c/return_zero.c
- test/versioned_dylib/c/return_zero.h
- util/import/fake_import_macro_impl.cc
Minor cleanup. The following config was used:
```yaml
---
BasedOnStyle: Google
...
```
> Ran clang-format on all C++ sources

- .bazelci/presubmit.yml
This would actually enable us to close out https://github.com/bazelbuild/rules_rust/pull/872
> Enable rustfmt CI for Windows.

- docs/BUILD.bazel
- docs/flatten.md
- docs/rust_analyzer.md
- docs/symbols.bzl
- examples/hello_lib/BUILD.bazel
- rust/defs.bzl
- rust/private/rust_analyzer.bzl
The old `rust_analyzer` rule is no longer necessary. Documentation for it's replacement can be found [here](https://bazelbuild.github.io/rules_rust/rust_analyzer.html).
> Deleted deprecated `rust_analyzer` rule.

- crate_universe/src/context/crate_context.rs
- crate_universe/src/rendering.rs
- crate_universe/src/rendering/templates/partials/crate/build_script.j2
- crate_universe/src/rendering/templates/partials/crate/common_attrs.j2
This solves for issues where users might be using the following [crate annotation](https://bazelbuild.github.io/rules_rust/crate_universe.html#crateannotation)
```starlark
"openssl-sys": [crate.annotation(
rustc_flags = [
"-l",
"dylib=ssl",
"-l",
"dylib=crypto",
],
)],
```
Before this would render to a list that omitted the second `-l` argument and result in an invalid build command.
```starlark
rustc_flags = [
"-l",
"dylib=ssl",
"dylib=crypto",
],
```
This is now fixed and the list renders correctly
```starlark
rustc_flags = [
"-l",
"dylib=ssl",
"-l",
"dylib=crypto",
],
```
> Use a vec, not set for rustc_flags for crate_universe annotations

- docs/flatten.md
- docs/rust_doc.md
- rust/private/rustdoc.bzl
**Context**
When building [rustdocs](https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html) it is very useful to pass `-Dwarnings`. This allows you to easily assert things like [intra-doc-links](https://doc.rust-lang.org/rustdoc/write-documentation/linking-to-items-by-name.html) aren't broken. As far as I can tell, passing flags to `rustdoc` isn't possible today. 
**Solution**
Add the `rustc_flags` attr to the `rust_doc` rule. `rustc_flags` is already parsed in [`construct_arguments(...)`](https://github.com/bazelbuild/rules_rust/blob/main/rust/private/rustc.bzl#L601) which `rust_doc` calls into.
> feat: add `rustc_flags` attr to `rust_doc` rule

- rust/private/rust.bzl
- test/unit/stamp/stamp_test.bzl
https://github.com/bazelbuild/rules_rust/pull/1452 set `rust_*.stamp=0` as a default for all rules except `rust_binary`, which has -1 as a default.
The `rust_binary_without_process_wrapper` rule is used to build the process wrapper itself. It needs to override the `stamp` attribute back to 0, as we do not support stamping without the process wrapper. https://github.com/bazelbuild/rules_rust/pull/1452 introduced a bug where the default value for this rule became `-1`, thus building `//util/process_wrapper` with `--stamp` is now broken.
This PR fixes the issue by routing all the attributes through the [_common_attrs_for_binary_without_process_wrapper](https://source.corp.google.com/piper///depot/google3/third_party/bazel_rules/rules_rust/rust/private/rust.bzl;rcl=461281665;l=1069?q=rust_bina …
> Fix `rust_binary_without_process_wrapper` build with `--stamp` past https://github.com/bazelbuild/rules_rust/pull/1452

- rust/platform/triple_mappings.bzl
Just found a small typo while exploring the insides of `rules_rust`.
> Fix typo in function name

- crate_universe/src/cli/splice.rs
- crate_universe/src/cli/vendor.rs
- crate_universe/src/splicing/splicer.rs
Previously if the workspace root manifest was missing, a panic would be
triggered due to unwrapping a `None` option.
Now, we suggest the missing manifest if possible, or direct you to work
it out yourself if we can't.
> Give useful error on missing workspace manifest

- docs/flatten.md
- docs/providers.md
- rust/private/providers.bzl
- rust/toolchain.bzl
Among the standard rust libs, libtest depends on libstd:
https://github.com/rust-lang/rust/blob/master/library/test/Cargo.toml#L12
The current implementation was adding it to
`between_core_and_std_files`. This may cause backward reference linker
errors in some configurations where the linker is configured to check
for such backward references and the toolchain uses the static version
of libtest.
> toolchain files: ensure test depends on std

- bindgen/BUILD.bazel
- bindgen/bindgen.bzl
- cargo/cargo_build_script.bzl
- crate_universe/private/crates_vendor.bzl
- docs/flatten.md
- docs/rust_bindgen.md
- docs/rust_proto.md
- docs/rust_proto.vm
- docs/rust_wasm_bindgen.md
- proto/BUILD.bazel
- proto/proto.bzl
- rust/BUILD.bazel
- rust/private/clippy.bzl
- rust/private/rust.bzl
- rust/private/rust_analyzer.bzl
- rust/private/rustdoc.bzl
- rust/private/rustdoc_test.bzl
- rust/private/rustfmt.bzl
- rust/private/toolchain_utils.bzl
- rust/private/utils.bzl
- test/unit/consistent_crate_name/with_modified_crate_name.bzl
- test/unit/force_all_deps_direct/generator.bzl
- test/unit/toolchain_make_variables/toolchain_make_variables_test.bzl
- wasm_bindgen/BUILD.bazel
- wasm_bindgen/wasm_bindgen.bzl
Upstream Bazel rules seem to consistently define [toolchain_type](https://docs.bazel.build/versions/main/toolchains.html#writing-rules-that-use-toolchains) names as `toolchain_type` ([rules_cc](https://github.com/bazelbuild/rules_cc/blob/0.0.2/cc/BUILD#L33-L36), [rules_python](https://github.com/bazelbuild/rules_python/blob/0.10.2/python/BUILD)). The changes here move `rules_rust` to be consistent with upstream Bazel.
This will be a breaking change for any users who index toolchains via the string of the label of the toolchain type in their rules.
> Updated all toolchain_type definitions to be named `toolchain_type`.

- rust/private/rustc.bzl
Fuchsia rules assemble shared libraries during packaging, so rpaths are not needed.
> Skip supplying rpaths on Fuchsia

- crate_universe/private/crates_repository.bzl
- docs/crate_universe.md
This fixes a typo in an example of crates_repository rule.
> Fix typo in an example of crates_repository rule

- examples/WORKSPACE.bazel
- examples/crate_universe/WORKSPACE.bazel
migrating to rbe_preconfig and remove bazel_toolchains to eliminate the usage of values from `@bazel_tools//platforms`
https://github.com/bazelbuild/continuous-integration/issues/1404
Fixes: https://github.com/bazelbuild/rules_rust/issues/1523
> migrating to rbe_preconfig and remove bazel_toolchains

- rust/private/rust.bzl
- test/generated_inputs/BUILD.bazel
- test/generated_inputs/lib.rs
- test/generated_inputs/src/generated/submodule.rs
- test/generated_inputs/src/lib.rs
- test/generated_inputs/submodule/mod.rs
When some input files are generated, the source files get symlinked to `bazel-out` so the generated and source files are in the same directory. This was implemented in #1340. However, the directory structure would get flattened since only the basename was used for the symlink location. Now the package-relative path is used.
Fixes #1510.
> Preserve directory structure of source files when some are generated

- rust/platform/triple_mappings.bzl
Newer NDKs no longer have this library, if it's still needed for folks
using older NDKs I think they'll have to manually link it.
> Remove -lgcc from Android builds

- crate_universe/private/splicing_utils.bzl
These labels are only used for error reporting, so it's not necessary for them to be unambiguous.
See https://github.com/bazelbuild/rules_rust/pull/1544 for more background.
Needed to flip https://github.com/bazelbuild/bazel/issues/16196.
> Strip leading '@'s for labels in the splicing manifest

- docs/rust_analyzer.md
- docs/rust_analyzer.vm
The rendered version looks pretty ugly.
> Fix markdown typo in rust_analyzer.md

- rust/private/rustc.bzl
- test/unit/remap_path_prefix/BUILD.bazel
- test/unit/remap_path_prefix/dep.rs
- test/unit/remap_path_prefix/test.rs
This fixes an inconsistency in file paths (included in e.g. panic info), wherein some paths would have a leading `./` and some would not.
I believe specifically generic code that is instantiated across a crate boundary would end up with an absolute path, then have it remapped to `.`, whereas other code would use the literal path passed on the command line to `rustc`, which is generally a relative path with no `./` prefix.
> Remap $PWD to empty string instead of "."

- util/import/import_internal.rs
So that [crubit](https://github.com/google/crubit)'s (upcoming) equivalent `cc_import!` macro can reuse the code.
> Export AbsoluteLabel functionality

- rust/private/rust.bzl
- rust/private/utils.bzl
The honest motivation for this little refactoring is https://github.com/google/crubit. In build rules that don't yet work in the open-source yet we need to patch `rust.bzl` with a custom logic encapsulated in a function (the function collects extra dependencies from aspects). This function is called from `rust.bzl`, and it needs to call `crate_root_src`. To prevent a `load` cycle I'm moving the function to `utils.bzl`. I understand that it would be much better to justify this PR with a working build rules in Crubit, but that's unfortunately not easily achievable yet.
> Move crate_root_src to utils.bzl

- rust/private/rustc.bzl
This is similar to the other output groups. It's helpful for debugging. For example, I used it to build the .rmeta multiple times to chase down the root cause of #1584.
> Add an output group for the .rmeta

- cargo/cargo_build_script_runner/lib.rs
When compiling the latest zstd crate on a German locale in non-release mode on Windows, it outputs localized messages that are not UTF8, causing the compile to fail.
> Ignore non-utf8 text in build script output

- docs/index.md
`depednencies` -> `dependencies`
> Typo correction on doc

- .github/release_notes.template
Given the response in https://github.com/bazelbuild/continuous-integration/issues/1347, it doesn't sound like Googlers are interested in adding release to the Google mirror. If anyone else has a desire for this functionality I'd suggest reaching out to someone at Google and reverting this change.
closes https://github.com/bazelbuild/rules_rust/issues/1502
> Remove Google mirror from Starlark snippet in release notes

- cargo/cargo_build_script.bzl
This is a follow up to https://github.com/bazelbuild/rules_rust/pull/1612. To ensure the git history for `cargo_build_script.bzl` is cleanly migrated, backwards compatibility is handled in this PR.
> Restore support for old `cargo_build_script` load statements

- crate_universe/3rdparty/crates/BUILD.bazel
- crate_universe/3rdparty/crates/BUILD.cfg-expr-0.12.0.bazel
- crate_universe/3rdparty/crates/defs.bzl
- crate_universe/Cargo.lock
- crate_universe/Cargo.toml
Upgrades [cfg-expr](https://crates.io/crates/cfg-expr) to version 0.12.0, which now supports `target_abi` in cfg expressions. Without it, if your project depends on a crate that uses it (one example of such crate is `getrandom`) the `crago-bazel` tool fails parsing generated metadata.json.
> Upgraded cfg-expr dependency to 0.12.0.

- crate_universe/src/splicing/cargo_config.rs
Fixing a couple typos I noticed while going through `cargo-vendor`ing workflows
> [docs] Fixing typos in CargoConfig doc strings

- rust/private/rust_analyzer.bzl
- rust/private/utils.bzl
- rust/toolchain.bzl
There's a bug in bazel where the server crashes if it encounters duplicate entries in expand_location's targets field.
See https://github.com/bazelbuild/bazel/issues/16664.
> Deduplicate expand_location targets in rust-project.json crate creation to avoid a bazel crash

- crate_universe/private/crates_vendor.bzl
When vendoring from a label that is not in a package, the output directory would be incorrectly set to `/vendor_path` and be treated as an absolute path.
> Fix vendoring when not in a package

- docs/BUILD.bazel
- docs/WORKSPACE.bazel
- docs/flatten.md
- docs/rust_repositories.md
- rust/repositories.bzl
- rust/toolchain.bzl
- test/rust_analyzer/rust_analyzer_test_runner.sh
Instead a [rust_analyzer_toolchain](https://github.com/bazelbuild/rules_rust/blob/0.12.0/rust/private/rust_analyzer.bzl#L214-L224) can be used.
> Deprecated `rust_toolchain.rustc_srcs`

- util/label/label.rs
This is apparently valid which I confirmed with an `sh_test` in a `baz/foo+bar` package.
```
rules_rust % bazel test //baz/...
INFO: Analyzed target //baz/foo+bar:test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //baz/foo+bar:test up-to-date:
bazel-bin/baz/foo+bar/test
INFO: Elapsed time: 0.216s, Critical Path: 0.09s
INFO: 3 processes: 1 internal, 2 darwin-sandbox.
INFO: Build completed successfully, 3 total actions
//baz/foo+bar:test                                                       PASSED in 0.1s
Executed 1 out of 1 test: 1 test passes.
INFO: Build completed successfully, 3 total actions
```
> Update `//util/label` to support `+` in packages

- crate_universe/src/rendering.rs
- crate_universe/src/rendering/template_engine.rs
- crate_universe/src/rendering/templates/partials/crate/aliases.j2
- crate_universe/src/rendering/templates/partials/crate/deps.j2
- crate_universe/src/test.rs
- crate_universe/src/utils/starlark/select.rs
Group deps and aliases by platform triple rather than by cfg string when generating BUILD files. This avoid Bazel errors due to duplicate keys/deps. See https://github.com/bazelbuild/rules_rust/issues/1417.
This is done purely at render time by adding a new Tera filter which will remap the conditions in the deps SelectList from "cfg(...)" strings to platform triple strings.
This is my first PR here, so please bear with me if I'm doing things wrong!
> Fix issue #1417 - Group deps by platform triple rather than cfg(...) string.

- crate_universe/src/rendering/templates/partials/crate/common_attrs.j2
Add files with spaces to the exclude list. [Original discussion raised on Slack](https://bazelbuild.slack.com/archives/CSV56UT0F/p1669140022100749?thread_ts=1669139179.947319&cid=CSV56UT0F): 
> Hey! I'm trying to setup my Rust project for the first time following the example from rules_rust/examples/crate_universe but I get the following error. My rust binary compiles and run just fine when running outside Bazel. It seems to be related with one of the deps having a space in its name? How can I address that?
> ```
> INFO: Analyzed target //backend/router:router (1 packages loaded, 5 targets configured).
> INFO: Found 1 target...
> ERROR: /private/var/tmp/_bazel_andre.bazaglia/d99a96be6823e596c135c9df87021555/external/crate_index__v8-0.44.3/BUILD.bazel:98:19: Creating runfiles tree …
```
> fix: add space to crate data exclude list

- crate_universe/src/rendering/template_engine.rs
- crate_universe/src/rendering/templates/partials/crate/build_script.j2
- crate_universe/src/rendering/templates/partials/crate/common_attrs.j2
PR #1665, unfortunately, missed updating the exclude attribute from the glob helper function everywhere it was used. This PR fixes that and also makes it now consistent everywhere it is needed by creating a centralized list.
I created a repro in [bazaglia/rules_rust_apollo_router](https://github.com/bazaglia/rules_rust_apollo_router) and verify a build that was previously failing because of the inconsistency in the exclude globs works with the changes in that PR. Thanks for sharing the diff @UebelAndre. 😃
> Common glob excludes

- crate_universe/private/crates_vendor.bzl
Fixing typo in `crate_universe/private/crates_vendor.bzl`
> crate_universe/private/crates_vendor.bzl typo fix

- crate_universe/private/crates_vendor.bzl
- examples/crate_universe/.bazelrc
This change updates `crate_universe` rules to work with [--nolegacy_external_runfiles](https://bazel.build/reference/command-line-reference#flag--legacy_external_runfiles)
> Updated crate_universe to work with `--nolegacy_external_runfiles`

- rust/private/repository_utils.bzl
- test/unit/repository_utils/repository_utils_test.bzl
In load_arbitrary_tool, use the suburl (which contains the a subdirectory containing the date, if the version is beta or nightly) to look up the sha256 to to download a specific archive. This allows Bazel to cache the downloaded archive by hash, and supports the correct behavior for dated nightly builds, as provided in the FILE_KEY_TO_SHA dict in //rust:known_shas.bzl.
The most recent nightly entry is given in FILE_KEY_TO_SHA as:
```
"2022-11-02/cargo-nightly-x86_64-unknown-linux-gnu.tar.gz": "d32e0a9f78ece567627b9b572912b000c53099c0dd9c9f5cea54848de02c6486",
```
This change fixes downloaded archive caching when using the nightly toolchains, including the default nightly toolchain.
> load_arbitrary_tool uses tool_suburl to look up sha256

- crate_universe/src/utils/starlark/label.rs
For more details, see
https://docs.google.com/document/d/1N81qfCa8oskCk5LqTW-LNthy6EBrDot7bdUsjz6JFC4/edit#heading=h.5mcn15i0e1ch.
This allows us to use crate_universe on a repo with bzlmod enabled.
> Fix labels to work with canonical label literals.

- rust/private/BUILD.bazel
- rust/private/rustfmt.bzl
- tools/runfiles/BUILD.bazel
- tools/runfiles/private/BUILD.bazel
- tools/runfiles/private/runfiles_utils.bzl
- tools/runfiles/runfiles.rs
- tools/rustfmt/BUILD.bazel
- tools/rustfmt/src/lib.rs
This allows users of the Rust runfiles library to construct runfiles paths using a combination of [File.short_path](https://bazel.build/rules/lib/File#short_path) and the new `Runfiles::current_repository` which returns the current workspace name.
Inspired by https://github.com/bazelbuild/bazel/pull/16341
> Add `Runfiles::current_repository` to runfiles library

- test/current_toolchain_files/BUILD.bazel
- test/current_toolchain_files/current_toolchain_files_test.bzl
- test/current_toolchain_files/current_toolchain_files_test_runner.sh
While working on other changes, I had to read through these tests again to understand a failure and felt the use of `genrule` with `sh_test` was more confusing than it was "convenient" to use over writing a dedicated rule. I feel this was the wrong decision and a rule should have always been written so I've done that now.
> Update current_toolchain_files tests to use a dedicated test rule

- rust/platform/triple_mappings.bzl
Corrects `thumbv7m` cpu definition and adds `thumbv6m`.
> Arm Thumb Embedded Targets.

- .bazelci/presubmit.yml
This change adds jobs to CI that test a minimum supported Rust version. This job is intended to inform contributors when a change is being made that would force users to upgrade their Rust version.
closes https://github.com/bazelbuild/rules_rust/issues/828
> Added CI for minimum supported Rust version

- tools/runfiles/runfiles.rs
RUNFILES_DIR is the preferred way to get runfiles directories in bazel.
Also refactor strings into constants for the environment variables while I'm at it.
> Support the RUNFILES_DIR environment variable.

- crate_universe/src/config.rs
- crate_universe/src/context/platforms.rs
- crate_universe/src/lockfile.rs
- crate_universe/src/rendering/template_engine.rs
- crate_universe/src/splicing.rs
- crate_universe/src/splicing/splicer.rs
- crate_universe/tools/urls_generator/src/main.rs
This is necessary together with #1736 to keep the generated BUILD files deterministic. Iterating a hashmap or hashset in hash order is a common source of nondeterminism in code generators (based on my experience with proc macros).
I haven't looked into which of the hashmaps changed in this diff are correctly used. It's *possible* to use a hashmap correctly, if all we do with them is lookups, not iteration. But it's simple enough to just not use hash-based containers entirely and never have hash order nondeterminism problems.
> Eliminate all use of hash-based collections from crate_universe

- crate_universe/src/context/crate_context.rs
- crate_universe/src/rendering.rs
- proto/3rdparty/crates/BUILD.bazel
- proto/3rdparty/crates/BUILD.protobuf-codegen-2.8.2.bazel
- wasm_bindgen/3rdparty/crates/BUILD.bazel
- wasm_bindgen/3rdparty/crates/BUILD.wait-timeout-0.2.0.bazel
Fixes the nondeterminism pointed out in https://github.com/bazelbuild/rules_rust/pull/1735#pullrequestreview-1233384845.
> Collect targets in a deterministic order

- crate_universe/private/crates_repository.bzl
- crate_universe/private/crates_vendor.bzl
- crate_universe/src/metadata.rs
- crate_universe/version.bzl
- docs/crate_universe.md
This change updates the default behavior of re-pinning with `crates_vendor` and `crates_repository` to re-pin workspace dependencies, not all transitive ones. Users who wish to do a full re-pin of all their dependencies should can pass the following values:
- `eager`
- `full`
- `all`
closes https://github.com/bazelbuild/rules_rust/issues/1522
> crate_universe re-pinning now defaults to "workspace"

- .bazelci/presubmit.yml
- test/cargo_build_script/tools_exec.rs
- test/process_wrapper/rustc_quit_on_rmeta.rs
- test/rustfmt/rustfmt_failure_test.sh
This provides regression testing for cases where users have only registered one toolchain in their workspace (meaning they only have a toolchain of a single [channel](https://rust-lang.github.io/rustup/concepts/channels.html) type).
> Added CI for single toolchain channel workspaces

- bindgen/3rdparty/BUILD.bazel
- bindgen/3rdparty/crates/BUILD.bazel
- bindgen/3rdparty/crates/BUILD.clap-3.2.23.bazel
- crate_universe/src/config.rs
- proto/3rdparty/BUILD.bazel
- proto/3rdparty/crates/BUILD.bazel
- proto/3rdparty/crates/BUILD.protobuf-codegen-2.8.2.bazel
This removes, for example, the `protobuf-bin-gen-rust-do-not-use` binary that was previously getting exposed.
https://github.com/bazelbuild/rules_rust/blob/d6e3003594713ba00d03a354cbf7a7c2c65e22d2/proto/3rdparty/crates/BUILD.bazel#L77-L81
I had to change `impl Add for CrateAnnotations` to make crate-level `gen_binaries` work. It turns out in #1718 I didn't fully understand what this `Add` impl was supposed to do, and I had only tested `gen_binaries` _before_ adding the global-level `generate_binaries` argument (https://github.com/bazelbuild/rules_rust/pull/1718#discussion_r1055669481). (I'm still not sure that I understand what this `Add` is supposed to do exactly, but at least now it appears to work in practice.)
The behavior I observed before the change in this PR was that global-level …
> Generate only the needed subset of binaries for bindgen and proto

- cargo/private/cargo_build_script_wrapper.bzl
- docs/cargo.md
- docs/flatten.md
- test/cargo_build_script/BUILD.bazel
I mostly fixed the interaction between `compatible_with` and `cargo_build_script` in https://github.com/bazelbuild/rules_rust/pull/1745, however I forgot to remove the `compatible_with` attribute from the underlying `rust_binary` target. This target shouldn't have the `compatible_with` specification as we only depend on it in `exec` mode.
> Don't propagate `compatible_with` to the underlying `cargo_build_script` `rust_binary` target

- .github/github.bazelrc
The ability to create releases seems to have broken with Bazel 6.0.0
https://github.com/bazelbuild/rules_rust/actions/runs/3847636156/jobs/6554345446#step:6:20
```
Run # Build binaries
2023/01/05 14:35:23 Downloading https://releases.bazel.build/6.0.0/release/bazel-6.0.0-linux-x86_64...
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Reading rc options for 'run' from /home/runner/work/rules_rust/rules_rust/.github/github.bazelrc:
Inherited 'common' options: --announce_rc --color=no --curses=no --show_task_finish --show_timestamps
ERROR: --show_task_finish :: Unrecognized option: --show_task_finish
Error: Process completed with exit code 2.
```
This should fix the issue as it seems by https://github.com/bazelbuild/bazel/issues/14052 this flag was …
> Fix release pipeline

- docs/flatten.md
- docs/providers.md
- proto/proto.bzl
- rust/private/providers.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc.bzl
- rust/private/rustdoc_test.bzl
- test/unit/compile_data/compile_data_env.rs
- test/unit/compile_data/compile_data_test.bzl
- test/unit/consistent_crate_name/with_modified_crate_name.bzl
- test/unit/force_all_deps_direct/generator.bzl
- test/unit/pipelined_compilation/wrap.bzl
Try to fix #1572 
Main issue is that data_paths do not inherit from original crate when building rust_doc (and probably rust_test).
The main idea is to rely on crate_info which inherit correctly from original crate.
Issue with this draft is that compile_data is filed with File instead of Target when building 3rd party crate.
```
ERROR: <redacted>__base64-0.13.1/BUILD.bazel:34:13: in rust_library rule @<redacted>__base64-0.13.1//:base64:
Traceback (most recent call last):
File "external/rules_rust/rust/private/rust.bzl", line 197, column 32, in _rust_library_impl
return _rust_library_common(ctx, "rlib")
File "external/rules_rust/rust/private/rust.bzl", line 292, column 32, in _rust_library_common
return rustc_compile_action(
File "external/rules_rust/rust/private/rustc.bzl", line 1093, …
```
> draft: fix data and compile_data for rust_doc

- crate_universe/private/generate_utils.bzl
- crate_universe/src/context.rs
- crate_universe/src/utils/starlark/glob.rs
- examples/crate_universe/cargo_aliases/cargo-bazel-lock.json
- examples/crate_universe/cargo_workspace/cargo-bazel-lock.json
- examples/crate_universe/multi_package/cargo-bazel-lock.json
- examples/crate_universe/no_cargo_manifests/cargo-bazel-lock.json
- examples/ios_build/cargo-bazel-lock.json
This change fixes an issue raised in https://github.com/bazelbuild/rules_rust/issues/1759 where, because crate_universe lockfiles are unable to be de-seralized, they fail the repin step in `crates_repository`.
```
ERROR: Error computing the main repository mapping: no such package '@crate_index//': Command [/private/var/tmp/_bazel_user/4560c17322c66335f5669efa18a57737/external/crate_index/cargo-bazel, "query", "--lockfile", /Users/user/Code/tmp-infinite-rules-rust-repin/rs/cargo-bazel-lock.json, "--config", /private/var/tmp/_bazel_user/4560c17322c66335f5669efa18a57737/external/crate_index/cargo-bazel.json, "--splicing-manifest", /private/var/tmp/_bazel_user/4560c17322c66335f5669efa18a57737/external/crate_index/splicing_manifest.json, "--cargo", …
```
> Fixed inability to deserialize crate_universe lockfiles

- bindgen/bindgen.bzl
- docs/flatten.md
- docs/rust_bindgen.md
This change updates the `rust_bindgen` rules to rely on `rustfmt_toolchain` to access `rustfmt`. The `rust_bindgen_toolchain` now also has a `default_rustfmt` attribute which informs the rest of the rules whether or not to enable format generated sources by default.
> Updated `rust_bindgen` to use `rustfmt_toolchain`

- crate_universe/private/crates_vendor.bzl
Previously, crates_vendor had the potential to restart bazel every time it runs, as the bazel startup options are dependent on PATH.
> Prevent crates_vendor from restarting bazel.

- .bazelrc
- tools/rustdoc/rustdoc_test_writer.rs
This solution is pretty hacky but should get the job done. I think a hacky solution is acceptable though since the way this rule works is already less than desirable. https://github.com/bazelbuild/rules_rust/issues/1431 tracks the ideal implementation.
closes https://github.com/bazelbuild/rules_rust/issues/1681
> Added support for `--nolegacy_external_runfiles` to `rust_doc_test`

- crate_universe/src/cli/generate.rs
- crate_universe/src/cli/query.rs
- crate_universe/src/cli/splice.rs
- crate_universe/src/cli/vendor.rs
- crate_universe/src/lockfile.rs
- crate_universe/src/metadata.rs
- crate_universe/src/splicing.rs
I'm about to add conditionally setting environment variables depending on the cargo version in-use, so it's useful to route all calls to cargo through controlled methods.
> Encapsulate running cargo into a struct

- docs/rust_fmt.md
- docs/rust_fmt.vm
Add instructions on performing the `rustfmt` check only, i.e., without building the Bazel project.
Fixes #1822
> Instructions on how to perform `rustfmt` check (#1822)

- rust/repositories.bzl
Kythe is currently updating to a newer rules_rust and we are failing to build because we use `dev_components = True` and currently the string target triple is being passed instead of the struct.
> fix: use target_triple struct instead of string

- examples/ios/.bazelrc
- examples/ios/WORKSPACE.bazel
- examples/ios_build/.bazelrc
- examples/ios_build/WORKSPACE.bazel
- rust/repositories.bzl
The Apple toolchain that is used to build iOS targets is moving out of bazel and into the apple_support repo. This switches tests to that toolchain so that this repo continues to work once it is removed from bazel.
https://github.com/bazelbuild/bazel/pull/16619
> Fix tests for new Apple toolchain

- rust/private/rustc.bzl
Right now, `_make_link_flags_default` is used when the target os is `ios`. However, it makes use of `--whole-archive` and `--no-whole-archive` flags, which are not supported by `dyld`.
As it is done for the `macos` target, we should use `-force_load` instead. `_make_link_flags_darwin` does that, therefore we should use it when linking for iOS.
> Use `_make_link_flags_darwin` when target os is `ios`.

- crate_universe/src/metadata.rs
Now that we're racing a bunch of them in parallel, they occasionally print:
> Blocking waiting for file lock on package cache
to stderr.
We print stderr if the process failed, but now swallow this benign output if the process succeeded.
> Pipe stderr from cargo tree processes

- crate_universe/Cargo.lock
- crate_universe/Cargo.toml
- crate_universe/version.bzl
- examples/crate_universe/cargo_aliases/cargo-bazel-lock.json
- examples/crate_universe/cargo_workspace/cargo-bazel-lock.json
- examples/crate_universe/multi_package/cargo-bazel-lock.json
- examples/crate_universe/no_cargo_manifests/cargo-bazel-lock.json
- version.bzl
I'd like to get a release out soon containing a bunch of recent perf improvements for cargo-bazel - is there anything pending which people want to block the release on?
> Release rules_rust and cargo-bazel

- rust/platform/triple_mappings.bzl
The logic introduced/changed in #1805 was not correct. This PR simplifies and fixes it.
Only triples for iOS and watchOS have a simulator ABI, and the following triples need to be set to `@build_bazel_apple_support//constraints:simulator`:
* aarch64-apple-ios-sim
* aarch64-apple-watchos-sim
* x86_64-apple-watchos-sim
* x86_64-apple-ios
All the other iOS and watchOS triples need to have the `@build_bazel_apple_support//constraints:device` constraints.
I was able to successfully build a multi platform (x86_64 sim, aarch64 sim and aarch64 device) xcframework with this patch as a test.
Resolves #1887
> Fix triple constraints for iOS and watchOS

- rust/toolchain.bzl
- test/toolchain/toolchain_test.bzl
Currently `rust_stdlib_filegroup` doesn't provide runfiles, therefore it cannot be easily used to pass all the stdlib artifacts to rules that expect runfiles (for example, passing stdlibs to `sh_test` so the `sh_test` can invoke rustc). This PR fixes that.
> Add runfiles support to rust_stdlib_filegroup

- docs/flatten.md
- docs/rust_doc.md
- rust/private/rustdoc.bzl
- test/unit/rustdoc/rustdoc_requires_args.rs
- test/unit/rustdoc/rustdoc_unit_test.bzl
Add support for `rustdoc_flags` on Rustdoc rules. This avoids some confusion around how to pass args to `rustdoc` as `rustc_flags` is misleading.
> Added `rustdoc_flags` attribute to rust_doc rule

- rust/platform/triple.bzl
It appears that `wmic os get osarchitecture` can also return
```
OSArchitecture
64-Bit
```
Note the capital `B`!
This fails for the string comparison and therefore fails to detect the existing architecture for windows.
Unfortunately i could not find any documentation on why or when this happens, but a simple `lower()` handles both cases just fine
Closes: https://github.com/bazelbuild/rules_rust/issues/1916
> Handle corner case for windows architecture detection

- .bazelci/presubmit.yml
- docs/flatten.md
- docs/rust_repositories.md
- rust/private/repository_utils.bzl
- rust/private/rustc.bzl
- rust/repositories.bzl
- rust/settings/BUILD.bazel
- rust/toolchain.bzl
- test/cc_common_link/BUILD.bazel
- test/cc_common_link/global_allocator_library.cc
- test/cc_common_link/with_global_alloc/BUILD.bazel
- test/cc_common_link/with_global_alloc/WORKSPACE.bazel
- test/cc_common_link/with_global_alloc/main.rs
- test/toolchain/toolchain_test.bzl
`rustc` generates allocator symbols at link time. When we link via `cc_common.link` those symbols are missing because `rustc` is not driving the linking anymore. We compensate by providing the symbols via the `rust_toolchain.allocator_library`.
Rust also allows a global allocator to be specified (via `#[global_allocator]`). The symbols `rustc` generates at link time are different based on whether the system allocator is used, or a global allocator was specified.
Currently, when linking via `cc_common.link`, `#[global_allocator]` is completely ignored. This PR makes using a global allocator actually work:
1. Adding a `rust_toolchain.global_allocator_library` attribute that can point to a set of symbols needed when `#[global_allocator]` is used.
2. Adding a build flag …
> Respect `#[global_allocator]` in `cc_common.link` builds

- crate_universe/src/context/crate_context.rs
- crate_universe/src/metadata/dependency.rs
- crate_universe/src/rendering.rs
- crate_universe/test_data/metadata/aliases/metadata.json
- crate_universe/test_data/metadata/build_scripts/Cargo.lock
- crate_universe/test_data/metadata/build_scripts/Cargo.toml
- crate_universe/test_data/metadata/build_scripts/metadata.json
- crate_universe/test_data/metadata/common/metadata.json
- crate_universe/test_data/metadata/crate_combined_features/metadata.json
- crate_universe/test_data/metadata/crate_optional_deps_disabled/metadata.json
- crate_universe/test_data/metadata/crate_optional_deps_enabled/metadata.json
- crate_universe/test_data/metadata/crate_types/metadata.json
- crate_universe/test_data/metadata/git_repos/metadata.json
- crate_universe/test_data/metadata/multi_cfg_dep/Cargo.lock
- crate_universe/test_data/metadata/multi_cfg_dep/Cargo.toml
- crate_universe/test_data/metadata/multi_cfg_dep/metadata.json
- crate_universe/test_data/metadata/target_cfg_features/metadata.json
- crate_universe/test_data/metadata/target_features/metadata.json
- crate_universe/test_data/metadata/workspace/metadata.json
- crate_universe/test_data/private/metadata_generator.py
This change updates test metadata and adds a test to check the expected behavior for parsing [build dependencies](https://doc.rust-lang.org/cargo/reference/build-scripts.html#build-dependencies) from targets.
> Added tests for build script dependencies to crate_universe

- docs/flatten.md
- docs/rust_repositories.md
- rust/private/repository_utils.bzl
- rust/repositories.bzl
Extension of the feature added in #1623 to expose it at the top-level repository rule.
> feature: expose `extra_rustc_flags` and `extra_exec_rustc_flags` at `rust_register_toolchains`

- docs/flatten.md
- docs/rust_repositories.md
- rust/repositories.bzl
Extra target triples may only be appropriate for specific platforms (e.g. if you register a toolchain with the exec_triple `x86_64-unknown-linux-gnu` with an extra target triple of `x86_64-unknown-linux-musl`, you may want differing `target_compatible_with` values for each of those two target triples.
This allows for specifying explicit `exec_compatible_with` lists per toolchain (which was already supported by `rust_toolchain_repository` just not proxied by `rust_repository_set`), and explicit `target_compatible_with` lists, both for the default triple and for extra ones.
I'm not 100% sure on our pre-existing assumption that every toolchain supports compiling targeting its own exec platform, i.e. the '`[exec_triple]`' part of https://github.com/bazelbuild/rules_rust/blob/937e63399b111a6d7e …
> Allow specifying exec and target compatibility constraints

- .bazelci/presubmit.yml
- cargo/cargo_build_script_runner/bin.rs
- cargo/features.bzl
- cargo/private/cargo_build_script.bzl
- cargo/private/cargo_build_script_wrapper.bzl
- cargo/private/features.bzl
- test/cargo_build_script/BUILD.bazel
- test/cargo_build_script/build.rs
- test/cargo_build_script/test_exec_root_access.build.rs
> Symlink in the exec-root so that relative paths will work, unchanged.

- bindgen/3rdparty/crates/defs.bzl
- crate_universe/3rdparty/crates/defs.bzl
- crate_universe/src/metadata/dependency.rs
- crate_universe/src/rendering/templates/module_bzl.j2
- examples/crate_universe/vendor_external/crates/defs.bzl
- examples/crate_universe/vendor_local_manifests/crates/defs.bzl
- examples/crate_universe/vendor_local_pkgs/crates/defs.bzl
- examples/crate_universe/vendor_remote_manifests/crates/defs.bzl
- examples/crate_universe/vendor_remote_pkgs/crates/defs.bzl
- examples/crate_universe_unnamed/vendor_remote_manifests/crates/defs.bzl
- examples/crate_universe_unnamed/vendor_remote_pkgs/crates/defs.bzl
- examples/ios_build/3rdparty/crates/defs.bzl
- examples/sys/basic/3rdparty/crates/defs.bzl
- examples/sys/complex/3rdparty/crates/defs.bzl
- proto/3rdparty/crates/defs.bzl
- tools/rust_analyzer/3rdparty/crates/defs.bzl
- util/import/3rdparty/crates/defs.bzl
- wasm_bindgen/3rdparty/crates/defs.bzl
```diff
vv
- dependnecies
+ dependencies
^^
```
This typo ends up in the caller's repo after they run crates_vendor, so it's worth fixing to keep from tripping a spell checker they might run on their repo.
> Fix typo in crate_universe-generated defs.bzl comment

- crate_universe/private/crates_repository.bzl
- docs/crate_universe.md
Stardoc escapes raw HTML, so this was outputting an escaped anchor tag, and a broken link, rather than working.
> Fix up anchor link

- .bazelci/presubmit.yml
- .bazelrc
- examples/.bazelrc
- examples/android/.bazelrc
- examples/bzlmod/hello_world/.bazelrc
- examples/crate_universe/.bazelrc
- examples/crate_universe/cargo_aliases/.bazelrc
- examples/crate_universe/cargo_remote/.bazelrc
- examples/crate_universe/cargo_workspace/.bazelrc
- examples/crate_universe/multi_package/.bazelrc
- examples/crate_universe/no_cargo_manifests/.bazelrc
- examples/crate_universe_unnamed/.bazelrc
- examples/ios/.bazelrc
- examples/ios_build/.bazelrc
- examples/zig_cross_compiling/.bazelrc
Rather than writing them in .bazelci yaml blocks.
This makes running the examples on Windows more likely to work out of the box.
> Set windows flags in platform-specific bazelrc

- crate_universe/private/crates_vendor.bzl
This fixes a similar issue to #1514, fixed by #1575.
When using Bzlmod, the main default repository name is now `_main`, instead of `__main__`. This PR extends detection of this use case to both scenarios.
> Fixes crates_vendor workspace name detection when using bzlmod

- examples/.bazelrc
- examples/android/.bazelrc
- examples/bzlmod/hello_world/.bazelrc
- examples/crate_universe/.bazelrc
- examples/crate_universe/cargo_aliases/.bazelrc
- examples/crate_universe/cargo_remote/.bazelrc
- examples/crate_universe/cargo_workspace/.bazelrc
- examples/crate_universe/multi_package/.bazelrc
- examples/crate_universe/no_cargo_manifests/.bazelrc
- examples/crate_universe_unnamed/.bazelrc
- examples/ios/.bazelrc
- examples/ios_build/.bazelrc
- examples/zig_cross_compiling/.bazelrc
It looks like startup doesn't support platform-specific config, but the only thing we use it for is windows-only anyway
(`--windows_enable_symlinks`).
> Don't use startup:windows

- crate_universe/private/crates_repository.bzl
- crate_universe/private/crates_vendor.bzl
- crate_universe/private/generate_utils.bzl
- crate_universe/private/srcs.bzl
- crate_universe/src/cli/generate.rs
- crate_universe/src/cli/vendor.rs
- crate_universe/src/config.rs
- crate_universe/src/lockfile.rs
- crate_universe/src/rendering.rs
- crate_universe/src/utils/starlark.rs
- crate_universe/src/utils/starlark/target_compatible_with.rs
- crate_universe/test_data/serialized_configs/BUILD.bazel
- docs/crate_universe.md
This should resolve the problem where a platform is targeted that isn't listed in `supported_platform_triples` (in `crates_repository()`) and no error manifests until a missing dependency (or some similar error due to an omitted branch in a `select()`) is encountered.
> feature: `target_compatible_with` added to `CommonAttrs`

- docs/BUILD.bazel
- docs/defs.md
- docs/flatten.md
- docs/symbols.bzl
- rust/private/common.bzl
- rust/private/providers.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/rust_common.bzl
This seems like a much cleaner interface and gives users more confidence that `CrateInfo` providers are paired with the right `DepInfo` providers.
A follow-up to https://github.com/bazelbuild/rules_rust/pull/1848
> Update `rust_library_group` to use `DepVariantInfo`

- proto/prost/private/3rdparty/BUILD.heck.bazel
- proto/prost/private/BUILD.bazel
- proto/prost/private/protoc_wrapper.rs
- proto/prost/private/tests/sanitized_modules/BUILD.bazel
- proto/prost/private/tests/sanitized_modules/bar.proto
- proto/prost/private/tests/sanitized_modules/foo.proto
- proto/prost/private/tests/sanitized_modules/sanitized_modules_test.rs
- proto/prost/repositories.bzl
This normalizes module names to be consistently written as lowercase. When given extravagant package names `prost-build` will snake_case package names `PackageX.FooBar` would become `package_x.foo_bar`. This change contains two commits where the first solves a bug where the extern paths that the process wrapper generated did not match the the paths `prost-build` would render. Sanitizing these to lowercase is the simplest fix. The second commit contains a change to add snake_case support by bringing in the same library `prost-build` uses to do the same logic but is a more complicated implementation. I personally lean toward the simpler solution but leave it up to my reviewers.
> Fix prost proto packages not sanitizing to valid module names

- docs/flatten.md
- docs/rust_proto.md
- proto/prost/private/prost.bzl
Since `prost_plugin_flag` has a default value (`--plugin=protoc-gen-prost=%s`), we don't need to flag it as mandatory, otherwise people have to explicitely set it to the same value as the default one.
> Remove `mandatory = True` from the `prost_plugin_flag` attribute in `rust_prost_toolchain`.

- bindgen/bindgen.bzl
- cargo/private/cargo_build_script.bzl
- proto/protobuf/toolchain.bzl
- rust/private/clippy.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc.bzl
- rust/private/rustfmt.bzl
- test/process_wrapper/process_wrapper_tester.bzl
Some minor optimizations to analysis time memory usage (avoid creating some list temporaries, some extra strings, etc.)
Some of the usage might be simpler as `args.add("foo", foo)` instead of `args.add(foo, format="foo=%s")` but I opted to keep the usage the same as before for safety.
> Cleanup args construction

- examples/crate_universe/WORKSPACE.bazel
- examples/crate_universe/using_cxx/BUILD.bazel
- examples/crate_universe/using_cxx/cargo-bazel-lock.json
- examples/crate_universe/using_cxx/rust_cxx_bridge.bzl
See the build error on 9221306cb9ef2a77d732c89f6d9980b7e4a1b1b0 (the parent commit of 8b26c2d7637b445889224112ac0c021cb7821592).
```console
ERROR: C:/b/gk6ogkw7/external/using_cxx__cxx-1.0.104/BUILD.bazel:96:11: Linking external/using_cxx__cxx-1.0.104/cxx_cc_6cbd2ac8.dll failed: (Exit 1120): link.exe failed: error executing command (from target @using_cxx__cxx-1.0.104//:cxx_cc)
cd /d C:/b/gk6ogkw7/execroot/examples
SET LIB=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\um\x64
SET PATH=C:\Program Files (x86)\Microsoft Visual …
```
> Make @using_cxx example buildable on Windows

- cargo/private/cargo_build_script.bzl
Build scripts of link dependencies need access to the 'target' environment which contains the library being linked against. This is needed to correctly cross-compile.
> Remove cfg exec from link_deps attribute

- rust/private/rustc.bzl
[cc_toolchain.linker_files()](https://github.com/bazelbuild/bazel/blob/69d3eccf8d75af80586fcb8249db66ba2e5476cb/src/main/java/com/google/devtools/build/lib/starlarkbuildapi/cpp/CcToolchainProviderApi.java#L198-L199) returns the linker files [used by cc](https://github.com/bazelbuild/bazel/blob/69d3eccf8d75af80586fcb8249db66ba2e5476cb/src/main/java/com/google/devtools/build/lib/rules/cpp/CcLinkingHelper.java#L881-L885) when building cc link action.
Using the same files in rust ensure it has the correct files to resolve the link args returned from cc toolchain. This also allows custom specification on [cc_toolchain.linker_files attribute](https://bazel.build/versions/6.2.0/reference/be/c-cpp#cc_toolchain) is correctly resolved.
> Use cc_toolchain.linker_files() for files required at linking steps

- rust/private/rustdoc.bzl
- test/unit/rustdoc/rustdoc_unit_test.bzl
This makes it easier to make a test ensuring rustdoc doesn't emit warnings.
> rustdoc: respect error_format config

- crate_universe/src/config.rs
- crate_universe/src/context/crate_context.rs
- crate_universe/src/rendering.rs
- crate_universe/src/utils/starlark/select.rs
- examples/crate_universe/multi_package/cargo-bazel-lock.json
This is a follow-up to #2139 making more annotations support `select`-ing.
> Make more annotations select-able

- .bazelrc
- examples/.bazelrc
- examples/android/.bazelrc
- examples/crate_universe/.bazelrc
- examples/crate_universe/cargo_aliases/.bazelrc
- examples/crate_universe/cargo_remote/.bazelrc
- examples/crate_universe/cargo_workspace/.bazelrc
- examples/crate_universe/multi_package/.bazelrc
- examples/crate_universe/no_cargo_manifests/.bazelrc
- examples/crate_universe_unnamed/.bazelrc
- examples/ios/.bazelrc
- examples/ios_build/.bazelrc
- examples/zig_cross_compiling/.bazelrc
This will help make sure [Bazel Downstream Pipeline](https://github.com/bazelbuild/continuous-integration/blob/master/docs/downstream-testing.md) is green after enabling Bzlmod at Bazel@HEAD
See https://github.com/bazelbuild/bazel/issues/18958#issuecomment-1749058780
Related issue: https://github.com/bazelbuild/rules_rust/issues/2181
> Disable Bzlmod explicitly in .bazelrc

- rust/platform/triple.bzl
The repository_ctx has already populated the arch and normalized it. Tested this locally on Mac/Linux amd/arm, but don't have an easy windows setup. Let's see what CI says.
> Simplify CPU arch detection in get_host_triple

- .bazelci/presubmit.yml
- docs/index.md
Also, update the docs to reflect that realistically we can't support Windows well without a relevant maintainer.
This is a very large hammer, but realistically these tests have wasted a lot of our time and no one is well positioned to address them.
Fixes #1946 
Relates to #2186
> Disable frequently failing Windows CI

- test/toolchain/toolchain_test.bzl
- test/unit/channel_transitions/channel_transiitons_test.bzl
- test/unit/clippy/clippy_test.bzl
- test/unit/extra_rustc_flags/extra_rustc_flags_test.bzl
- test/unit/per_crate_rustc_flag/per_crate_rustc_flag_test.bzl
- test/unit/pipelined_compilation/pipelined_compilation_test.bzl
- test/unit/proc_macro/leaks_deps/proc_macro_does_not_leak_deps.bzl
- test/unit/rustdoc/rustdoc_unit_test.bzl
With bzlmod enabled, errors like the following would occur:
```
Error in analysis_test_transition: invalid transition output '@[unknown repo '' requested from @bazel_skylib~1.3.0]//:clippy_flags': no repo visible as @ from repository '@bazel_skylib~1.3.0'
```
To resolve this, use str(Label("...")) to get the canonical label to use as the key in config_settings.
Related issues: #2181, bazelbuild/bazel#19286
> Use canonical labels for analysistest config_settings

- proto/prost/private/protoc_wrapper.rs
- proto/prost/private/tests/camel_case/BUILD.bazel
- proto/prost/private/tests/camel_case/another.proto
- proto/prost/private/tests/camel_case/camel_case.proto
- proto/prost/private/tests/camel_case/camel_case_test.rs
For example, the message name `SomeAPI`. Internally protoc-gen-prost [converts](https://github.com/neoeinstein/protoc-gen-prost/blob/1a6d3593622af18b75a4a79f545f8530cdaf444f/protoc-gen-tonic/src/util.rs#L14) this to upper camel case, but rules_rust is not doing that when populating the `--extern_path` args. The result is that when a message with an acroynym in its name is included in another proto file, the generated code has a type name with the wrong casing.
Without this fix, the added test fails to build like this:
```
error[E0412]: cannot find type `NameWithCAPS` in module `camel_case_proto::camel_case`
--> bazel-out/k8-fastbuild/bin/proto/prost/private/tests/camel_case/another_proto.lib.rs:9:75
|
9 |         pub inner: ::core::option::Option<::camel_case_proto::camel_case::NameWithCAP …
```
> [prost] Fix handling of message names with acronyms

- .gitattributes
- examples/crate_universe/WORKSPACE.bazel
- examples/crate_universe/using_cxx/Cargo.Bazel.lock
- examples/crate_universe/using_cxx/cargo-bazel-lock.json
- examples/crate_universe/using_cxx/cxxbridge-cmd.Cargo.Bazel.lock
- examples/crate_universe/using_cxx/cxxbridge-cmd.Cargo.lock
This eliminates the annotation introduced by https://github.com/bazelbuild/rules_rust/pull/2192, because it includes https://github.com/dtolnay/cxx/pull/1277.
This PR includes handwritten changes to WORKSPACE.bazel followed by the generated result of running:
- `cd examples/crate_universe/using_cxx`
- `CARGO_BAZEL_REPIN=1 bazel sync --only=using_cxx`
- `CARGO_BAZEL_REPIN=1 bazel sync --only=cxxbridge_cmd_deps`
Tested by running `bazel build ...` in the same directory.
> Update using_cxx example to cxx 1.0.109

- .bazelci/presubmit.yml
- examples/android/BUILD.bazel
- examples/android/platform_mappings
Part of https://github.com/bazelbuild/bazel/issues/16285.
> Add Android Platforms build flags.

- cargo/private/cargo_build_script_wrapper.bzl
- docs/cargo.md
- docs/flatten.md
Before https://github.com/bazelbuild/rules_rust/commit/3e124fb9f5fb91554908fd7fb82d10c378ee4ca8 this was implicitly handled by passing **binary_kwargs to the rust_binary, now we're making this explicit.
> add compile_data attr to cargo_build_script

- version.bzl
To pick up recent internal API changes about the crate_info -> dict changes. Some users like Crubit and rust Protobuf use these internal APIs, it would be nice for them to be adapted accordingly and refer them to the new version.  But since these are internal, just updating the minor version.
(it's my first time prepping a release, is there anything beyond just getting something like this submitted for the released archives to be created?)
> Prep release 0.29.1

- crate_universe/private/crate.bzl
- docs/crate_universe.md
Followup to #2226. That PR made bindeps work for crates repositories that use `manifests`.
https://github.com/bazelbuild/rules_rust/blob/d86faee8b85cc334e0529193142f4b61362e79a3/examples/crate_universe/WORKSPACE.bazel#L60
This PR makes it work for crates repositories that use `packages`.
https://github.com/bazelbuild/rules_rust/blob/43b101e6b3e679b333c2622d7615233edf344624/examples/crate_universe/WORKSPACE.bazel#L317-L320
> Support artifact dependencies in crate.spec

- test/process_wrapper/fake_rustc.rs
- test/process_wrapper/rustc_quit_on_rmeta.rs
- util/process_wrapper/main.rs
- util/process_wrapper/output.rs
- util/process_wrapper/rustc.rs
Previously we were only reporting the first line of any error rustc may emit when it panic'd or otherwise unexpectedly stopped outputting json.
> process_wrapper: write all output from rustc if json parsing fails.

- docs/MODULE.bazel
- docs/MODULE.bazel.lock
Otherwise the 'docs' pipeline on Bazel CI complains that docs are out of date: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3447#018bb1e5-7c49-4729-88d9-893149ed99e2
> Fix docs for Bazel@HEAD

- .bcr/README.md
- .bcr/config.yml
- .bcr/metadata.template.json
- .bcr/presubmit.yml
- .bcr/source.template.json
Add machinery to automatically push GitHub releases to bazel central registry. This will need some setup by the ruleset maintainers to enable the GitHub app when bzlmod support is ready. See the [instructions](https://github.com/apps/publish-to-bcr) for more details
Ref #2181
> Add configuration to mirror github releases to bazel central registry

- .rustfmt.toml
- docs/rust_fmt.md
- docs/rust_fmt.vm
- test/rustfmt/BUILD.bazel
- test/rustfmt/rustfmt_failure_test.sh
- test/rustfmt/rustfmt_integration_test_suite.bzl
- test/rustfmt/srcs/generated/lib.rs
- test/rustfmt/test_rustfmt.toml
- tools/rustfmt/rustfmt.toml
closes https://github.com/bazelbuild/rules_rust/issues/2254
> Support rustfmt on crates with generated sources

- tools/rust_analyzer/rust_project.rs
The generated content uses ${pwd} and in the rust-analyzer server output I see error logs saying can't find dir with ${pwd} references
Though I'm not sure if this actually affect anything as it seems work fine most of the time, but I think it maybe good to not have rust-analyzer errors
> replace pwd in rust-project.json output #1

- cargo/private/cargo_build_script_wrapper.bzl
- docs/cargo.md
- docs/flatten.md
- test/cargo_build_script/rustc_env_files/BUILD.bazel
- test/cargo_build_script/rustc_env_files/build.rs
- test/cargo_build_script/rustc_env_files/test_lib.rs
> cargo_build_script can use rustc_env_files

- proto/prost/private/prost.bzl
This allows rust-analyzer to autocomplete definitions like ::decode() and other methods that are found in ::prost::Message.
> rust-analyzer: Include prost_runtime as a dep for rust_prost_library

- crate_universe/src/metadata/dependency.rs
Follow-up to #2235 that corrects the `DependencyKind` used. This bug caused optional dependencies to be incorrectly _included_ even no feature activated that dependency. This can lead to crates being compiled with missing features, resulting in compile errors.
For example, `sqlx==0.7.3` compiled successfully with `0.30.0`, but fails with `0.31.0`:
```toml
sqlx = { version = "0.7.3", default-features = false, features = ["sqlite"] }
```
because `default-features = false` should remove the [optional dependency](https://github.com/launchbadge/sqlx/blob/c55aba0dc14f33b8a26cab6af565fcc4c8af8962/Cargo.toml#L54-L56) `sqlx-macros`. Instead, however, it gets incorrectly included but with its crate dependencies' features missing, resulting in compile errors.
Related issue:
- …
> Fix inclusion/exclusion of optional dependencies

- BUILD.bazel
- MODULE.bazel
- rust/repositories.bzl
- test/bzl_version/BUILD.bazel
- test/bzl_version/bzl_version_test.rs
This also adds a test to ensure `//:version.bzl` and `//:MODULE.bazel` both specify the same version for `rules_rust`. Note that `//:version.bzl` is still the source of truth that will kick off releases via github actions
> Updated direct dependencies

- .bazelci/presubmit.yml
Add an environment which builds without a workspace file.
This will allow us to verify that targets such as cargo_bazel can build with bzlmod. This is mainly useful to ensure that your dependencies are specified in MODULE.bazel, rather than WORKSPACE. At the moment, I only specify a single target, to verify that it's working. As we start supporting additional targets, entries will be added here to prevent regressions.
> Add a new presubmit environment for bzlmod

- crate_universe/private/srcs.bzl
- crate_universe/src/config.rs
- crate_universe/src/context.rs
- crate_universe/src/context/platforms.rs
- crate_universe/src/lockfile.rs
- crate_universe/src/metadata.rs
- crate_universe/src/rendering.rs
- crate_universe/src/utils.rs
- crate_universe/src/utils/target_triple.rs
- examples/nix_cross_compiling/bazel/cargo/cargo-bazel-lock.json
As discussed on Slack with @illicitonion (hopefully).  With the `Select` refactor, we presumably want `selects` to be keyed by `TargetTriple` instead of `String`.  Please let me know if you have a better interface for `TargetTriple` and/or any bikesheds 🙂
> Introduced `TargetTriple` newtype.

- crate_universe/src/splicing.rs
This is a fix for supporting sparse-registries (private).
When we tried to use crate_universe together with an internal sparse registry (Artifactory) we ran into an issue. `cargo-bazel splice` was not correctly detecting sparse registries as "sparse", even though the URLs correctly started with the "sparse+https://" prefix in the Cargo.lock file. Instead it re-interpreted them as registries with a git index.
The root cause of this is that`cargo_lock::Lockfile` automatically removes the prefix `sparse+` from the URL and the only way to determine that a registry is sparse is to check the `kind`. The code previously assumed it could check for sparse registries by checking if the url starts with "sparse+https://".
This pull requests adapts the code so it uses the lockfile "SourceKind" instead …
> cargo-bazel: Corrected sparse registry splicing code

- .envrc
`nix_direnv_watch_file` is deprecated and appears to have been removed from some `direnv` distributions.
> fix: use `watch_file` in `.envrc`

- rust/private/rust.bzl
Just noticed this inconsistency, updated similarly to rust_library.
> _rust_binary_impl: propagate `data` to the crate info

- examples/WORKSPACE.bazel
Bazel 7 stopped the Bazel in-built cc toolchain from knowing about Xcode and the env vars it requires.
This change registers an Apple-aware cc toolchain, which will only be used on macOS platforms.
Fixes #2207
> Register apple cc toolchain

- MODULE.bazel
See discussion in github.com/bazelbuild/bazel-central-registry/pull/1199
> Register a toolchain by default in MODULE.bazel

- rust/private/utils.bzl
Instead of looking for "-exec-" look for "-exec" since that portion may be the last component of the output path mneumonic.
Ultimately fixes issues with --experimental_platforms_in_output_dir that had sufficiently improved calculations to remove the need for an ST-hash and thus surfaced this issue.
Ideally, in the long term, this heuristic would not be used and whether an artifact is in the exec configuration would be determined by tracking the provenance of that artifact. However, this would likely require a more significant rework.
> Adjust is_exec_configuration heuristic

- bindgen/private/BUILD.bazel
- bindgen/private/bindgen.bzl
- docs/flatten.md
- docs/rust_bindgen.md
- examples/bindgen/simple.h
This change parses `cc_toolchain` flags for `c++-compile` actions for use in bindgen. This change aims to allow the action to gain toolchain specific include paths as well as a more accurate `--sysroot`.
> Include more cc_toolchain flags in RustBindgen actions

- .bazelci/presubmit.yml
- .bazelrc
- rust/defs.bzl
- rust/private/rust.bzl
- rust/private/unpretty.bzl
- rust/settings/BUILD.bazel
- test/unit/force_all_deps_direct/force_all_deps_direct_test.bzl
- test/unpretty/BUILD.bazel
- test/unpretty/proc_macro.rs
- test/unpretty/proc_macro.unpretty.expanded.rs
- test/unpretty/proc_macro_test.rs
- test/unpretty/proc_macro_test.unpretty.expanded.rs
Proposal for https://github.com/bazelbuild/rules_rust/issues/1642
Duplicates https://github.com/bazelbuild/rules_rust/pull/1643 (special thanks to @freeformstu)
Rustc can be used to expand all macros so that you can inspect the generated source files easier.
This feature is enabled via `-Zunpretty={mode}`. The `-Z` flag is only available in the nightly
version of `rustc` (https://github.com/rust-lang/rust/issues/43364).
Build and test your targets normally.
```
bazel build //:ok_binary   
INFO: Analyzed target //:ok_binary (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //:ok_binary up-to-date:
bazel-bin/ok_binary
INFO: Elapsed time: 0.081s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```
Use the aspect to …
> Added `rust_unpretty_aspect` and `rust_unpretty` rules

- .bazelci/presubmit.yml
- examples/bzlmod/hello_world/BUILD.bazel
- examples/bzlmod/hello_world/hello_world_test.sh
A followup to https://github.com/bazelbuild/rules_rust/pull/2370#discussion_r1437744310
> Ensure bzlmod example tests are run

- bindgen/private/bindgen.bzl
Now that sysroots are correctly detected, bindgen is going to need sources from them.
> Add cc_toolchain files to bindgen actions

- .github/workflows/release.yaml
Fixes #2378.
```console
$ tar -czf .github/rules_rust.tar.gz --exclude=".git" --exclude=".github" --exclude="crate_universe/target" examples/bzlmod --exclude="examples" .
$ tar tf .github/rules_rust.tar.gz | rg examples
examples/bzlmod/
examples/bzlmod/hello_world/
examples/bzlmod/hello_world/WORKSPACE.bzlmod
examples/bzlmod/hello_world/hello_world_test.sh
examples/bzlmod/hello_world/.gitignore
examples/bzlmod/hello_world/WORKSPACE.bazel
examples/bzlmod/hello_world/src/
examples/bzlmod/hello_world/src/main.rs
examples/bzlmod/hello_world/BUILD.bazel
examples/bzlmod/hello_world/MODULE.bazel
examples/bzlmod/hello_world/third-party/
examples/bzlmod/hello_world/third-party/Cargo.lock
examples/bzlmod/hello_world/third-party/BUILD.bazel
examples/bzlmod/hello_world/third-party/extension.bzl …
```
> Include examples/bzlmod in release tgz for BCR presubmit

- crate_universe/private/module_extensions/cargo_bazel_bootstrap.bzl
This function isn't yet used. It will be used in #1910. I'm splitting it into its own PR because no-one seems to want to review #1910 because it's too big.
> Allow using cargo_bazel_bootstrap from module extensions

- .github/release_notes.template
- .github/workflows/release.yaml
`integrity` is preferred because it works for both `http_archive` (legacy) and `archive_override` (bzlmod). `sha256` only works for `http_archive`. Context: https://github.com/bazelbuild/bazel/pull/20156
I confirmed that `xxd` and `base64` commands are available in the GitHub ubuntu-20.04 runner:
and that this produces an integrity string that checks out with what Bazel wants. See https://github.com/dtolnay/cxx/commit/17f46ec7a5392a6d4b817464847e5261b5133f09 for a successful use of `integrity` with `http_archive`:
```starlark
http_archive(
name = "rules_rust",
integrity = "sha256-p2HVTknbBvhjRo5rukoTJSsb1Jno9wbaZeJ5s7y8XFI=",
urls = ["https://github.com/bazelbuild/rules_rust/releases/download/0.36.2/rules_rust-v0.36.2.tar.gz"],
)
```
and https://github.com/dtolnay/cxx/pull/1294 for a …
> Switch from `sha256` to `integrity` in release notes

- crate_universe/extension.bzl
- examples/bzlmod/hello_world/BUILD.bazel
- examples/bzlmod/hello_world/MODULE.bazel
- examples/bzlmod/hello_world/hello_world_test.sh
This PR adds bzlmod support for third party crates via rules_rust.
It only adds some subset of crate_universe's features. Specifically, it supports:
* Using a Cargo.toml  and Cargo.lock file as the source of truth for dependencies.
* Automatically generating build targets for your referenced dependencies in Cargo.toml.
* One repo per Cargo.toml / Cargo.lock, to namespace and prevent implicit dependencies.
Out of scope of this PR is:
* Vendoring deps
* all_crate_deps or similar
> Support third party crates with bzlmod

- wasm_bindgen/private/wasm_bindgen.bzl
https://github.com/bazelbuild/rules_rust/pull/2284 removed the .wasm output file from the `DefaultInfo` provider, which makes it unavailable to other downstream rules.
This PR restores the behavior pre-0.32.0.
> Fix missing .wasm output for rust_wasm_bindgen

- crate_universe/private/crate.bzl
This is needed for https://github.com/bazelbuild/rules_rust/pull/2392 as starlark doesn't JSON-serialize labels.
> Stringify annotation labels

- examples/bzlmod/hello_world/BUILD.bazel
- rust/repositories.bzl
It looks like we register these as _tools not as _srcs, this looks like it was maybe a typo in https://github.com/bazelbuild/rules_rust/pull/1528
Fixes #2388
> Fix name of toolchain repo

- .bazelci/presubmit.yml
- test/BUILD.bazel
- test/query_test_binary.sh
This will ensure we don't regress https://github.com/bazelbuild/rules_rust/issues/2359
We can discuss adding this to different configurations (e.g. bazel versions, bzlmod enabled vs disabled, ...), but I think "latest bazel in its default config" is a reasonable place to start.
> Add test for query and cquery in the repo

- docs/flatten.md
- docs/rust_repositories.md
- rust/private/repository_utils.bzl
- rust/repositories.bzl
- test/unit/repository_utils/repository_utils_test.bzl
Rust infra folks requested that I send this change.
According to Rust's logs, currently 30% of bytes served by static.rust-lang.org are .gz tarballs, and primarily that is attributed to Bazel according to user-agent.
The .gz tarballs are needlessly large and consume more bandwidth for Rust than we want to serve.
This PR changes rules_rust to default to .xz tarballs instead. Rustup has been using xz downloads for the past 6.5 years.
The default set of tars downloaded by rules_rust (rustc, rust-std, cargo, clippy, rustfmt, llvm-tools) is 215M in gz and 127M in xz, which is 41% smaller. If adopted, this PR would save static.rust-lang.org more than 12% of its bandwidth.
As a tradeoff, decompressing that set of 6 files with xz is slower: 3.6 seconds for gz and 8.4 seconds for xz. …
> Change default Rust distribution downloads from .tar.gz to .tar.xz

- crate_universe/extension.bzl
- crate_universe/private/crate.bzl
It was documented incorrectly as a list, but the parameter is actually an Option<String> in the rust code (https://github.com/bazelbuild/rules_rust/blob/a1e9f9600cd22ecfdd08fc4a7572ccbdeba97395/crate_universe/src/metadata/metadata_annotation.rs#L152)
> Fix the patch_tool annotation.

- bindgen/private/bindgen.bzl
This commit fixes #2402 by using [`get_lib_name_default`] to pass libraries names to `rustc` through `-lstatic` instead of relying on the owner's name of the `File` object.
[`get_lib_name_default`]: https://github.com/bazelbuild/rules_rust/blob/a1e9f9600cd22ecfdd08fc4a7572ccbdeba97395/rust/private/utils.bzl#L101
> Fix #2402: use `get_lib_name_default(lib)` instead of `lib.owner.name`.

- bindgen/private/bindgen.bzl
This commit fixes issue #2406 by using the [`link-args`] codegen option of `rustc`:
```
-C
link-args=<user_link_flags>
```
where `<user_link_flags>` are the flags from the [`user_link_flags`] field of [`LinkerInput`].
[`user_link_flags`]: https://bazel.build/rules/lib/builtins/LinkerInput#user_link_flags
[`LinkerInput`]: https://bazel.build/rules/lib/builtins/LinkerInput
[`link-args`]: https://doc.rust-lang.org/rustc/codegen-options/index.html#link-args
> Fix #2406: use codegen option `link-args` to forward `user_link_flags` in bindgen.

- .bazelci/presubmit.yml
- examples/android/.bazelrc
- examples/android/WORKSPACE.bazel
The native version of `android_ndk_repository` rule no longer work with the newer ndk versions.
When I set `ANDROID_NDK_HOME` to `/usr/local/vinhdaitran/Android/Sdk/ndk/26.1.10909125`, the rule expects a different structure from the Android NDK path.
```
ERROR: /usr/local/vinhdaitran/github/rules_rust/examples/android/WORKSPACE.bazel:67:23: fetching android_ndk_repository rule //external:androidndk: java.io.IOException:
Expected directory at /usr/local/vinhdaitran/Android/Sdk/ndk/26.1.10909125/platforms but it is not a directory or it does not exist.
Unable to read the Android NDK at /usr/local/vinhdaitran/Android/Sdk/ndk/26.1.10909125, the path may be invalid. Is the path in android_ndk_repository() or ANDROID_NDK_HOME set correctly?
If the path is correct, the contents in the Android …
```
> Update android example to use Starlark version of android_ndk_repository

- rust/private/rustc.bzl
https://github.com/bazelbuild/rules_rust/issues/2425
> Prepare rust rules for Starlark CcToolchainInfo.

- rust/private/rustc.bzl
- rust/settings/BUILD.bazel
- rust/toolchain.bzl
To remove `SYSROOT` from Rustc actions
> Added `incompatible_no_rustc_sysroot_env`

- .bazelci/presubmit.yml
- .bcr/presubmit.yml
- tools/tool_utils.bzl
Currently when running `gen_rust_project`, the aspect given to bazel has the canonical repo name but only a single `@`. This does not work with bzlmod, since it tries to resolve this using the repository mappings, and complains that the repository does not exist:
```
ERROR: Unable to find package for @@[unknown repo 'rules_rust~0.38.0' requested from @@]//rust:defs.bzl: The repository '@@[unknown repo 'rules_rust~0.38.0' requested from @@]' could not be resolved: No repository visible as '@rules_rust~0.38.0' from main repository.
ERROR: Analysis of aspects '[@@[unknown repo 'rules_rust~0.38.0' requested from @@]//rust:defs.bzl%rust_analyzer_aspect] with parameters {} on //prost:prost_toolchain_impl' failed; build aborted: Unable to find package for @@[unknown repo 'rules_rust~0.38.0' …
```
> Use canonical repo name for aspects

- rust/private/rustc.bzl
If `rustc_compile_action` is invoked within an aspect of a rule, without this change, an `InstrumentedFilesInfo` would be created, which conflicts with the `InstrumentedFilesInfo` with the underlying target, causing a bazel action conflict. Thus, we add an option (default to `True`) so that aspect can specify this option when invoking `rustc_compile_action`, to avoid creating `InstrumentedFilesInfo`.
> Add argument `include_coverage` to toggle if `InstrumentedFilesInfo` is created

- crate_universe/private/crates_vendor.bzl
Otherwise using `cargo_config` with `crate.from_cargo(` fails with a JSON encoding error.
> Fix serialization of cargo_config attribute with bzlmod

- .bazelci/presubmit.yml
- rust/private/rust_analyzer.bzl
Before this change, users would fail with the following error:
```
~/Code/rules_rust/examples (main ✔) bazel run @rules_rust//tools/rust_analyzer:gen_rust_project
INFO: Analyzed target @@rules_rust//tools/rust_analyzer:gen_rust_project (51 packages loaded, 2095 targets configured).
INFO: Found 1 target...
Target @@rules_rust//tools/rust_analyzer:gen_rust_project up-to-date:
bazel-bin/external/rules_rust/tools/rust_analyzer/gen_rust_project
INFO: Elapsed time: 0.530s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/external/rules_rust/tools/rust_analyzer/gen_rust_project
Error: bazel build failed:(exit status: 1)
Computing main repo mapping:
Loading:
Loading: 0 packages loaded
Analyzing: 99 targets …
```
> Fix type error in rust-analyzer rule

- crate_universe/private/crates_repository.bzl
- crate_universe/src/metadata.rs
- docs/crate_universe.md
This change corrects the parsing logic of `CARGO_BAZEL_REPIN` to solve for the following issue
```
CARGO_BAZEL_REPIN=ahash@0.7.7 bazel build //...
```
```
ERROR: /home/user/Code/factory/WORKSPACE.bazel:162:12: fetching crates_repository rule //external:crates_io: Traceback (most recent call last):
File "/home/user/.cache/bazel/_bazel_user/2a4a06230c9b85a2073801b413943939/external/rules_rust/crate_universe/private/crates_repository.bzl", line 59, column 50, in _crates_repository_impl
metadata_path = splice_workspace_manifest(
File "/home/user/.cache/bazel/_bazel_user/2a4a06230c9b85a2073801b413943939/external/rules_rust/crate_universe/private/splicing_utils.bzl", line 178, column 12, in splice_workspace_manifest
execute(
File "/home/user/.cache/bazel/_bazel_user/2a4a06230c9b85a2073801b413943 …
```
> Update crate_universe to allow re-pinning precise packages with pins

- util/label/label.rs
Doing my best to adhere to https://bazel.build/concepts/labels. This change updates the label utility to account for modern changes to Bazel labels (e.g. from bzlmod).
> Updated label crate to understand canonical vs apparent repositories

- crate_universe/src/rendering/templates/partials/module/deps_map.j2
I believe this was an oversight from #2491, that this is lacking.
> Fix all-crate-deps with bzlmod and conditionals.

- crate_universe/src/config.rs
- crate_universe/src/context.rs
- crate_universe/src/context/crate_context.rs
- crate_universe/src/context/platforms.rs
- crate_universe/src/lockfile.rs
- crate_universe/src/metadata.rs
- crate_universe/src/metadata/metadata_annotation.rs
- crate_universe/src/rendering.rs
- crate_universe/src/splicing.rs
- crate_universe/src/splicing/splicer.rs
Currently we use the same CrateId type for two contexts: A known crate
name + version, and in an annotation to specify a version requirement
that an annotation applies to.
These are different use-cases, and neither should use String to
represent a the version.
Also, update CrateId to use a `semver::Version` (which is required, not optional).
> Split CrateID CrateNameAndVersionReq

- crate_universe/private/srcs.bzl
- crate_universe/src/api.rs
- crate_universe/src/api/lockfile.rs
- crate_universe/src/context.rs
- crate_universe/src/lib.rs
- crate_universe/src/lockfile.rs
- crate_universe/src/rendering.rs
- crate_universe/src/rendering/template_engine.rs
- crate_universe/test_data/cargo_bazel_lockfile/multi_package-cargo-bazel-lock.json
https://github.com/Calsign/gazelle_rust currently relies on a patch to rules_rust which makes the `Context` struct public.
Instead, supply the information they need via a public API.
All names (and whether we want to hide these structs behind traits and just return `impl Trait`s) are open to discussion.
Fixes #1725
cc @Calsign
> Add public interface to lockfile interospection

- rust/repositories.bzl
There is a bug/typo in `rust_register_toolchains` where `rustfmt_version` would always override `rust_analyzer_version` (default or otherwise specified). This causes problems related to mismatched ABIs when rust-analyzer tries to expand proc macros if one were to use an older-than-default nightly toolchain without specifying a specific `rustfmt_version`. This is because `rust-analyzer` will be set to use the default `rustfmt_version` which is `nightly/2024-02-08`: https://github.com/bazelbuild/rules_rust/blob/8b977b5f7020fc3a3b3bbc318e414269014f126a/rust/private/common.bzl#L36
As a very basic example of what I mean:
```
rust_register_toolchains(
edition = "2021",
versions = [
"nightly/2024-01-31",
],
extra_exec_rustc_flags = ["-A", "async_fn_in_trait"],
)
```
Will result in rust-analyzer …
> Stop rustfmt versioning from overriding rust-analyzer versioning.

- rust/extensions.bzl
- rust/repositories.bzl
Hi there 👋 
I tried using bzlmod with rules_rust, and I encountered an issue with the download of the toolchains.
I applied a "hotfix," but I'm sure it's not the correct approach. Hence, feel free to take over the PR.
```
bazel_dep(name = "rules_rust", version = "0.40.0")
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
edition = "2021",
extra_target_triples = [
"aarch64-apple-ios-sim",
"aarch64-apple-ios",
"aarch64-linux-android",
"x86_64-unknown-linux-gnu",
],
rustfmt_version = "nightly/2024-02-22",
versions = ["nightly/2024-02-22"],
)
crate = use_extension(
"@rules_rust//crate_universe:extension.bzl",
"crate",
)
crate.from_cargo(
name = "crates",
cargo_lockfile = "//:Cargo.lock",
manifests = [
"//:Cargo.toml",
],
)
use_repo(crate, "crates")
```
> bzlmod: fix issue with nightly versions

- rust/private/rust.bzl
- rust/private/utils.bzl
- test/genquery/BUILD.bazel
- test/genquery/bar.rs
- test/genquery/foo.rs
relates to https://github.com/bazelbuild/rules_rust/issues/2522
> Fixed genquery for rust targets

- MODULE.bazel
- crate_universe/extension.bzl
> Mark the bzlmod extension reproducible as appropriate

- crate_universe/extension.bzl
- Resolves https://github.com/bazelbuild/rules_rust/issues/2585
- Fixes the host triple string lookup for CARGO_BAZEL_URLs. 
- Will work on bzlmod bootstrap so we can bootstrap the bzlmod cargo stuff so we have the URLS in a follow up MR
> BUG-FIX: host-triple str for bzl mod

- crate_universe/src/context.rs
- crate_universe/src/context/crate_context.rs
- crate_universe/src/metadata/dependency.rs
- crate_universe/src/metadata/metadata_annotation.rs
- crate_universe/test_data/metadata/aliases/Cargo.lock
- crate_universe/test_data/metadata/aliases/Cargo.toml
- crate_universe/test_data/metadata/aliases/metadata.json
- crate_universe/test_data/metadata/build_scripts/metadata.json
- crate_universe/test_data/metadata/common/metadata.json
- crate_universe/test_data/metadata/crate_combined_features/metadata.json
- crate_universe/test_data/metadata/crate_optional_deps_disabled/metadata.json
- crate_universe/test_data/metadata/crate_optional_deps_disabled_build_dep_enabled/metadata.json
- crate_universe/test_data/metadata/crate_optional_deps_enabled/metadata.json
- crate_universe/test_data/metadata/crate_renamed_optional_deps_disabled/metadata.json
- crate_universe/test_data/metadata/crate_renamed_optional_deps_enabled/metadata.json
- crate_universe/test_data/metadata/crate_types/metadata.json
- crate_universe/test_data/metadata/example_proc_macro_dep/metadata.json
- crate_universe/test_data/metadata/git_repos/metadata.json
- crate_universe/test_data/metadata/has_package_metadata/metadata.json
- crate_universe/test_data/metadata/multi_cfg_dep/metadata.json
- crate_universe/test_data/metadata/multi_kind_proc_macro_dep/metadata.json
- crate_universe/test_data/metadata/no_deps/metadata.json
- crate_universe/test_data/metadata/target_cfg_features/metadata.json
- crate_universe/test_data/metadata/target_features/metadata.json
- crate_universe/test_data/metadata/workspace/metadata.json
- crate_universe/test_data/metadata/workspace_path/metadata.json
This change also updates tests to account for the change in registry reprs in Cargo.lock files. E.g.
```
tracing 0.2.0 (git+https://github.com/tokio-rs/tracing.git?branch=master#1e09e50e8d15580b5929adbade9c782a6833e4a0
```
to
```
git+https://github.com/tokio-rs/tracing.git?branch=master#tracing@0.2.0
```
> Update test metadata for crate_universe

- docs/flatten.md
- docs/rust_repositories.md
- rust/private/rustc.bzl
- rust/toolchain.bzl
- test/unit/debug_info/debug_info_analysis_test.bzl
- test/unit/strip_level/BUILD.bazel
- test/unit/strip_level/strip_level_test_suite.bzl
Attempts to follow the cargo proposal linked below to remove debug info for release builds. Furthermore this should uphold the expected behavior of bazel for cc builds which automatically strips debug symbols for optimized builds.
https://github.com/rust-lang/cargo/issues/4122#issuecomment-1868318860
> feat: Strip debug info from opt builds

- crate_universe/extension.bzl
- examples/bzlmod/hello_world_no_cargo/BUILD.bazel
- examples/bzlmod/hello_world_no_cargo/MODULE.bazel
- examples/bzlmod/hello_world_no_cargo/src/main.rs
This PR contains two changes:
1. Set the default value of `crate.spec` `default_features` to `True` as `WORKSPACE` handles it.
2. Prevent filtering out `default_features` during package json encoding as both truthy and falsy values for booleans are significant.
> Keep default_features parity from bzlmod to workspace

- examples/bzlmod/hello_world/MODULE.bazel.lock
- rust/extensions.bzl
The reproducible attribute was added in Bazel 7.1, so unconditional usage of this breaks earlier versions. This uses `@bazel_features` to detect whether we can safely use this. For more context see https://github.com/bazelbuild/rules_rust/pull/2453#issuecomment-2048115743.
> Fix rust module extension for Bazel pre-7.1

- MODULE.bazel
Otherwise wasm_bindgen with rules_js is unusable.
> Add aspect_rules_js to MODULE.bazel

- MODULE.bazel
- examples/bzlmod/hello_world/MODULE.bazel
- examples/bzlmod/hello_world/MODULE.bazel.lock
- rust/extensions.bzl
See https://github.com/bazelbuild/bazel/discussions/22024 for details.
> Register a default rust toolchain.

- crate_universe/src/lockfile.rs
- crate_universe/src/splicing.rs
- crate_universe/src/splicing/splicer.rs
This adds the following new logging when `CARGO_BAZEL_DEBUG=1` is enabled in the environment when the repository rule runs.
```
cd test/no_std && CARGO_BAZEL_REPIN=1 CARGO_BAZEL_DEBUG=1 bazel sync --only=no_std_crate_index
```
````
...
...
Splice 2024-04-27T16:31:48.249675Z DEBUG write_registry_urls_and_feature_map: cargo_bazel::splicing::splicer: Writing Cargo manifest '/private/var/tmp/_bazel_user/427c86c43c8db37f50959419e7306f4e/external/no_std_crate_index/splicing-workspace/Cargo.toml':
```toml
[dependencies.libc_alloc]
version = "1.0.3"
[lib]
name = "direct_cargo_bazel_deps"
path = ".direct_cargo_bazel_deps.rs"
required-features = []
[package]
edition = "2018"
name = "direct-cargo-bazel-deps"
version = "0.0.1"
[workspace]
members = []
resolver = "2" …
> Added debug logging for spliced manifests to crate_universe

- rust/private/rust.bzl
- rust/settings/BUILD.bazel
- rust/toolchain.bzl
closes https://github.com/bazelbuild/rules_rust/issues/2324
> Remove `incompatible_test_attr_crate_and_srcs_mutually_exclusive`

- BUILD.bazel
- tools/rustfmt/BUILD.bazel
- tools/rustfmt/src/upstream_rustfmt_wrapper.rs
Previously you either needed to go via our bazel-aware wrapper, or write a rule to grab the file from the toolchain.
> Add target for running rustfmt directly

- tools/runfiles/runfiles.rs
Our use case is `runfiles::rlocation!(cache.runfiles, "foo")` but this would also allow `runfiles::rlocation!(Runfiles::create()?, "foo")`
> Allow runfiles object to be an arbitrary expression.

- proto/prost/private/prost.bzl
- proto/protobuf/proto.bzl
- tools/rust_analyzer/lib.rs
At the moment, rust_analyzer's rust-project.json will list the root of a proto crate as, for example: `$HOME/.cache/bazel/_bazel_msta/60654fdd7bbd86377eab8595eb8577e8/execroot/_main/bazel-out/k8-dbg/bin/examples/prost/proto/example_proto.lib.rs`. However, this file does not exist, since it wasn't actually declared as the output of any rule.
With this change, tools/rust-analyzer will actually generate the generated sources.
> Add support for generated sources to rust-analyzer.

- docs/flatten.md
- docs/rust_repositories.md
- rust/repositories.bzl
Modifies the default of `rustfmt_version` so that it uses the first version in the `versions` list. If there are multiple versions given then falls back to the original default of `DEFAULT_NIGHTLY_VERSION`.
We tripped over this where supply a single Rust version (non-nightly), but started using nightly features in `rustfmt.toml` and could no longer format directly with `cargo fmt`. This helped align the versions of both toolchains.
> fix: default rustfmt version to supplied rust version

- tools/rust_analyzer/lib.rs
Fixes https://github.com/bazelbuild/rules_rust/issues/2615 and https://github.com/bazelbuild/rules_rust/issues/2438
> Use repo-mapping-aware runfiles API in rust-analyzer

- cargo/private/cargo_build_script.bzl
- cargo/private/cargo_build_script_wrapper.bzl
- crate_universe/src/rendering.rs
- crate_universe/src/utils/starlark.rs
- docs/cargo.md
- docs/flatten.md
This PR shortens the path to the build script (potentially significantly), which helps with long-path issues on Windows.
This change is motivated by the crate `tree-sitter-embedded-template`, which has a too long path to the compiled build script otherwise, and which then fails to build on Windows in a `bzlmod` setting.
Fixes https://github.com/bazelbuild/rules_rust/issues/2520.
The cargo build script name was used to automatically derive the cargo package name, this now went into a separate override parameter that is generated by the crate-universe tooling.
There's never two build scripts in a single crate, so I don't see how having a single build script target with a single name would be a problem.
> crate_universe: Don't include crate name in build script path.

- rust/private/rustc.bzl
- test/cc_shared_library/BUILD.bazel
- test/cc_shared_library/linked_against_shared.rs
- test/cc_shared_library/runfiles_contains_shared.sh
Right now the runfiles directory only contains "data" that is attached to a rust_binary() or one of its dependencies. This is inconsistent with cc_binary() and go_binary(), which also include an `_solib_*/` directory containing shared library dependencies.
When doing a plain 'bazel run' against the resulting executable, this is not a noticeable issue. The reason being that the runtime dynamic linker will use `${execroot}/_solib_*`. However, it does become a problem when `pkg_tar(include_runfiles = True)` is used to construct an archive of the binary so that it can be placed in a container image.
This change extends the runfiles gathering logic to merge all LibraryToLink.dynamic_library files in there as well.
> Ensure dynamic library dependencies end up in the runfiles directory

- .bazelci/presubmit.yml
- MODULE.bazel
- WORKSPACE.bazel
- examples/WORKSPACE.bazel
- rust/private/extensions.bzl
bazel_ci_rules@1.0.0 module has been published to the BCR, see https://github.com/bazelbuild/bazel-central-registry/pull/2058
This use it has a bazel_dep instead of a http_archive
> use bazel_ci_rules bazel_dep instead of http_archive

- rust/private/toolchain_utils.bzl
- rust/toolchain/BUILD.bazel
- tools/rustfmt/BUILD.bazel
The toolchain_files() and current_rust_toolchain() rules return files for the current 'exec' platform. This is perfecly reasonable if you want to use these tools as part of ctx.actions.run(). But if you want to use these as part of 'data = []' (runfiles), they must be built for the target.
Fixes: https://github.com/bazelbuild/rules_rust/issues/2684
> Depend on a copy of rustfmt for the target

- cargo/cargo_build_script_runner/lib.rs
The `cargo_build_script_runner` currently converts the keys from `cargo:KEY=VALUE` metadata build script output lines into uppercase. This is not completely correct, however, because Cargo converts those keys to uppercase AND replaces dashes with underscores (effectively doing a conversion to SCREAMING_SNAKE_CASE).
To verify that Cargo is indeed doing the dash-to-underscore conversion, have a look at https://github.com/rust-lang/cargo/blob/10b7d384352f6d9a39f609de44476f815fc792a2/src/cargo/core/compiler/custom_build.rs#L46, which is the code responsible for building the `DEP_{crate-name}_{metadata-key}` env variables in Cargo. The code is
```rust
cmd.env(
&format!("DEP_{}_{}", super::envify(&name), super::envify(key)),
value,
);
```
where `super::envify()` is defined as
```rust
fn …
```
> [Bugfix] Convert metadata keys to screaming snake case instead of screaming kebab case in `cargo_build_script_runner`

- rust/private/rust_analyzer.bzl
- test/rust_analyzer/generated_srcs_test/BUILD.bazel
- test/rust_analyzer/generated_srcs_test/lib.rs
- test/rust_analyzer/generated_srcs_test/rust_project_json_test.rs
- test/rust_analyzer/merging_crates_test/rust_project_json_test.rs
- test/rust_analyzer/static_and_shared_lib_test/rust_project_json_test.rs
- tools/rust_analyzer/rust_project.rs
This change updates the `rust_analyzer_aspect` to attempt to match generated crate root sources to `srcs` inputs and use the the path of the source file in place of the generated path. The generated path is then added to `sources.include_dirs` for compatibility. The impact of this can be seen in the following diff of the `@rules_rust//:rust-project.json` file:
```diff
--- rust-project.old.json	2024-06-28 09:00:51
+++ rust-project.json	2024-06-28 09:04:43
@@ -821,10 +821,16 @@
},
{
"display_name": "libgensrc_with_crate_root",
-            "root_module": "/private/var/tmp/_bazel_user/76282c66b0dfe3c5cb9a230bdc913a52/execroot/rules_rust/bazel-out/darwin_arm64-fastbuild/bin/test/generated_inputs/lib.rs",
+            "root_module": "test/generated_inputs/lib.rs",
"edition": "2018",
"deps": …
```
> Updated rust-analyzer to use repo vs generated files as crate roots

- crate_universe/src/utils/starlark/label.rs
According to the [migration guide](https://bazel.build/external/migration), `WORKSPACE.bazel` is no longer required with Bazel 6.3 or later. This updates `crate_universe` to respect that, allowing `MODULE.bazel` to be the root marker of a workspace, without requiring a `WORKSPACE` or `WORKSPACE.bazel`.
Happy to iterate on this.
> crate-universe allows workspaces with MODULE.bazel only

- bindgen/private/bindgen.bzl
This is needed when using toolchains that use custom include directories.
> Update bindgen.bzl to use toolchain system include directories as well

- docs/defs.md
- docs/flatten.md
- rust/private/rust.bzl
- test/rust_test_suite_shared/BUILD.bazel
- test/rust_test_suite_shared/src/lib.rs
- test/rust_test_suite_shared/tests/helpers/mod.rs
- test/rust_test_suite_shared/tests/integrated_test_a.rs
- test/rust_test_suite_shared/tests/integrated_test_b.rs
Currently, `rust_test_suite` is not capable of supporting integration tests with shared modules. A very basic example is:
```
[crate]/
src/
lib.rs
tests/
integration_test_a.rs
integration_test_b.rs
util/
mod.rs
```
With `integration_test_a.rs` and `integration_test_b.rs` importing code from `util`.
This PR adds a `shared_srcs` argument to `rust_test_suite`. That way, we can finally compile and run those tests with:
```python
rust_test_suite(
name = "integrated_tests_suite",
srcs = glob(["tests/**"]),
shared_srcs = ["tests/util/mod.rs"],
deps = [":example_dep"],
)
```
> Add support for shared test-only modules

- examples/bzlmod/all_deps_vendor/MODULE.bazel
- examples/bzlmod/compile_opt/MODULE.bazel
- examples/bzlmod/cross_compile/MODULE.bazel
- examples/bzlmod/ffi/MODULE.bazel
- examples/bzlmod/proto/MODULE.bazel
Otherwise these test a released rules_rust not an in-repo one, and breaking changes will always fail CI.
> Add missing local_path_overrides in examples

- bindgen/3rdparty/BUILD.bazel
I don't know how this ever worked before. I've picked the version that happens to be in the lockfile at the moment.
Fixes #2752
> Add version to bindgen dep

- proto/prost/private/prost.bzl
The deprecated attribute was passing a `Target` where the `proto_toolchain` is passing a `FilesToRun` provider. This ensures the two are consistent.
> Ensure proto compiler attribute is consistent in prost_toolchain

- docs/flatten.md
- docs/rust_repositories.md
- rust/extensions.bzl
- rust/private/repository_utils.bzl
- rust/repositories.bzl
Most notably in places where `version` and `iso_date` were used, the `versions` parameter should be used instead. There have long since prints guiding folks to use `versions` over the previous two.
> Remove deprecated variables from `repositories.bzl` macros

- docs/defs.md
- docs/flatten.md
- rust/private/rust.bzl
- test/rust/src/lib.rs
- test/unit/linkstamps/linkstamps_test.bzl
- test/unit/rust_test_outputs_are_in_subdirectory/BUILD.bazel
- test/unit/rust_test_outputs_are_in_subdirectory/foo.rs
- test/unit/rust_test_outputs_are_in_subdirectory/rust_test_outputs.bzl
This reverts commit b4ccc97bbe4e6c2cb264efe075cc7b55126f9607.
That commit makes a behavior change, and thus should have been protected by a feature flag. This will be done in a future PR.
> Revert "Build rust_test targets using a crate name different from the underlying lib"

- docs/rust_analyzer.md
- docs/rust_analyzer.vm
Tracking Issue: https://github.com/bazelbuild/rules_rust/issues/2814
The command in doc looks outdated and I'm getting
```
❯ bazel build --@rules_rust//:output_diagnostics=true --output_groups=+rust_lib_rustc_output,+rust_metadata_rustc_output //hellow_world
WARNING: Target pattern parsing failed.
ERROR: Skipping '@rules_rust//:output_diagnostics': no such target '@@rules_rust~//:output_diagnostics': target 'output_diagnostics' not declared in package '' defined by /private/var/tmp/_bazel_xxx/c947415ff64a19538545e009b2e6df63/external/rules_rust~/BUILD.bazel
ERROR: @rules_rust//:output_diagnostics :: Error loading option @rules_rust//:output_diagnostics: no such target '@@rules_rust~//:output_diagnostics': target 'output_diagnostics' not declared in package '' defined by …
```
> Doc: update outdated parameter `output_diagnostics`

- .bazelci/presubmit.yml
- examples/musl_cross_compiling/WORKSPACE.bazel
- examples/musl_cross_compiling/hello_linux_musl_test.sh
- rust/repositories.bzl
This allows for selecting non-default toolchains where the exec triple matches the target triple.
This is tested by enabling the musl static linking tests on the Linux host platform. Before this PR, the test would fail because the -gnu rather than -musl rust toolchain would end up getting selected. Now, everything works.
Fixes #2726
> Consistently thread extra target constraints around

- rust/private/rustdoc_test.bzl
- test/unit/rustdoc/procmacro_in_rustdoc.rs
- test/unit/rustdoc/rustdoc_unit_test.bzl
Without stripping the prefix, rustdoc can not find the proc macro shared library.
It's not entirely clear to me why `//test/unit/rustdoc:lib_with_proc_macro` passes without this. When I run `bazel test //test/unit/rustdoc:rustdoc_test_suite     --subcommands` I don't see any "action 'Generating Rustdoc test runner for.." lines so perhaps that path is not tested?
> rustdoc_test: Apply prefix stripping to proc_macro dependencies.

- util/process_wrapper/main.rs
When debugging an action it can be incredibly helpful to have the exact command used to invoke `rustc`. This PR updates the rustc process wrapper to emit debug logs when the `RULES_RUST_PROCESS_WRAPPER_DEBUG` environment variable is enabled.
Example:
```bash
bazel build //test/... --action_env=RULES_RUST_PROCESS_WRAPPER_DEBUG=1
```
```
INFO: From Generating Rustdoc for @//test/unit/rustdoc:lib_with_proc_macro:
Command: Command {
program: "bazel-out/darwin_arm64-fastbuild/bin/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/rust_toolchain/bin/rustdoc",
args: [
"bazel-out/darwin_arm64-fastbuild/bin/external/rust_darwin_aarch64__aarch64-apple-darwin__stable_tools/rust_toolchain/bin/rustdoc",
"test/unit/rustdoc/rustdoc_lib.rs",
"--crate-name=lib_with_proc_macro", …
```
> Support emitting debug logs in rules_rust process wrapper.

- crate_universe/src/api/lockfile.rs
- crate_universe/src/config.rs
- crate_universe/src/splicing.rs
- crate_universe/src/splicing/crate_index_lookup.rs
- crate_universe/src/splicing/splicer.rs
- crate_universe/tests/cargo_integration_test.rs
- examples/hello_runfiles/hello_runfiles.rs
- examples/proto/helloworld/helloworld_test.rs
- test/bzl_version/bzl_version_test.rs
- test/bzlmod_repo_mapping/module_b/lib.rs
- test/process_wrapper/rustc_quit_on_rmeta.rs
- test/process_wrapper_bootstrap/bootstrap_process_wrapper_test.rs
- test/rust/src/greeter.rs
- tools/runfiles/runfiles.rs
- tools/rust_analyzer/lib.rs
- tools/rustfmt/src/lib.rs
- tools/upstream_wrapper/src/main.rs
closes https://github.com/bazelbuild/rules_rust/issues/2653
> Update `runfiles::rlocation!` to return `Option` instead of panicing

- cargo/private/cargo_build_script.bzl
- test/cargo_build_script/compile_data/BUILD.bazel
- test/cargo_build_script/compile_data/build.rs
- test/cargo_build_script/compile_data/data.txt
- test/cargo_build_script/compile_data/test.rs
This way any outputs that the build script may refer to in flags it emits can be referenced without needing to also explicitly pass the data target to the `compile_data` attribute of it's consumer.
> Propagate `cargo_build_script.data` to `Rustc` compile actions

- crate_universe/private/crates_vendor.bzl
Previously the environment variable was discarded. Now users can see debug info about how crates are being rendered.
> Allow `crates_vendor` to read the `CARGO_BAZEL_DEBUG` env var

- .bazelci/presubmit.yml
- crate_universe/src/utils.rs
> crate_universe: Don't preform path translation on `out_dir`

- rust/extensions.bzl
> Allow bzlmod users to inhibit toolchain registration

- docs/src/flatten.md
- docs/src/rust_wasm_bindgen.md
- rust/platform/platform.bzl
- rust/platform/triple_mappings.bzl
- rust/private/dummy_cc_toolchain/BUILD.bazel
- rust/private/dummy_cc_toolchain/dummy_cc_toolchain.bzl
- rust/private/rustc.bzl
- rust/private/utils.bzl
- rust/repositories.bzl
- util/fetch_shas/fetch_shas.py
- util/fetch_shas/fetch_shas_TARGETS.txt
- wasm_bindgen/private/transitions.bzl
- wasm_bindgen/private/wasm_bindgen.bzl
This PR adds support for `wasm64-unknown-unknown` although there are no prebuilt `wasm64-unknown-unknown` rustc toolchains. Compiling for `wasm64` will be left up to anyone using this target triple until we get T2 support for wasm64.
> Add wasm64 support.

- proto/prost/private/protoc_wrapper.rs
- proto/prost/private/tests/keywords/BUILD.bazel
- proto/prost/private/tests/keywords/imported_keyword.proto
- proto/prost/private/tests/keywords/mod_named_mod.proto
- proto/prost/private/tests/keywords/mod_named_mod_test.rs
Fixes Prost: Handling of reserved keywords in package names is broken #2884
Added escaping on Rust keywords in proto package names
> Fix keyword handling in prost wrapper

- crate_universe/src/utils/starlark/label.rs
- util/label/label.rs
Bazel 8 uses `+` as the separator for segments of canonical repo names, whereas Bazel 7 uses `~` or `+` depending on the value of `--incompatible_use_plus_in_repo_names`.
> Allow `+` in repo names

- tools/action_args/BUILD.bazel
- tools/action_args/action_args.rs
This change introduces the `action_args` crate which is something I feel I keep writing in various repos now. It's original design is to make it easier to pass args to built binaries. E.g.
```rust
use action_args;
use clap::Parser;
use runfiles::{rlocation, Runfiles};
#[command(version, about, long_about = None)]
struct ClapArgs {}
fn main() {
let args = {
let runfiles = Runfiles::create().unwrap();
let var = std::env::var("ARGS_FILE").unwrap();
let runfile = rlocation!(runfiles, var).unwrap();
let text = std::fs::read_to_string(runfile).unwrap();
let argv = action_args::parse_args(text);
ClapArgs::parse_from(std::env::args().take(1).chain(argv))
};
// ...
// ...
// ...
}
```
This utility will likely be unnecessary should https://github.com/bazelbuild/bazel/issues/16076 ever be …
> Added utility for parsing action Args param files

- crate_universe/private/crate.bzl
- docs/src/crate_universe.md
Updates the documentation to match the implementation: https://github.com/bazelbuild/rules_rust/blob/144d34fdaa3c3c5fe27a9666b760aa31aa9155a5/crate_universe/src/context/crate_context.rs#L65-L74
> Fix `override_targets` keys in docs

- cargo/private/cargo_build_script.bzl
Also generalize `_pwd_flags`. Flags can use both, " " and "=" as argument separators.
> Use absolute path with "-fsanitize-ignorelist"

- cargo/private/cargo_build_script.bzl
This was a miss from https://github.com/bazelbuild/rules_rust/pull/2891
> Add missing inputs to CargoBuildScriptRun action

- cargo/private/BUILD.bazel
- cargo/private/cargo_build_script.bzl
- cargo/private/copy_file.rs
After https://github.com/bazelbuild/rules_rust/pull/2826 was merged, I started seeing flaky builds on Windows related to build script executables (https://github.com/bazelbuild/rules_rust/pull/2891#issuecomment-2363985009). This appears to be related to https://github.com/bazelbuild/bazel/issues/21747 so to avoid the issue, this change ensures that Windows build script executables are copied instead of symlinked.
> Avoid builds-without-the-bytes bug on Windows

- cargo/private/cargo_build_script.bzl
`is_absolute` was lost for "=" case in #2911
Fixes  #2917
> Restore lost "is_absolute"

- MODULE.bazel
- cargo/private/cargo_build_script.bzl
- version.bzl
Revert "Restore lost "is_absolute" (#2922)"
This reverts commit 2a85e13c74239d2a0d0c47a37f10a4c9739fa5e6.
Revert "Use absolute path with "-fsanitize-ignorelist" (#2911)"
This reverts commit 9594fa70b5b6f556a7b4f57ca0ac7c48149bf280.
> Revert #2911 and #2922

- rust/private/rustc.bzl
- test/toolchain/toolchain_test.bzl
This allows target specific flags to override toolchain
specific flags, e.g: to disable LTO on examples.
> Add target specific rustc_flags last to the command line

- docs/rust_proto.vm
- docs/src/rust_proto.md
Commit c080d7bfa12b53e011e7065a8f242d90311fab81 moved the location of `BUILD.bazel`. This PR adjusts sources to changes.
> Update `BUILD.bazel` location

- cargo/private/cargo_build_script.bzl
- test/cargo_build_script/cc_args_and_env/BUILD.bazel
- test/cargo_build_script/cc_args_and_env/cc_args_and_env_test.bzl
This is trivial copy/paste implementation, to
minimize regression probability.
Previously it was combined with refactoring, but
introduced regression and was reverted #2911.
This time I split refactoring into follow up PR.
> cargo_build_script: Add support for `-fsanitize-ignorelist=`

- test/cargo_build_script/cc_args_and_env/BUILD.bazel
- test/cargo_build_script/cc_args_and_env/cc_args_and_env_test.bzl
#2931 added tests for _pwd_flags, however 
the test as-is passes with #2911 and #2922,
which still caused problems and reverted.
Here I introduce a test case for likely
unfixed in reverted #2925.
The test needs strictter check for cflags. As-ls
`flag in cflags` is a just substring search and
very weak test for abs path.
For #2917
> cargo_build_script: Add regression test for revert #2925

- docs/src/flatten.md
- docs/src/rust_proto.md
- proto/prost/private/BUILD.bazel
- proto/prost/private/prost.bzl
- proto/prost/private/protoc_wrapper.rs
- proto/prost/private/tests/package_imports/package_importer_test.rs
- proto/prost/private/tests/sanitized_modules/sanitized_modules_test.rs
- proto/prost/private/tests/transitive_dependencies/BUILD.bazel
- proto/prost/private/tests/transitive_dependencies/a_test.rs
- proto/prost/private/tests/transitive_dependencies/b/b_test.rs
- proto/prost/private/tests/transitive_dependencies/b/c/c_test.rs
- proto/prost/private/tests/transitive_dependencies/transition.bzl
- proto/prost/private/tests/transitive_dependencies/transitive_deps_test.rs
- proto/prost/private/tests/well_known_types/well_known_types_test.rs
This PR makes two changes:
1. It removes the duplicately generated code in the prost `lib.rs`.
2. It allows opting into transitively including all of the proto deps.
Previously there was a bug where we generated the same code at every proto package level. This created separate Rust types for each module which made it easy to accidentally import an incompatible type.
Before:
```rust
// @generated
pub mod b_ar {
pub mod b_az {
pub mod qaz {
pub mod qu_x {
// @generated
// This file is @generated by prost-build.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Bar {
#[prost(string, tag = "1")]
pub name: ::prost::alloc::string::String,
#[prost(message, optional, tag = "2")]
pub foo: ::core::option::Option< …
```
> [Prost] Remove extra generated modules and opt-in to transitively including deps

- tools/rust_analyzer/aquery.rs
Hi, if I'm not mistaken, in Bazel `deps(a)+deps(b)` is equivalent to `deps(a+b)`. The latter is more efficient because it doesn't have to deduplicate common dependencies between a and b. This performance issue has been triggered in our configuration, as we track roughly 700 targets and 1600 transitive dependencies in our monorepo. 
Running `aquery` with the original implementation takes 15 seconds on my machine while the implementation proposed in this PR takes 1.5 seconds.
> gen_rust_project: optimize aquery with many targets

- crate_universe/extension.bzl
This PR is follow up to #2453 and marks the `crate` extension as `os_dependent` and `arch_dependent`.
For `crate.from_cargo`, the extension specifies reproducibility via the `reproducible` attribute of `extension_metadata` which makes Bazel skip the extension when writing the lockfile. 
But in the case of `crate.from_specs`, the current implementation marks the extension as non reproducible since the crates will not be backed by a lockfile.
And because the `crate` module extension depends on `rust_host_tools` (which are os / arch dependent), the entry in the lockfile for the module extension includes the checksum of the `rustc` and `cargo` binaries for whatever host it was resolved for.
This makes the bazel lock file platform dependent in that case.
This PR will result in a new os/arch …
> Make crate module extension os and arch dependent

- rust/private/rustc.bzl
Very quick one. Probably a left over from a merge conflict.
> Remove duplicate build metadata depset

- bindgen/private/bindgen.bzl
- cargo/private/cargo_build_script.bzl
- examples/hello_world/src/main.rs
- rust/private/rustc.bzl
- test/linker_inputs_propagation/BUILD.bazel
- test/linker_inputs_propagation/bar_uses_shared_foo_for_rust.rs
- test/linker_inputs_propagation/main_uses_foo.rs
- test/unit/linker_inputs_propagation/linker_inputs_propagation_test.bzl
Previously we were adding these early on in the link args.
This was a bug - if some transitive dep foo has a linkopt of `-lbar`, the `-lbar` needs to be later in the link args list than `-lfoo`.
Rather than arbitrarily adding them early on and hoping things work, this adds the args for each library just after we add a dependency on that library.
> Add per-target link flags in the right place

- rust/private/rust.bzl
- test/renamed_deps/BUILD.bazel
Inline tests compile the same set of source files as the original crate.
The set of aliases required will be the same or occasionally a superset.
We shouldn't make users repeat them across targets.
> rust_test(crate=foo) inherits foo.aliases

- MODULE.bazel
- WORKSPACE.bazel
- cargo/private/cargo_build_script.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/private/utils.bzl
- test/cargo_build_script/tools_exec/BUILD.bazel
- test/cargo_build_script/tools_exec/build.rs
- test/foreign_toolchain_make_variables/BUILD.bazel
- test/foreign_toolchain_make_variables/build.rs
- test/foreign_toolchain_make_variables/toolchain.bzl
Previously if a target depended on a toolchain which exposed `$(FOO)`, we would automatically set `$FOO` as an env var.
This was not correct. Toolchains should make Make variables available for expansion in env vars, but should not automatically promote them to action env.
If you want `$FOO` set, you should set `$FOO=$(FOO)` in the appropriate env var attribute.
> Make toolchain vars available but don't automatically set them

- cargo/cargo_build_script_runner/bin.rs
- cargo/private/cargo_build_script.bzl
- cargo/settings/BUILD.bazel
This change introduces the `--@rules_rust//cargo/settings:debug_std_streams_output_group` flag which can be used to enable the `streams` output group on `cargo_build_script` targets. For greater reproducibility, the flag is defaulted to `false`.
closes https://github.com/bazelbuild/rules_rust/issues/2974
> Made `cargo_build_script` `streams` output group optional.

- crate_universe/private/crate.bzl
Fixes #2940 
This changes fixes `crate.select`, used for annotations, for list flags.
A [recent fix](https://github.com/bazelbuild/rules_rust/pull/2394) for bzlmod introduced a remapping of `annotation` labels to lists. This did not originally recurse into `select` structs. This fixes that issue.
Should I create one for `_stringify_label` too?
> Fix annotations' crate.select for lists

- rust/private/clippy.bzl
- rust/private/rustc.bzl
- rust/settings/BUILD.bazel
According to the Bazel documentation, this option is deprecated. config.string_list(repeatable = True) should be used instead.
> Stop using config.string(allow_multiple = True)

- tools/workspace_status/BUILD.bazel
- tools/workspace_status/workspace_status.rs
This change introduces a small utility for parsing workspace status stamp files. I found similar snippets throughout projects I work on and thought consolidation within `rules_rust` would be good. An example usage can be seen here:
```rust
use workspace_status::parse_workspace_status_stamps;
fn main() {
let stable_status = std::fs::read_to_string("bazel-out/stable-status.txt").unwrap();
let volatile_status = std::fs::read_to_string("bazel-out/volatile-status.txt").unwrap();
let stamps = parse_workspace_status_stamps(&stable_status)
.chain(parse_workspace_status_stamps(&stable_status))
.flatten()
.collect::<BTreeMap<_, _>>();
// ...
// ...
// ...
}
```
> Added utility library for parsing workspace status stamps.

- MODULE.bazel
- rust/extensions.bzl
- version.bzl
I'm not going to bother adding a new test for this as Bazel 8 is just around the corner and Bazel 6 is about to be dropped.
> Fix bzlmod support for bazel 6

- docs/src/flatten.md
- docs/src/rust_doc.md
- rust/private/rustdoc_test.bzl
- test/unit/rustdoc/rustdoc_unit_test.bzl
This allows representing doctests that
depend on proc macros their crate do not depend on.
> Add proc_macro_deps for rust_doc_test

- rust/extensions.bzl
Currently, this attribute can be either a dict or a list:
https://github.com/bazelbuild/rules_rust/blob/d383a1aef9865e59172af6c63f29c96fed19b04a/rust/repositories.bzl#L152
Resolved here:
https://github.com/bazelbuild/rules_rust/blob/d383a1aef9865e59172af6c63f29c96fed19b04a/rust/repositories.bzl#L1047
This adds `bzlmod` parity to that feature.
> feat: add extra_rustc_flags_triples

- crate_universe/BUILD.bazel
- examples/cargo_manifest_dir/external_crate/BUILD.bazel
- examples/crate_universe/WORKSPACE.bazel
- examples/flag_locations/BUILD.bazel
- rust/private/rustc.bzl
- rust/settings/BUILD.bazel
- rust/toolchain.bzl
- test/build_env/BUILD.bazel
> provide flag to exclude data at compile time

- .bazelci/presubmit.yml
- docs/rust_analyzer.vm
- docs/rust_clippy.vm
- docs/rust_fmt.vm
- docs/src/flatten.md
- docs/src/rust.md
- docs/src/rust_analyzer.md
- docs/src/rust_clippy.md
- docs/src/rust_fmt.md
- rust/private/clippy.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc.bzl
- rust/private/rustfmt.bzl
- rust/toolchain.bzl
- test/clippy/clippy_failure_test.sh
- test/extra_exec_rustc_flags/BUILD.bazel
- test/extra_exec_rustc_flags/defs.bzl
- test/no_std/BUILD.bazel
- test/rustfmt/rustfmt_failure_test.sh
- test/toolchain/toolchain_test.bzl
- test/unit/clippy/clippy_test.bzl
- test/unit/consistent_crate_name/with_modified_crate_name.bzl
- test/unit/extra_rustc_flags/extra_rustc_flags_test.bzl
- test/unit/force_all_deps_direct/generator.bzl
- test/unit/per_crate_rustc_flag/per_crate_rustc_flag_test.bzl
- test/unit/pipelined_compilation/wrap.bzl
- test/unit/rustdoc/rustdoc_unit_test.bzl
- tools/rustfmt/BUILD.bazel
carry-over from https://github.com/bazelbuild/rules_rust/pull/2870
> Migrate all settings labels from aliases to using settings package

- docs/src/rust_wasm_bindgen_rules_js.md
- extensions/wasm_bindgen/private/wasm_bindgen.bzl
- extensions/wasm_bindgen/rules_js/defs.bzl
- extensions/wasm_bindgen/rules_nodejs/defs.bzl
This is useful for targets which are gated behind `target_compatible_with = ["@platforms//os:wasm32"]` but developers still want them to analyzed by rust-analyzer.
> Allow rust_wasm_bindgen rules to re-expose rust-analyzer providers

- extensions/prost/private/prost.bzl
- rust/private/providers.bzl
- rust/private/rust_analyzer.bzl
This patch adds an `id` to RustAnalyzerInfo, and replace all the recursive RustAnalyzerInfos with the respective crate `id`s.
This fixes RustAnalyzerInfos becoming exponentially expensive to build in the presence of aliases.
---
Before this patch, `RustAnalyzerInfo.deps` contains the RustAnalyzerInfo of the target crate's deps, and so on recursively.
This forms a graph of Infos where there is one Info per target, but multiple paths from one target to another.
e.g. these could all point to `bar`: `foo.deps[0] == foo.deps[1].deps[0] == foo.aliases[0]`.
If we walk `foo` as a tree, we will see `bar` multiple times. Two operations that do this are `print(info)` and `{info: 42}` which hashes the object. As the graph grows, the number of paths grows combinatorically.
`RustAnalyzerInfo.aliases` …
> rust_analyzer: don't build a tree of RustAnalyzerInfos

- .github/workflows/release.yaml
This avoids the following error
```
The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15. For more details, see https://github.com/actions/runner-images/issues/10721
```
> Fix release workflow on macos

- .github/workflows/release.yaml
This was a miss from https://github.com/bazelbuild/rules_rust/pull/3007 and https://github.com/bazelbuild/rules_rust/pull/3037
> Fix release notes generation for extensions

- cargo/private/cargo_build_script.bzl
This PR adds a new boolean attribute to `cargo_build_script` rules called `use_default_shell_env` which is set to `True` by default.
The goal here is to make Cargo Build Scripts more hermetic. If you set `use_default_shell_env` to false, local environment variables like `PATH` should not get set for build scripts, preventing them from relying on tools not provided by Bazel.
Note: I considered adding a global `use_default_shell_env_for_cargo_build_scripts` setting, but couldn't figure out a good way to make the global setting work with this attribute. e.g. if you disable `use_default_shell_env` globally, ideally you still have a way to enable it for an individual crate, but I couldn't figure out how to set the defaults for the global setting and this local attr to get that to work
Related …
> cargo: Allow disabling the `default_shell_env` for build scripts

- crate_universe/private/crates_vendor.bzl
Slight tweak to the logic in https://github.com/bazelbuild/rules_rust/pull/2862 (cc: @UebelAndre)
My `$PATH` variable has spaces in it and I hit an error like
```
env: Support/JetBrains/Toolbox/scripts:/Users/ryanpbrewster/.bin:/Users/ryanpbrewster/config/bin:/Users/ryanpbrewster/.local/bin:/Applications/Visual: No such file or directory                                                                     
```
If I manually modify `bazel-bin/rust/crates_vendor.sh` to modify
```
exec env - \
${_ENVIRON[@]} \
```
into
```
exec env - \
"${_ENVIRON[@]}" \
```
it starts working.
> Quote environ when injecting into crates vendor wrapper

- extensions/wasm_bindgen/private/wasm_bindgen.bzl
- extensions/wasm_bindgen/test/BUILD.bazel
This allows targets gated by `target_compatible_with = ["@platforms//cpu:wasm32"]` to have clippy and rustfmt run on them as well as include those targets in rust-analyzer outputs.
> Forward clippy, rustfmt, and rust-analyzer through wasm_bindgen

- cargo/private/cargo_utils.bzl
- rust/private/compat.bzl
- rust/private/rustc.bzl
- rust/private/utils.bzl
- rust/repositories.bzl
> Use `abs` from utils instead of the global

- docs/src/rust_prost.md
- extensions/prost/defs.bzl
- extensions/prost/private/prost.bzl
- extensions/prost/private/prost_transform.bzl
- extensions/prost/private/protoc_wrapper.rs
- extensions/prost/private/tests/transform/BUILD.bazel
- extensions/prost/private/tests/transform/a.proto
- extensions/prost/private/tests/transform/a_src.rs
- extensions/prost/private/tests/transform/a_test.rs
- extensions/prost/private/tests/transform/b/BUILD.bazel
- extensions/prost/private/tests/transform/b/b.proto
- extensions/prost/private/tests/transform/b/b_src.rs
- extensions/prost/private/tests/transform/b/b_test.rs
- extensions/prost/private/tests/transform/b/c/BUILD.bazel
- extensions/prost/private/tests/transform/b/c/c.proto
- extensions/prost/private/tests/transform/b/c/c_test.rs
- extensions/prost/private/tests/transform/b/greeting.rs
This new rule is to support granular modifications to existing `proto_library` targets without adding duplicate actions to the build graph depending on what `rust_prost_library` target was consumed.
closes https://github.com/bazelbuild/rules_rust/issues/2045
> Added `rust_prost_transform` rule for modifying granular proto_library

- crate_universe/src/metadata/workspace_discoverer.rs
This is a reasonably common convention
> Ignore .bazel symlinks as well as bazel- symlinks

- extensions/prost/private/prost.bzl
- rust/private/providers.bzl
- rust/private/rust_analyzer.bzl
This reverts commit 443b089ca6bd38a5df9d3d7056669b905b39ea30 (https://github.com/bazelbuild/rules_rust/pull/3028).
> Revert "rust_analyzer: don't build a tree of RustAnalyzerInfos (#3028)"

- docs/src/rust.md
- rust/private/lto.bzl
- rust/private/rustc.bzl
- rust/settings/BUILD.bazel
- rust/toolchain.bzl
- test/unit/lto/BUILD.bazel
- test/unit/lto/lto_test_suite.bzl
Fixes https://github.com/bazelbuild/rules_rust/issues/3045
This PR adds a new build setting `//rust/settings:lto=(off|thin|fat)` which changes how we specify the following flags:
* [`lto`](https://doc.rust-lang.org/rustc/codegen-options/index.html#lto)
* [`embed-bitcode`](https://doc.rust-lang.org/rustc/codegen-options/index.html#embed-bitcode)
* [`linker-plugin-lto`](https://doc.rust-lang.org/rustc/codegen-options/index.html#linker-plugin-lto)
The way we invoke the flags was based on how Cargo does it today ([code](https://github.com/rust-lang/cargo/blob/769f622e12db0001431d8ae36d1093fb8727c5d9/src/cargo/core/compiler/lto.rs#L4)) and based on suggestions from the [Rust docs](https://doc.rust-lang.org/rustc/codegen-options/index.html#embed-bitcode).
When LTO is not enabled, we will …
> feat: Add `//rust/settings:lto`

- crate_universe/src/metadata/cargo_tree_resolver.rs
- crate_universe/tests/cargo_integration_test.rs
The cargo_tree_resolver discovers dependencies by executing `cargo tree` for different host and target triples. This procedure breaks when cargo successfully but incorrectly caches rustc info. Incorrect cache hit may happen because cache key does not take into account HOST_TRIPLE env variable used by `rules_rust` to force rustc to report it's built for different host.
The caching may happen if one has target/ directory in repo, or it was created through running some commands outside of bazel.
- After recent fixes to support properly bzlmod
(https://github.com/bazelbuild/rules_rust/pull/3034) noticed issues under windows when building bazel-lsp: https://github.com/cameron-martin/bazel-lsp/issues/92
- Cargo may cache rustc info in target/.rustc_info.json : …
> Do not cache rustc info in deps resolver

- .bazelci/presubmit.yml
- examples/crate_universe_local_path/BUILD.bazel
- examples/crate_universe_local_path/vendor_edit_test.sh
This tests that the repository rules are properly invalidated when patched Cargo.toml files are edited.
> Add test for editing patch Cargo.toml files

- cargo/private/cargo_build_script.bzl
- extensions/bindgen/private/bindgen.bzl
- extensions/protobuf/proto.bzl
- rust/private/clippy.bzl
- rust/private/rust.bzl
- rust/private/rustdoc.bzl
- rust/private/rustdoc_test.bzl
- rust/toolchain.bzl
- test/unit/consistent_crate_name/with_modified_crate_name.bzl
- test/unit/force_all_deps_direct/generator.bzl
- test/unit/pipelined_compilation/wrap.bzl
CC toolchains are gathered from the line:
```
toolchains = use_cc_toolchains(),
```
Keep toolchain usage of _cc_toolchain with a TODO to remove it.
See #3115 for details.
> Remove the unused implicit attribute `_cc_toolchains`.

- docs/src/rust_settings.md
- rust/private/rustc.bzl
- rust/private/rustc_resource_set.bzl
- rust/settings/BUILD.bazel
- rust/settings/settings.bzl
- rust/toolchain.bzl
- test/unit/codegen_units/BUILD.bazel
- test/unit/codegen_units/codegen_units_test_suite.bzl
closes https://github.com/bazelbuild/rules_rust/issues/3008
> Added `codegen_units` flag for setting `Rustc` resource sets

- rust/toolchain.bzl
Remove `toolchain.crosstool_files and _cc_toolchains`.
Fixes #3115.
> Remove crosstool files

- CONTRIBUTORS
- crate_universe/private/crates_vendor.bzl
The intent is to allow this variable to be passed in an --action_env, but ctx.var is not where these show up: ctx.configuration.default_shell_env is.
> Look up CARGO_BAZEL_GENERATOR_PATH correctly

- crate_universe/docs_bzlmod.bzl
- crate_universe/extensions.bzl
- crate_universe/private/crates_vendor.bzl
- docs/src/crate_universe_bzlmod.md
There was previously no way to set `render_config` values with `bzlmod` and `splicing_config` was a bit awkward in it's current implementation by needing to inline a json encoded string. This change adds a `tag_class` to manage the interaction for each config.
> Added render_config and splicing_config to create_universe bzlmod

- rust/private/lto.bzl
- test/unit/lto/lto_test_suite.bzl
Related to https://github.com/bazelbuild/rules_rust/pull/3119
Adds an option named "manual" to `//rust/settings/lto` which was introduced in https://github.com/bazelbuild/rules_rust/pull/3104. When set to "manual" we will not automatically set any flags so users with customized setups can configure the relevant flags on their own.
FWIW this was an oversight and IMO should have been included in the original PR. Apologies to anyone who stumbled over this or encountered build issues!
> fix: add 'manual' option for `//rust/settings/lto`

- crate_universe/extensions.bzl
- crate_universe/private/splicing_utils.bzl
- crate_universe/src/cli/splice.rs
- crate_universe/src/cli/vendor.rs
- crate_universe/src/metadata/workspace_discoverer.rs
- crate_universe/src/splicing/splicer.rs
- crate_universe/tests/cargo_integration_test.rs
There are edge-cases around bazel output symlinks which are fiddly to cover, and I wouldn't expect people to have symlinks between crates within their local workspace. If they do, they can use the explicit `members` property of the Cargo.toml workspace to explicitly include it.
> Ignore symlinks in workspace discovery

- crate_universe/private/crates_vendor.bzl
This is most impactful for windows environments that do not support runfiles (symlinks) at all.
> Updated crates_vendor rule to accurately use runfiles

- examples/compile_opt/.bazelrc
- examples/compile_opt/MODULE.bazel
- examples/compile_opt/README.md
- examples/compile_opt/hello_comp_opt/BUILD.bazel
Fixes comment mentioned in [3143#issuecomment-2568947858](https://github.com/bazelbuild/rules_rust/issues/3143#issuecomment-2568947858)
> Update hello_comp_opt example with new LTO settings

- cargo/cargo_build_script_runner/bin.rs
- test/cargo_build_script/resolve_abs_symlink_out_dir/BUILD.bazel
- test/cargo_build_script/resolve_abs_symlink_out_dir/build.rs
- test/cargo_build_script/resolve_abs_symlink_out_dir/data.txt
- test/cargo_build_script/resolve_abs_symlink_out_dir/test.rs
#2948 breaks building of rdkafka with `cmake` because of dangling symlinks.
When building with latest version we get the following error:
```
ERROR: /home/wincent/.cache/bazel/_bazel_wincent/394c4c1d21c5490d4a70260a2cfccaf5/external/rules_rust~~crate~crates__rdkafka-sys-4.8.0-2.3.0/BUILD.bazel:68:19: error while validating output tree artifact external/rules_rust~~crate~crates__rdkafka-sys-4.8.0-2.3.0/_bs.out_dir: child lib/cmake/RdKafka/FindLZ4.cmake is a dangling symbolic link
ERROR: /home/wincent/.cache/bazel/_bazel_wincent/394c4c1d21c5490d4a70260a2cfccaf5/external/rules_rust~~crate~crates__rdkafka-sys-4.8.0-2.3.0/BUILD.bazel:68:19: Running Cargo build script rdkafka-sys failed: not all outputs were created or valid
Target @@rules_rust~~crate~crates__rdkafka-0.37.0//:rdkafka failed to …
```
> Replace symlinks in the output of cargo build scripts

- crate_universe/extensions.bzl
I spent a bit of time with it on how to use it properly as the documentation was not too explicit to me. So I thought I write it down.
> Add documentation about using binary dependencies in crate_universe

- rust/private/rust.bzl
- rust/private/utils.bzl
- test/unit/compile_data/compile_data_gen.rs
- test/unit/compile_data/compile_data_gen_srcs.rs
- test/unit/compile_data/compile_data_test.bzl
- test/unit/location_expansion/location_expansion_test.bzl
I'm not very well versed in starlark nor the rules_rust codebase, so feel free to ignore this and address the issue in a more fitting way, but this fixes #3171 and a related issue for me.
> Improve handling of compile_data with mixed sources

- rust/extensions.bzl
The bazel-lsp uses `rust_host_tools` to perform some actions by using:
```starlark
rust_host_tools = use_extension("@rules_rust//rust:extensions.bzl", "rust_host_tools") 
use_repo(rust_host_tools, "rust_host_tools")
```
See: https://github.com/cameron-martin/bazel-lsp/blob/19b799e528c884be6efeb108ed1840a4edff1330/MODULE.bazel#L14
It started failing when using rules_rust from HEAD after https://github.com/bazelbuild/rules_rust/pull/3148 because rules_rust's MODULE.bazel registers toolchain with the same name:
```starlark
rust_host_tools.host_tools(
name = "rust_host_tools",
)
```
See: https://github.com/bazelbuild/rules_rust/blob/aae84e97c73eae2e6654e1a7e1b751d0c1f2ac9e/MODULE.bazel#L70
> Don't register rust_host_tools twice

- examples/all_crate_deps/.bazelrc
- examples/all_deps_vendor/.bazelrc
- examples/bazel_env/.bazelrc
- examples/compile_opt/.bazelrc
- examples/crate_universe/.bazelrc
- examples/crate_universe_local_path/.bazelrc
- examples/cross_compile/.bazelrc
- examples/hello_world/.bazelrc
- examples/hello_world_no_cargo/.bazelrc
- examples/musl_cross_compiling/.bazelrc
- examples/nix_cross_compiling/.bazelrc
- examples/override_target/.bazelrc
- examples/proto/.bazelrc
- examples/proto_with_toolchain/.bazelrc
- examples/sys/.bazelrc
- extensions/bindgen/.bazelrc
- extensions/mdbook/.bazelrc
- extensions/prost/.bazelrc
- extensions/protobuf/.bazelrc
- extensions/wasm_bindgen/.bazelrc
- test/no_std/.bazelrc
https://github.com/bazelbuild/bazel/issues/24871 will need to be addressed somehow where unnecessary "built-ins" are either not forcibly pulled in or all built-ins conform to this flag.
> Disable `--incompatible_autoload_externally=` as it's unusable in Bazel8

- rust/private/transitions.bzl
Otherwise aspects can't see through it
> Advertise CrateInfo and DepInfo from the import macro

- cargo/private/internal_extensions.bzl
Since all repo from cargo_repositories are instantiated with the same attribute values. Saves an entry in the lockfile.
> Mark cargo internal extension as reproducible

- crate_universe/src/cli.rs
- crate_universe/src/main.rs
- crate_universe/src/metadata/cargo_tree_resolver.rs
Some of the logging was insanely verbose, so I've opted to add it to `Level::TRACE`.  This level can be enabled by setting the environment variable `CARGO_BAZEL_DEBUG=TRACE`.
> Add support for `CARGO_BAZEL_DEBUG=TRACE` level logging

- cargo/private/cargo_build_script.bzl
- examples/crate_universe/MODULE.bazel
- rust/private/utils.bzl
The former location was deprecated
> Replace uses of //tools/cpp:toolchain_utils.bzl with @rules_cc//cc:find_cc_toolchain.bzl

- cargo/private/cargo_build_script.bzl
Follow-up from https://github.com/bazelbuild/rules_rust/pull/3245: `toolchain.cargo` is optional and might be missing for some custom toolchains; only attempt to set it up if it's present.
> only set $CARGO if toolchain.cargo is set

- crate_universe/extensions.bzl
- crate_universe/private/splicing_utils.bzl
- crate_universe/src/splicing/splicer.rs
This way all files are available for introspection after generation.
> Ensure crate_universe modules don't override intermediates for debugging

- crate_universe/private/crates_vendor.bzl
As `@bazel_tools//tools/bash/runfiles` is now an alias to `@rules_shell//shell/runfiles` with Bazel@HEAD, consumers must properly merge all its runfiles rather than assuming that the `sh_library` target just consists of a single file.
Work towards https://github.com/bazelbuild/examples/pull/557#issuecomment-2677865427
> Merge all runfiles of `@bazel_tools//tools/bash/runfiles`

- crate_universe/extensions.bzl
- crate_universe/private/crate.bzl
- crate_universe/src/config.rs
- crate_universe/src/context/crate_context.rs
- crate_universe/src/lockfile.rs
- examples/crate_universe/alias_rule/cargo-bazel-lock_global_alias_annotation_none.json
- examples/crate_universe/alias_rule/cargo-bazel-lock_global_alias_annotation_opt.json
- examples/crate_universe/alias_rule/cargo-bazel-lock_global_custom_annotation_none.json
- examples/crate_universe/alias_rule/cargo-bazel-lock_global_dbg_annotation_fastbuild.json
- examples/crate_universe/alias_rule/cargo-bazel-lock_global_opt_annotation_alias.json
- examples/crate_universe/alias_rule/cargo-bazel-lock_global_opt_annotation_dbg.json
- examples/crate_universe/alias_rule/cargo-bazel-lock_global_opt_annotation_none.json
- examples/crate_universe/cargo_aliases/cargo-bazel-lock.json
- examples/crate_universe/complicated_dependencies/cargo-bazel-lock.json
- examples/crate_universe/multi_package/cargo-bazel-lock.json
- examples/crate_universe/override_target/cargo-bazel-lock.json
- examples/nix_cross_compiling/bazel/cargo/cargo-bazel-lock.json
- test/unit/crate_name/crate_name_test.bzl
[`link_deps` is a property of `cargo_build_script`](https://bazelbuild.github.io/rules_rust/cargo.html#cargo_build_script-link_deps). This PR adds that ability to add it to third party crates via an annotation.
> Add `build_script_link_deps` to crate annotation system.

- crate_universe/src/lockfile.rs
Re-implements https://github.com/bazelbuild/rules_rust/pull/3223 (special thanks to @tkr-sh!)
> No bazel command will work on NixOS when using crate_universe because `NIX_LD` is removed by `.env_clear()`.
See <https://github.com/nix-community/nix-ld>
This fix is fairly simple, and makes the command work on NixOS.
closes https://github.com/bazelbuild/rules_rust/issues/3224
> fix: add NIX_LDs vars to work on NixOS

- rust/private/rustc.bzl
- test/cc_common_link/unit/cc_common_link_test.bzl
Debug info packages (`dSYM`, `pdb`) are created by `rustc` only if you link with `rustc`. When linking with `cc_common`, they should be handled by the cc toolchain or a custom aspect. Declaring them prematurely can cause conflicts.
This PR removes the `dsym_folder` declaration if `cc_common.link` is being used - since cc_common doesn't support dsym generation yet. It postpones the declaration of `pdb_file` after checking with the cpp features first.
> Handle debug info packages separately when using `cc_common.link`

- tools/rust_analyzer/lib.rs
This fixes #3170, by ensuring that transitive deps like procmacro dylibs are fetched from the disk-cache.
This works in my case, but it's unclear to me if this has unintended consequences for people running remote builds etc, and this can easily be addressed by users manually by adding `build --remote_download_all` to their .bazelrc too if you prefer not merging this.
> Use `--remote_download_all` when building `rust_analyzer_crate_spec`s

- .github/workflows/release.yaml
Confirmed fixed on my fork
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> Fixed release github workflow.

- util/process_wrapper/main.rs
Even when rustc is run with `--error-format=json`, LLVM may still [output
human-readable diagnostics](https://github.com/llvm/llvm-project/blob/680391f07a45272bb9bfd385cf4c6846b8be32dd/llvm/lib/MC/MCSubtargetInfo.cpp#L82)
that are not formatted as JSON. So far, process_wrapper has choked on these.
This patch detects these lines and converts them to JSON so that they can be
processed like JSON diagnostics from rustc itself.
The correct fundamental fix would likely be to teach rustc itself to perform
this conversion, but this is a change that would require some time to implement,
so we're putting this fix in place instead.
> process_wrapper: Convert non-JSON diagnostics from LLVM to JSON.

- cargo/private/cargo_bootstrap.bzl
- crate_universe/extensions.bzl
From a comment of @UebelAndre replacing the previous trick of calling `repository_ctx.path()` by the newly introduced `repository_ctx.watch` solves two issues:
- `rules_rust` correctly re-splices crates when the workspace `Cargo.toml` manifest changes, but also when any of the projects' `Cargo.toml` change
- `rules_rust` correctly re-bootstraps `cargo-bazel` when the source changes (if you're developing for `rules_rust` and using `local_path_override`)
Closes #3216
> Fix monitoring input manifest/lockfile/srcs changes

- extensions/bindgen/MODULE.bazel
Pulling in https://github.com/bazelbuild/bazel-central-registry/pull/3953
> Bump llvm to 17.0.3.bcr.2 for rust_wasm_bindgen

- tools/rust_analyzer/aquery.rs
- tools/rust_analyzer/lib.rs
- tools/rust_analyzer/main.rs
This is useful if you want to analyze code using a different configuration than the default.  An example of this might be under a different platform.
> rust_analyzer: Support passing a --config option to Bazel

- extensions/prost/private/protoc_wrapper.rs
- extensions/prost/private/tests/camel_case/another.proto
- extensions/prost/private/tests/camel_case/camel_case.proto
When generating a message that contains a field that is an enum, the generated code was not following the proper upper camel case convention, making it fail to build.
Example:
```
message Test {
some.pkg.SomethingID test = 1;
}
```
```
#[prost(enumeration="super::some::pkg::SomethingID", tag="1")]
pub test: i32,
```
When we actually expects `SomethingId` because prost generates it like that.
> extensions/prost/private/protoc_wrapper: codegen for enums was broken

- .bazelci/presubmit.yml
- .bazelrc
- util/collect_coverage/collect_coverage.rs
- util/process_wrapper/main.rs
Round two of https://github.com/bazelbuild/rules_rust/pull/2340
> Run CI without building runfiles links

- rust/platform/triple.bzl
- rust/platform/triple_mappings.bzl
- rust/repositories.bzl
Allow rules_rust module to be used on the ppc64le architecture.
> Add support for ppc64le architecture

- extensions/bindgen/defs.bzl
It should've been /README.md but I now think linking to the "folder" is actually nicer.
> Fix broken bindgen doc link

- MODULE.bazel
- WORKSPACE.bazel
- cargo/deps.bzl
- crate_universe/repositories.bzl
- rust/private/internal_extensions.bzl
This fixes issues specifically for missing a `rules_rust_ctve` repository but others I wouldn't have expected to be missing unless users forgot to add the following to their `WORKSPACE.bazel` files
```starlark
load("@rules_rust//cargo:deps.bzl", "cargo_dependencies")
cargo_dependencies()
```
Users just using `crate_universe` and not `cargo_toml_env_vars` directly should be fine using the standard `crate_universe` setup macros
```starlark
load("@rules_rust//crate_universe:repositories.bzl", "crate_universe_dependencies")
crate_universe_dependencies()
```
> Fixed missing cargo_toml_variable_extractor deps

- .bazelci/presubmit.yml
- rust/private/utils.bzl
- test/unit/pipelined_compilation/pipelined_compilation_test.bzl
It's not clear why windows is disabled from this. Gonna enable it so developers can give it a try.
> Enable pipelined_compilation tests for windows

- MODULE.bazel
- crate_universe/3rdparty/crates/BUILD.bazel
- crate_universe/3rdparty/crates/BUILD.crates-index-3.7.0.bazel
- crate_universe/3rdparty/crates/defs.bzl
- crate_universe/Cargo.lock
- crate_universe/Cargo.toml
@UebelAndre my last MR (https://github.com/bazelbuild/rules_rust/pull/3318) got in a funky state due to the github rev pin of crates-index.  I opted to just redo the MR instead of fighting the rebase.
closes https://github.com/bazelbuild/rules_rust/issues/3310
> Updated crates index

- .bazelci/presubmit.yml
- cargo/cargo_build_script_runner/cargo_manifest_dir.rs
- cargo/cargo_toml_variable_extractor/testdata/empty/Cargo.toml
- cargo/private/cargo_toml_info/main.rs
Since our testing mostly uses bzlmod these days, we've currently regressed in this coverage.
> Update MSRV in MODULE.bazel as well as WORKSPACE.bazel

- extensions/bindgen/private/bindgen.bzl
All flags were treated as accepting a parameter, causing any argument following a parameterless flag (e.g. `-no-standard-includes`) to be passed through. This causes bindgen failures if the next argument isn't supported by clang.
`-nostd*` flags has also been expanded using
https://clang.llvm.org/docs/ClangCommandLineReference.html to make it clearer that these flags are parameterless. Since these flags resulted in a prefix match, not a full match, they wouldn't set `open_arg = True` and therefore wouldn't cause issues, but this behavior is unnecessarily subtle now that there are two lists.
Fixes #3359
> Fix rust_bindgen compile flag filtering

- rust/settings/settings.bzl
This setting was introduced in [this commit](https://github.com/bazelbuild/rules_rust/commit/6571cde64cbd72542ea012fe91d678031eb15fbf), and from the context there ([docs](https://github.com/bazelbuild/rules_rust/commit/6571cde64cbd72542ea012fe91d678031eb15fbf#diff-2a806da393e47c07ffe67c78ace69eb488b4ac44b029a46d8237b8e2a05637be), [tests](https://github.com/bazelbuild/rules_rust/commit/6571cde64cbd72542ea012fe91d678031eb15fbf#diff-7cfe86db91ef77d2663a7f891492547fcae21fc081ae947532f031585eb86f1d)), it seems clear that the intent is that the flag should apply to non-exec configurations.
When [this commit](https://github.com/bazelbuild/rules_rust/commit/eb1fe7da8c6cd95ce92c77dcbe00e643dd7c83e8#diff-d516c822cec75e56bb5c193fbd7c7dfd28d8f982224175324da28b61bf6a1fe3) later introduced the …
> Fix documentation for `experimental_per_crate_rustc_flag`.

- rust/runfiles/runfiles.rs
This fixes the ability to use runfiles in scenarios where a runfiles directory is created but all it contains is a `MANIFEST` file.
This matches the behavior of:
- rules_cc: https://github.com/bazelbuild/bazel/blob/c8217fdd2f20e4a061122c0af0417380d09e9480/tools/cpp/runfiles/runfiles_test.cc#L180-L196
- rules_shell: https://github.com/bazelbuild/bazel/blob/c8217fdd2f20e4a061122c0af0417380d09e9480/tools/bash/runfiles/runfiles.bash#L88-L96
> Update runfiles to work with directory embedded manifests

- .github/workflows/release.yaml
- crate_universe/extensions.bzl
- rust/platform/triple.bzl
This change makes `musl` binaries available for all supported linux platforms.
> Update crate universe to use musl binaries on Linux

- crate_universe/extensions.bzl
Relative paths don't work in the deployed documentation since they end up in URLs such as https://bazelbuild.github.io/examples/bzlmod/all_crate_deps
Not sure if there is a better way, but for now this at least fixes the links.
> Fix links in documentation targeting github

- .github/workflows/release.yaml
This was a miss from https://github.com/bazelbuild/rules_rust/pull/3401
> Upload aarch64-unknown-linux-gnu crate_universe binary to releases

- MODULE.bazel
- crate_universe/extensions.bzl
- examples/crate_universe/MODULE.bazel
- rust/repositories.bzl
This allows users of `rules_rust` to define their own `rust_host_tools` modules and use it with `crate_universe` to control the versions of rustc and cargo used by it.
For example:
```python
rust_host_tools = use_extension("@rules_rust//rust:extensions.bzl", "rust_host_tools")
rust_host_tools.host_tools(
name = "my_rust_host_tools",
version = "1.86.0",
)
use_repo(
rust_host_tools,
"my_rust_host_tools",
)
crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
crate.from_cargo(
name = "crate_index",
manifests = ["//:Cargo.toml"],
cargo_lockfile = "//:Cargo.lock",
lockfile = "//:cargo-bazel-lock.json",
host_tools = "@my_rust_host_tools",
)
use_repo(
crate,
"crate_index",
)
```
> Allow `crate_universe` to use external `rust_host_tools`

- rust/toolchain.bzl
`dot_a_files` look like `libcfg_if-578106348.a`, so the substring check currently is the wrong way round and `panic_files` inadvertently ends up empty.
> Filter `panic_files` correctly

- crate_universe/extensions.bzl
- examples/all_deps_vendor/sys_deps.bzl
- extensions/bindgen/defs.bzl
Change all `crate_universe.html` -> `crate_universe_workspace.html` to fix a few 404 in the docs.
> Fix all crate_universe workspace urls

- .bazelci/presubmit.yml
- .pre-commit-config.yaml
- .prettierrc.toml
[43 PRs](https://github.com/bazelbuild/rules_rust/pulls?q=is%3Apr+typo+is%3Aclosed) with the keyword "typo" in the title have been merged. To make the a more scalable solution, I want to introduce pre-commit and starting rolling out https://github.com/crate-ci/typos as a pre-commit hook.
In a follow up PR, we can also add a CI for this.
> Add basic pre commit

- rust/private/rustc.bzl
This change allows to remove linkstamp from CcLinkingContext.
The change is a no-op.
> Use the linkstamps from linker_inputs instead of from cc_linking_context

- ffi/rs/allocator_library/allocator_library.rs
- test/integration/cc_common_link/MODULE.bazel
Added a couple of new symbols that new versions of rustc are emitting (https://github.com/bazelbuild/rules_rust/issues/3459). For testing, bumped the test nightly version to a date that includes a compiler that uses them.
> rust allocator symbols: add new rustc_std_internal_symbol-s

- .pre-commit-config.yaml
- .typos.toml
- cargo/private/cargo_bootstrap.bzl
- cargo/private/cargo_build_script.bzl
- cargo/private/cargo_build_script_wrapper.bzl
- cargo/private/cargo_dep_env.bzl
- cargo/private/cargo_toml_info/main.rs
- cargo/settings/settings.bzl
Followup of #3484 fixing typos in cargo folder
> Fix typos in cargo folder

- crate_universe/private/crates_vendor.bzl
- crate_universe/src/cli/vendor.rs
This lockfile is useful for tools like gazelle because it contains all the information about resolved crates. The regular cargo lockfile does not have enough details about each crate to properly identify dependencies.
> Optionally write the rendering lockfile when vendored

- crate_universe/extensions.bzl
- crate_universe/private/crates_repository.bzl
- crate_universe/private/splicing_utils.bzl
- crate_universe/src/cli/splice.rs
- crate_universe/tests/cargo_integration_test.rs
> Include repository name in splicing errors

- crate_universe/private/crates_vendor.bzl
These are used for authenticating to registries, which may be required when vendoring.
> Pass CARGO_REGISTR* env vars through to vendor

- crate_universe/extensions.bzl
- crate_universe/private/crates_repository.bzl
- crate_universe/private/generate_utils.bzl
- crate_universe/src/cli/generate.rs
> Make Cargo.lock overwrite optional

- crate_universe/extensions.bzl
Fixed a broken link in the all_crate_deps example.
> Fix link to example in extensions.bzl

- .pre-commit-config.yaml
- test/cargo_build_script/cc_args_and_env/cc_args_and_env_test.bzl
- test/cargo_build_script/foreign_toolchain_make_variables/toolchain.bzl
- test/current_toolchain_files/BUILD.bazel
- test/process_wrapper/process_wrapper_tester.cc
- test/process_wrapper_bootstrap/bootstrap_process_wrapper_test.rs
- test/rust_analyzer/generated_srcs_test/lib.rs
- test/unit/exports/exports_test.bzl
- test/unit/toolchain/toolchain_test.bzl
Next cycle of typo fixes in test folder. Removing nix from the exclude as well since it did not had any typos
> Fix typos in nix and test

- crate_universe/extensions.bzl
An implementation to bring some select statement functionality which are available in [repository rules](https://github.com/bazelbuild/rules_rust/blob/f04b2a6f9dc3f26e29563867155da8577b7203ad/crate_universe/private/crate.bzl#L258) but not bzlmod.
Since a dict of dicts is not supported, I've opted for a dict of json string which gets decoded on the other end.
> Adding select statements for build script environment and data attributes in bzlmod

- rust/private/repository_utils.bzl
- rust/repositories.bzl
This adds a path for configuring `strip_level` in the same way as `opt_level`. This will allow configuration away from the default of:
```
default = {
"dbg": "none",
"fastbuild": "none",
"opt": "debuginfo",
},
```
through `rust_register_toolchains`.
> Bring strip_level configuration up to top level

- rust/repositories.bzl
- rust/settings/settings.bzl
In accordance with the process described [here](https://github.com/bazelbuild/rules_rust/blob/main/COMPATIBILITY.md#compatibility-before-10), I will let at least another two weeks pass before removing the setting
entirely.
> Flip default for `incompatible_change_clippy_error_format` to true.

- .github/workflows/release.yaml
When building envoy on s390x, I get an error when trying to download the cargo-bazel binary because it is not published to github releases (see example message below).
This PR adds s390x-unknown-linux-gnu to the list of targets to release.
Error message:
```bash
ERROR: /home/jalbrecht/.cache/bazel/_bazel_jalbrecht/6fade89f6c57252e6093cc46d35caeb2/external/rules_rust/crate_universe/private/generate_utils.bzl:60:13: An error occurred during the fetch of repository 'dynamic_modules_rust_sdk_crate_index':
Traceback (most recent call last):
File "/home/jalbrecht/.cache/bazel/_bazel_jalbrecht/6fade89f6c57252e6093cc46d35caeb2/external/rules_rust/crate_universe/private/crates_repository.bzl", line 28, column 48, in _crates_repository_impl
generator, generator_sha256 = …
```
> Build and upload s390x-unknown-linux-gnu crate_universe binary to releases

- .pre-commit-config.yaml
- rust/platform/triple_mappings.bzl
- rust/private/common.bzl
- rust/private/providers.bzl
- rust/private/repository_utils.bzl
- rust/private/rust.bzl
- rust/private/rustc.bzl
- rust/private/rustdoc.bzl
- rust/private/rustdoc/rustdoc_test_writer.rs
- rust/repositories.bzl
- rust/runfiles/runfiles.rs
- rust/toolchain.bzl
- tools/rustfmt/src/bin/test_main.rs
- util/fetch_shas/fetch_shas.py
- util/process_wrapper/rustc.rs
Fix more typos, bump the typos hook to the latest version available, and exclude `diff` types (we don't want to change patches).
> Fix typos in rust tools and util

- rust/private/repository_utils.bzl
- rust/private/rustc.bzl
- rust/toolchain.bzl
Fixes https://github.com/bazelbuild/rules_rust/issues/2760
> Add libLLVM to coverage runfiles

- rust/private/rustdoc_test.bzl
Mirrors the implementation in the `rust_doc` rule
> Support rustdoc_flags parameter for rust_doc_test similar to rust_doc

- rust/toolchain.bzl
Fixes the following error:
```
rust/toolchain.bzl:867: unsorted-dict-items: Dictionary items are out of their lexicographical order. (https://github.com/bazelbuild/buildtools/blob/main/WARNINGS.md#unsorted-dict-items)
```
> Fix bazel formatting

- crate_universe/src/splicing/splicer.rs
This fixes a warning when using `crates_vendor` from `@rules_rust//crate_universe:defs.bzl` inside a workspace that uses a Rust toolchain 1.89.0 or newer. Specifically I hit this in https://github.com/dtolnay/cxx/tree/ebb3d0954eee94ce9a8189cbcc508b37108a2aee.
```console
dtolnay:cxx$  bazel run //third-party:vendor
INFO: Analyzed target //third-party:vendor (390 packages loaded, 14191 targets configured).
INFO: From Compiling Rust rlib cargo_bazel v0.17.0 (40 files) [for tool]:
warning: hiding a lifetime that's elided elsewhere is confusing
--> external/rules_rust+/crate_universe/src/splicing/splicer.rs:483:27
|
483 |     pub(crate) fn prepare(&self) -> Result<SplicerKind> {
|                           ^^^^^            ----------- the same lifetime is hidden here
| …
```
> Resolve mismatched_lifetime_syntaxes warning in cargo-bazel

- extensions/bindgen/private/bindgen.bzl
- extensions/bindgen/test/bindgen_test.bzl
For some cc_toolchain configurations, this is required to find the builtin
headers.
So far, the bindgen rules had assumed that the builtin headers can be
found through `cc_toolchain.built_in_include_directories`. This is,
however, not guaranteed to be the case; indeed,
`built_in_include_directories` is not really intended for finding
builtin headers but merely for filtering out diagnostics in builtin
headers.
Clang itself finds the resource directory relative to its own binary,
and then finds the builtin headers in the "include" subdirectory of the
resource directory. bindgen-cli may, however, be located in a different
directory than Clang, so we pass a `-resource-dir` flag on the command
line.
> bindgen: Pass `-resource-dir` Clang flag to bindgen-cli.

- rust/private/rust.bzl
When `settings:experimental_per_crate_rustc_flag` is set, the`crate_root` parameter passed to `_collect_cfgs` is accessed. In the case of a `rust_test` using the `crate` attribute, we were previously passing the value of `ctx.file.crate_root` which could be `None`. This change uses `CrateInfo.root` (which should not be `None`) of the library target specified by the `crate` attr instead.
This raises a broader question of what it means for a `rust_test` with `crate` to have a `crate_root` attr also specified. It looks like for compilation purposes, this is ignored, and the `crate_root` of the corresponding `crate` attribute is inherited regardless. Given that, perhaps it makes sense to just `fail()` if a user specifies both `crate` and `crate_root` attrs simultaneously?
> Fix 'NoneType has no attribute' error when building `rust_test` using `crate` attr with `settings:experimental_per_crate_rustc_flag` set

- cargo/private/cargo_build_script.bzl
- cargo/private/cargo_build_script_wrapper.bzl
- crate_universe/src/context/crate_context.rs
- crate_universe/src/rendering.rs
- test/cargo_build_script/build_script_env_files/BUILD.bazel
- test/cargo_build_script/build_script_env_files/build.rs
- test/cargo_build_script/build_script_env_files/test_lib.rs
Fixes https://github.com/bazelbuild/rules_rust/issues/3625, see that issue for explanation
> Allow passing env files to build script runtime env

- crate_universe/extensions.bzl
- crate_universe/private/crates_repository.bzl
- crate_universe/private/generate_utils.bzl
- crate_universe/private/splicing_utils.bzl
- crate_universe/src/cli/splice.rs
- crate_universe/tests/cargo_integration_test.rs
If we already have a Cargo.lock and don't intend to let cargo-bazel update it, we can just use it for splicing directly.
> [cargo-bazel] Avoid regenerating cargo lockfile when splicing is not needed

- crate_universe/extensions.bzl
If the only annotation used is annotation_select, it will be silently dropped because no repository annotation exists yet.
> Use setdefault in case no other annotations exist

- rust/private/utils.bzl
> Fast-path _expand_location_for_build_script_runner

- cargo/private/cargo_build_script.bzl
- rust/private/rust.bzl
- rust/private/rust_analyzer.bzl
- rust/private/utils.bzl
- rust/toolchain.bzl
Does what it says on the tin. Usually the deduping was not necessary at all because the argument were already coming from a depset or an attribute (though kept for safety), but doing the same work for every arg was truly unnecessary
Before:
After:
> Avoid quadratic deduping in location expansion

- rust/runfiles/runfiles.rs
Instead fallback on a directory based approach.
This matches the behavior of rules_python: https://github.com/bazel-contrib/rules_python/blob/79f654686646e2ab213741bc4774ea9d69895b54/python/runfiles/runfiles.py#L458
This addresses #3654.
> Update the runfiles library behavior to support an empty RUNFILES_MANIFEST_FILE

- rust/private/rustc.bzl
> collect_inputs.files: fix docs and and add a check for `data`

- .bazelrc
- examples/all_crate_deps/.bazelrc
- examples/all_deps_vendor/.bazelrc
- examples/android/.bazelrc
- examples/bazel_env/.bazelrc
- examples/compile_opt/.bazelrc
- examples/crate_universe/.bazelrc
- examples/crate_universe_local_path/.bazelrc
- examples/cross_compile/.bazelrc
- examples/hello_world/.bazelrc
- examples/hello_world_no_cargo/.bazelrc
- examples/ios/.bazelrc
- examples/ios_build/.bazelrc
- examples/musl_cross_compiling/.bazelrc
- examples/nix_cross_compiling/.bazelrc
- examples/override_target/.bazelrc
- examples/proto/.bazelrc
- examples/proto_with_toolchain/.bazelrc
- examples/sys/.bazelrc
- extensions/bindgen/.bazelrc
- extensions/mdbook/.bazelrc
- extensions/prost/.bazelrc
- extensions/protobuf/.bazelrc
- extensions/wasm_bindgen/.bazelrc
- test/integration/cc_common_link/.bazelrc
- test/integration/cc_common_link_with_global_alloc/.bazelrc
- test/integration/no_std/.bazelrc
We no longer test versions below Bazel 7
> Delete old bazelrc flag no longer used for testing
