README.md

Update README to address bazel version

---

.bazelci/presubmit.yml
README.md

add new bazel ci configuration

---

rust/repositories.bzl

This is a pretty simple (mostly copy/paste) change to add support for FreeBSD.

Add FreeBSD toolchain.

---

README.md

The method is called "greet" not "greeting"
EDIT: Added a method "greeting" and made the ""greet" method call it.

Fix the example for test in the README

---

WORKSPACE

Update repository rules to supported versions

---

WORKSPACE
examples/ffi/rust_calling_c/BUILD
rust/rust.bzl
rust/toolchain.bzl
rust/utils.bzl

See https://github.com/bazelbuild/buildtools/blob/master/buildifier/README.md for details on buildifier.
@mfarrugi At your leisure.

Apply buildifier to rules_rust files

---

WORKSPACE

https://github.com/bazelbuild/rules_rust/issues/125

update bazel-toolchains pin

---

workspace.bzl

Do not crash on using version check with development version of bazel.

---

rust/private/rustc.bzl

Bazel CI still failing: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/528#70b8ac31-e21e-4e8e-b27a-34e384808db3

Fix version check in rustc.bzl

---

WORKSPACE

To be compatible with the next version of Bazel.
/cc @cushon

Update version of stardoc

---

proto/proto.bzl

https://github.com/bazelbuild/bazel/issues/7152 
requires bazel >= 22

Use ProtoInfo instead of legacy .proto attr

---

bindgen/bindgen.bzl
rust/private/legacy_cc_starlark_api_shim.bzl
rust/private/rustc.bzl

Locally tested this works with and without the flag on bazel v22.

#190, #200 :: Migrate to new cc provider.

---

tools/runfiles/runfiles.rs

We were doing $CWD + link_target instead of $CWD + link_dir + link_target.
Also some drive by refactors, and ran rustfmt.

Fix symlink resolution in runfiles.rs

---

rust/private/rustc.bzl

This PR migrates rules_rust for https://github.com/bazelbuild/bazel/issues/7793

Migrate for Bazel's --incompatible_require_ctx_in_configure_features

---

test/proto/BUILD

Replace the deprecated proto_source_root attribute.

---

rust/private/rustc.bzl

Fixes https://github.com/bazelbuild/rules_rust/issues/243

Use empty dictionary instead of None for kwargs

---

README.md

https://buildkite.com/bazel/rules-rust-plus-bazelisk-migrate

Add badge for incompatible flag pipeline

---

bindgen/clang.BUILD
bindgen/raze/libloading.BUILD
examples/ffi/c_calling_rust/BUILD
examples/ffi/rust_calling_c/BUILD
examples/ffi/rust_calling_c/c/BUILD
examples/ffi/rust_calling_c/simple/BUILD
examples/hello_runfiles/BUILD
examples/hello_world/BUILD
examples/proto/BUILD
examples/proto/helloworld/BUILD
proto/BUILD
proto/proto.bzl
test/BUILD
test/proto/BUILD
wasm_bindgen/raze/overrides/backtrace-sys-0.1.29.BUILD
wasm_bindgen/wasm_bindgen.bzl

Migrating rules_rust for these incompatible changes:
https://github.com/bazelbuild/bazel/issues/9006
https://github.com/bazelbuild/bazel/issues/8922
https://github.com/bazelbuild/bazel/issues/8743
Only review/merge after https://github.com/bazelbuild/rules_rust/pull/261 and https://github.com/bazelbuild/rules_rust/pull/260.
Thanks!

Fix bzl loads

---

proto/repositories.bzl

Context: https://github.com/bazelbuild/bazel/issues/10270

Mirror all http_archives.

---

.gitignore

Running examples generates a couple of these

gitignore node_modules

---

cargo/cargo_build_script.bzl

Certain crates (e.g. openssl-sys, bzip2-sys) use "cc" during their
build script phase. Cargo just picks up "cc" available with CC env
variable or throught PATH.
This change exposes CC variable for build scripts with a path to
C compiler obtained from Bazel cc_toolchain.

Provide access to C compiler to crate build scripts.

---

.bazelci/presubmit.yml
rust/private/rustdoc_test.bzl
rust/repositories.bzl

This allows us to run tests in the CI

Fix rustdoc_test on windows

---

rust/repositories.bzl

PR should address:
https://github.com/bazelbuild/rules_rust/issues/396 
Discussion here:
https://twitter.com/pietroalbini/status/1302551048935088128?s=20

Update rustfmt version to fix #396

---

cargo/cargo_build_script.bzl
cargo/cargo_build_script_runner/bin.rs
cargo/cargo_build_script_runner/lib.rs

See individual commits for details.

Assorted cargo build script fixes

---

examples/examples_deps.bzl

Fixed buildifier defect

---

.bazelignore
docs/flatten.md
docs/rust_repositories.md
docs/rust_workspace.md

Fixed a couple of small things

Small cleanup pass

---

rust/private/rustc.bzl

I believe this solves for #442 which in some worst case scenarios should be a speed improvement according to https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#overly-nested-depset

Fixed overly-nested-depset warnings

---

rust/private/rustc.bzl

A new way that will not break with new versions of Bazel was proposed.
This is cleaner and should get in before the next version of Bazel,
which will change the behaviour of `ctx.build_file_path`.
See https://github.com/bazelbuild/bazel/issues/12344#issuecomment-721815138 - thanks @lberki for the suggestion <3

Stable way to infer CARGO_MANIFEST_DIR

---

docs/index.md

Signed-off-by: Piotr Sikora <piotrsikora@google.com>

Update commit and versions in the documentation.

---

examples/examples_repositories.bzl

Added missing sha256

---

test/build_env/BUILD.bazel
test/unit/common.bzl
test/unit/crate_name/crate_name_test.bzl

I think this CI check just started working.

Fix some buildifier errors.

---

crate_universe/Cargo.lock
crate_universe/Cargo.toml

Pulls in https://github.com/UebelAndre/cargo-raze/pull/1

Include sha256s by default

---

crate_universe/src/renderer.rs
crate_universe/src/templates/defs.bzl.template

Currently we get an error about bad indentation

Generate valid file if no crates are found

---

crate_universe/src/renderer.rs
crate_universe/src/templates/defs.bzl.template

This gets us closer to generating buildifier-compliant rules

Only load required rules

---

util/process_wrapper/process_wrapper.cc
util/process_wrapper/system.h
util/process_wrapper/system_posix.cc
util/process_wrapper/system_windows.cc
util/process_wrapper/utils.cc

Just running clangd (which uses clang-format I believe) reformatting.

Reformat C++ code

---

tools/rust_analyzer/main.rs

This commit fixes a couple of issues with the gen_rust_project rule.
1) Repository name is ignored from the parsed label, causing targets in external workspaces to not work correctly.
2) The bazel-bin path is relying on the workspace symlink instead of the actual bazel-bin directory. This causes file not found errors when --experimental_convenience_symlinks=ignore is set (see: https://docs.bazel.build/versions/master/command-line-reference.html#flag--experimental_convenience_symlinks).

Fixes for //tools/rust_analyzer:gen_rust_project

---

rust/private/clippy.bzl
rust/private/rustc.bzl

The `toolchain` argument of `collect_deps` was unused. Removing it.

---

rust/private/clippy.bzl

Clippy should ideally only run on targets within the user's workspace since defects in external code can generally be out of the user's control. This matches the behavior of the [rustfmt](https://github.com/bazelbuild/rules_rust/blob/c9345d33123e49928a021f75725da2f5b609f660/rust/private/rustfmt.bzl#L6-L32) rule, another Rust linter aspect/rule.

Prevent clippy from running on external targets.

---

rust/private/repository_utils.bzl
rust/toolchain.bzl

These docs are not exposed externally so should only impact contributors (but hopefully in a good way! 😄).

Updated internal documentation

---

rust/private/clippy.bzl
rust/private/rustc.bzl

`construct_arguments` now generates separate sets of arguments, one for the process wrapper, another to launch `rustc` from the process wrapper, and a final set for Rust flags. This allows rules like clippy to pass flags to the process wrapper and not have this function need to be aware of clippy (making the rules more contained).

Internal macro `construct_arguments` now generates separate Args sets

---

docs/BUILD.bazel
docs/defs.md
docs/flatten.md
docs/symbols.bzl

Split from https://github.com/bazelbuild/rules_rust/pull/566

Add docs for error_format

---

rust/private/clippy.bzl

Fixes https://github.com/bazelbuild/rules_rust/issues/943

Resolve clippy remote execution build error

---

crate_universe/src/resolver.rs

Don't filter out pre-release versions for git deps

---

tools/runfiles/runfiles.rs

Derive Debug for runfiles

---

crate_universe/src/renderer.rs
crate_universe/src/templates/partials/git_repository.template

Many sys crates pull in source as a submodule

Init submodules for crate_universe git repos

---

rust/settings/BUILD.bazel

https://github.com/bazelbuild/rules_rust/issues/1051

Flip --incompatible_remove_transitive_libs_from_dep_info

---

test/test_env_launcher/BUILD.bazel
test/test_env_launcher/tests/run.rs

Minor cleanup in prep for https://github.com/bazelbuild/rules_rust/pull/1079

Updated tests to prep for `incompatible_disable_custom_test_launcher` fiip

---

rust/private/rustc.bzl

Works around https://github.com/bazelbuild/bazel/issues/14681

Deduplicate input to ctx.expand_location

---

crate_universe/src/templates/partials/build_script.template
examples/crate_universe/basic/BUILD.bazel
examples/crate_universe/basic/src/main.rs
examples/crate_universe/basic/workspace.bzl

Pass through aliases for build dependencies

---

crate_universe/src/context.rs
crate_universe/src/rendering.rs
crate_universe/test_data/metadata/aliases/Cargo.lock
crate_universe/test_data/metadata/aliases/Cargo.toml
crate_universe/test_data/metadata/aliases/metadata.json
crate_universe/test_data/private/metadata_generator.py

Fixed test metadata generation for crate_universe tests

Fixed crate_universe test metadata generation

---

examples/crate_universe/WORKSPACE.bazel
examples/crate_universe/cargo_aliases/Cargo.Bazel.lock
examples/crate_universe/cargo_aliases/Cargo.lock
examples/crate_universe/cargo_aliases/Cargo.toml

This pulls in https://crates.io/crates/names/0.13.0

Updated crate_universe examples

---

version.bzl

addresses https://github.com/bazelbuild/rules_rust/issues/1242

Updating `rules_rust` version to `0.2.1`

---

version.bzl

closes https://github.com/bazelbuild/rules_rust/issues/1272

Updated `rules_rust` version to `0.3.1`

---

crate_universe/defs.bzl
crate_universe/private/crates_repository.bzl
crate_universe/private/crates_vendor.bzl
docs/crate_universe.md

Updated crate_universe docs

---

bindgen/bindgen.bzl
rust/private/clippy.bzl

Prevents running of clippy on bindgen targets

---

docs/flatten.md
docs/rust_bindgen.md
docs/rust_repositories.md
docs/symbols.bzl

closes https://github.com/bazelbuild/rules_rust/issues/1357

Fixed missing docs

---

crate_universe/crates.bzl

Minor cleanup for `crate_universe`.

Removed deprecated file

---

rust/private/rustc.bzl

Minor commenting while I was learning more about [pic](https://en.wikipedia.org/wiki/Position-independent_code).

Added comments to internal function

---

crate_universe/src/metadata/dependency.rs

Fixed crate_universe not finding target library names for "rlib"s

---

test/cargo_build_script/BUILD.bazel
test/rustc_env_files/BUILD.bazel

Replaced small genrules with uses of bazel_skylib

---

examples/WORKSPACE.bazel
rust/private/rust_analyzer.bzl
test/rust_analyzer/rust_analyzer_test_runner.sh
test/rust_analyzer/static_and_shared_lib_test/BUILD.bazel
test/rust_analyzer/static_and_shared_lib_test/greeter.rs
test/rust_analyzer/static_and_shared_lib_test/rust_project_json_test.rs
test/rust_analyzer/static_and_shared_lib_test/shared_lib.rs
test/rust_analyzer/static_and_shared_lib_test/static_lib.rs

closes https://github.com/bazelbuild/rules_rust/issues/1481

Fixed use of rust-analyzer with rust static and shared lib targets

---

crate_universe/docs.bzl
docs/crate_universe.md
docs/index.md

closes https://github.com/bazelbuild/rules_rust/issues/1495

Promoted crate_universe to non-experimental

---

.bazelci/presubmit.yml

closes https://github.com/bazelbuild/rules_rust/issues/615

Enable rust-analyzer tests on windows.

---

bindgen/3rdparty/BUILD.bazel
proto/3rdparty/BUILD.bazel
tools/rust_analyzer/3rdparty/BUILD.bazel
util/import/3rdparty/BUILD.bazel
wasm_bindgen/3rdparty/BUILD.bazel

This glob does not glob anything and prevents to compile with incompatible_disallow_empty_glob

Remove empty glob

---

.bazelci/presubmit.yml

https://github.com/bazelbuild/rules_rust/issues/1629 is the tracking issue.

Disable failing job in CI

---

crate_universe/docs.bzl
crate_universe/private/crates_repository.bzl
docs/crate_universe.md

Fix confusing/misleading crate_universe docs

---

crate_universe/private/crate.bzl
crate_universe/src/config.rs
docs/crate_universe.md

Match prerelease versions with annotation wildcard

---

rust/platform/triple_mappings.bzl

This change is intended to help users avoid issues where they forgot to add constraints.

Unify functions for computing constraint values for platform triple abi

---

rust/platform/triple_mappings.bzl
rust/private/repository_utils.bzl
rust/repositories.bzl
test/load_arbitrary_tool/load_arbitrary_tool_test.bzl
test/unit/repository_utils/repository_utils_test.bzl

Minor cleanup to avoid computing parts of a platform triple multiple times.

Updated platform triple values from strings to structs ("triple")

---

docs/defs.md
docs/flatten.md
rust/private/rust.bzl

* Fix example code
* Regenerate documentation

Fix code example in doc

---

test/unit/native_deps/native_deps_test.bzl

On M1 macs the bazel-out darwin path is `darwin_arm64-fastbuild`. This just takes whatever is there and allows it just assuming bazel is doing the right thing.

Fix test assertion for arm64 macs

---

examples/crate_universe/vendor_local_manifests/BUILD.bazel

relates to https://github.com/bazelbuild/rules_rust/issues/1860

Silence windows build failure

---

cargo/private/cargo_build_script.bzl
cargo/private/cargo_build_script_wrapper.bzl
test/cargo_build_script/BUILD.bazel
test/cargo_build_script/build.rs

closes https://github.com/bazelbuild/rules_rust/issues/1859

Forward `toolchains` to `cargo_build_script` targets

---

crate_universe/src/metadata.rs

In metadata.rs `cargo tree` is called per platform triple. Have these calls happen in parallel.
Context: https://bazelbuild.slack.com/archives/CSV56UT0F/p1678470889893829?thread_ts=1678379024.023019&cid=CSV56UT0F

Parallelize cargo tree calls

---

util/fetch_shas.sh

Not sure which mktemp it's been used with before, but it doesn't work with mine.

Make fetch_shas work with mktemp from coreutils 8.32

---

.bazelci/presubmit.yml

see https://github.com/bazelbuild/rules_rust/issues/1892

Disable zig example

---

.bazelci/presubmit.yml

@bsilver8192 noticed the config setting isn't applied on the tests.

ci: fix test config in cc_common_link_ubuntu2004

---

examples/ios/WORKSPACE.bazel

Fixes https://github.com/bazelbuild/rules_rust/issues/1963

Update rules_apple in tests

---

docs/test_docs.sh
test/clippy/clippy_failure_test.sh
test/current_toolchain_files/current_toolchain_files_test_runner.sh
test/portable_link_flags_darwin/test.sh
test/rust_analyzer/rust_analyzer_test_runner.sh
test/rustfmt/rustfmt_failure_test.sh

Minor cleanup which helps ensure errors surface in the right places when contributors are working on changes.

Update various bash scripts to pipe errors to stderr

---

bindgen/bindgen.bzl

To avoid bindgen mixing includes it finds on the host with ones that may already be defined in the configured `cc_toolchain`, the Bindgen rules will now attempt to pass `--sysroot` to clang if the configured `cc_toolchain` has a sysroot set. 
This functionality can be disabled by using the `no-rust-bindgen-cc-sysroot` [feature flag](https://bazel.build/reference/command-line-reference#flag--features) or [feature attribute](https://bazel.build/reference/be/common-definitions#common-attributes).

Allow sysroots from cc_toolchains to be added to bindgen actions

---

version.bzl

This release includes the following commits:

Release 0.25.0

---

version.bzl

These are the current changes:
And I think we should wait for these two PRs to merge as well:
- https://github.com/bazelbuild/rules_rust/pull/2043
- https://github.com/bazelbuild/rules_rust/pull/2044

Release 0.26.0

---

.bazelci/presubmit.yml

https://github.com/bazelbuild/rules_rust/issues/2075#issuecomment-1652843634

Disable zig cross compiling example

---

docs/flatten.md
docs/providers.md
rust/private/common.bzl
rust/private/providers.bzl
rust/private/rust.bzl
rust/private/rustc.bzl
rust/private/rustdoc.bzl
test/proc_macro/data/BUILD.bazel
test/proc_macro/data/nonmacro_library.rs
test/proc_macro/data/proc_macro_helper.rs
test/proc_macro/data/rust_proc_macro.rs
test/proc_macro/data/rust_test.rs

Make proc macros' "data" available in compile_data of crates that use macro

---

crate_universe/Cargo.toml

Fill in some crate metadata for publishing cargo-bazel to crates.io

---

.github/workflows/cargo_bazel_release.yaml
crate_universe/BUILD.bazel
crate_universe/tests/version_test.rs
crate_universe/version.bzl

closes https://github.com/bazelbuild/rules_rust/issues/2131

Added github action to publish cargo-bazel binaries.

---

cargo/private/cargo_build_script.bzl
test/cargo_build_script/tools_exec/BUILD.bazel
test/cargo_build_script/tools_exec/build.rs

As per https://doc.rust-lang.org/cargo/reference/environment-variables.html

Set CARGO_MANIFEST_LINKS if links is set

---

proto/prost/private/protoc_wrapper.rs

If the command line passed to protoc is too long, `proto_common.compile` will [spill the args to an argfile](https://github.com/bazelbuild/bazel/blob/release-6.3.0/src/main/starlark/builtins_bzl/common/proto/proto_common.bzl#L105). This PR changes the arg parsing logic to handle the argfile.
Without this change, a prost pbtype build with enough dependencies will fail in a strange way. For me this manifested as the `--prost_out` flag being missing, because it was in the argfile.

[prost] Handle argfiles

---

docs/rust_proto.md
docs/rust_proto.vm

This PR fixes a prost toolchain documentation typo.

Fix prost toolchain documentation typo

---

MODULE.bazel
rust/repositories.bzl
wasm_bindgen/repositories.bzl

Update rules_cc to 0.0.9 which has not been upgraded for a long time

Update rules_cc to 0.0.9

---

.bazelci/presubmit.yml
WORKSPACE.bazel

To fix BazelCI errors for the presubmit.

Migrade rbe_ubuntu1604 to rbe_ubuntu2004

---

crate_universe/src/utils/starlark/select.rs

Previously, we only allowed cfg-expressions.
We started allowing target triples in #2139.
Now we also allow bazel labels.
Fixes #2233

Allow passing explicit labels as select keys

---

util/repin_all.sh

Every time I need to update these I incrementally run these commands, finding out what I missed via CI each time.
Instead, let's write this down.

Add repin script

---

MODULE.bazel
version.bzl

I mostly want to test whether the "Publish to BCR" release workflow works.

Release 0.33.0

---

crate_universe/test_data/test_data_passing_crate/Cargo.toml

Add licence to Cargo.toml

---

MODULE.bazel
version.bzl

Release 0.34.1

---

MODULE.bazel

Related to https://github.com/bazelbuild/bazel-central-registry/pull/1199#discussion_r1429128823.

chore: remove print from MODULE.bazel

---

MODULE.bazel
rust/repositories.bzl

Fixes https://github.com/bazelbuild/rules_rust/issues/2481
CC Greenteam @mai93 @meteorcloudy

Fixes the ci failure in Bazel

---

crate_universe/src/splicing.rs

Check if resolved index URL starts with sparse+

---

MODULE.bazel
examples/ios/WORKSPACE.bazel
rust/repositories.bzl

Fixes https://github.com/bazelbuild/rules_rust/issues/2495

Update apple rules

---

.bazelci/presubmit.yml

relates to https://github.com/bazelbuild/rules_rust/issues/2554

Temporarily disable "Examples Clang with LLD" CI job

---

MODULE.bazel
crate_universe/3rdparty/crates/BUILD.bazel
crate_universe/3rdparty/crates/BUILD.cargo_toml-0.19.2.bazel
crate_universe/3rdparty/crates/defs.bzl
crate_universe/Cargo.lock
crate_universe/Cargo.toml
crate_universe/src/lockfile.rs
crate_universe/src/splicing/splicer.rs

Fixed: #2348, #2536, #2433, #2434

Update cargo_toml to `0.19.2`

---

crate_universe/private/selects.bzl

Doesn't look used anymore, this was from 2 years ago

Removed unused 'select_with_or'

---

.bazelci/presubmit.yml
.github/workflows/release.yaml
WORKSPACE.bazel
crate_universe/repositories.bzl
crate_universe/tools/cross_installer/BUILD.bazel
crate_universe/tools/cross_installer/cross_installer_deps.bzl
crate_universe/tools/cross_installer/src/main.rs
examples/bzlmod/hello_world/MODULE.bazel.lock

Fix is demonstrated by https://github.com/UebelAndre/rules_rust/actions/runs/9018414504

Update cross to fix crate_universe builds in releases

---

tools/runfiles/runfiles.rs

Currently, if the repo mapping maps "foo" to "real_foo", then:
* `rlocation!(r, "foo/bar/baz")` will return "real_foo/bar/baz"
* `rlocation!(r, "foo")` will return `foo`
This PR handles the case where the user attempts to do something like `rlocation!("rules_rust")` (which is valid for directory based runfiles).

Allow searching for the rlocation of a module.

---

cargo/private/cargo_build_script.bzl

This allows it to work with new-style toolchains that use action configs (see https://github.com/bazelbuild/bazel/issues/22561).
It also allows you to specify a seperate C compiler and C++ compiler.

Fix cargo_build_script executables.

---

examples/wasm_bindgen/rules_js/BUILD.bazel
wasm_bindgen/private/wasm_bindgen.bzl

Don't expect typescript outputs if this flag is set.

Respect "--no-typescript" flag in wasm_bindgen

---

crate_universe/src/metadata.rs

Otherwise on repinning, we get errors because virtual workspaces can't have deps.
Repinning the multi_package example hit this problem.

Add virtual deps to package, not virtual workspace root

---

crate_universe/src/metadata.rs

Fake resolve roots don't forcibly enable default features

---

tools/runfiles/runfiles.rs

closes https://github.com/bazelbuild/rules_rust/issues/2868

Fix runfiles creation for directory based runfiles.

---

.bazelrc

The default value for this flag changed, but we require it.

Get rolling releases CI green

---

crate_universe/src/metadata/workspace_discoverer.rs

Ignore dangling symlinks when discovering workspaces

---

.bazelrc
MODULE.bazel
docs/BUILD.bazel
docs/MODULE.bazel
examples/bazel_env/BUILD.bazel
examples/bazel_env/MODULE.bazel
examples/bzlmod/all_crate_deps/BUILD.bazel
examples/bzlmod/all_crate_deps/MODULE.bazel
examples/bzlmod/cross_compile/BUILD.bazel
examples/bzlmod/cross_compile/MODULE.bazel
examples/crate_universe_local_path/BUILD.bazel
examples/crate_universe_local_path/MODULE.bazel
examples/ios_build/BUILD.bazel
examples/musl_cross_compiling/BUILD.bazel
examples/sys/basic/BUILD.bazel
rust/private/repository_utils.bzl
rust/repositories.bzl
test/BUILD.bazel
test/cc_shared_library/BUILD.bazel
test/clippy/BUILD.bazel
test/empty_suite/BUILD.bazel
test/portable_link_flags_darwin/BUILD.bazel
test/rust_analyzer/BUILD.bazel
test/rustfmt/rustfmt_integration_test_suite.bzl

Use rules_shell instead of built-in rules

---

docs/src/rust_mdbook.md
extensions/mdbook/defs.bzl

A miss from https://github.com/bazelbuild/rules_rust/pull/3105

Updated rules_rust_mdbook docs

---

crate_universe/src/cli/generate.rs

Rerun repository rule if manifests changed

---

MODULE.bazel
cargo/deps.bzl

closes https://github.com/bazelbuild/rules_rust/issues/3191

Fixed missing bzlmod repository

---

cargo/cargo_build_script_runner/lib.rs

In Rust 1.77.0, the preferred build directive prefix for Cargo commands was changed from `cargo:` to `cargo::`.  (The single-colon prefix is still supported, but is no longer the default in documentation.)
With this commit, the `cargo_build_script_runner` tool now supports both prefixes.
This fixes issue #2980.

Support new `cargo::` prefixes in build script outputs.

---

.bazelci/presubmit.yml
.github/workflows/formatting.yaml
cargo/private/cargo_build_script.bzl
examples/nix_cross_compiling/MODULE.bazel
examples/nix_cross_compiling/bazel/toolchain_rules/llvm_cc_toolchain_config.bzl
extensions/bindgen/private/bindgen.bzl
extensions/prost/private/prost.bzl
extensions/prost/private/prost_transform.bzl
rust/private/BUILD.bazel
rust/private/dummy_cc_toolchain/dummy_cc_toolchain.bzl
rust/private/rust.bzl
rust/private/rustc.bzl
rust/private/rustdoc_test.bzl
rust/private/utils.bzl
rust/settings/BUILD.bazel
rust/settings/settings.bzl
rust/toolchain.bzl
test/cargo_build_script/cc_args_and_env/cc_args_and_env_test.bzl
test/cc_shared_library/BUILD.bazel
test/unit/cc_info/cc_info_test.bzl
test/unit/check_runfiles/check_runfiles_test.bzl
test/unit/consistent_crate_name/with_modified_crate_name.bzl
test/unit/force_all_deps_direct/generator.bzl
test/unit/interleaved_cc_info/interleaved_cc_info_test.bzl
test/unit/linkstamps/linkstamps_test.bzl
test/unit/native_deps/native_action_inputs_test.bzl
test/unit/pipelined_compilation/wrap.bzl
test/unit/stdlib/stdlib.bzl
test/unit/transitive_crate_outputs/transitive_crate_outputs_test.bzl
test/unit/win_interface_library/win_interface_library_analysis_test.bzl

Avoids https://github.com/bazelbuild/continuous-integration/issues/2167

Move buildifier to github actions

---

examples/proto/MODULE.bazel
examples/proto/README.md
examples/proto/build/prost_toolchain/BUILD.bazel
examples/proto/build/proto_toolchain/BUILD.bazel
examples/proto_with_toolchain/MODULE.bazel
examples/proto_with_toolchain/README.md
examples/proto_with_toolchain/build/proto_toolchain/BUILD.bazel
extensions/prost/MODULE.bazel
extensions/protobuf/MODULE.bazel

I forgot to add this to https://github.com/bazelbuild/rules_rust/pull/3219

Fixed broken protoc toolchain in examples 

---

extensions/prost/private/prost.bzl

This should help with aspects ability to discover these targets.

Added expected providers to `rust_prost_library`.

---

crate_universe/src/api/lockfile.rs
crate_universe/src/context/crate_context.rs
crate_universe/src/context/platforms.rs
crate_universe/src/rendering.rs
examples/crate_universe/alias_rule/cargo-bazel-lock_global_alias_annotation_none.json
examples/crate_universe/alias_rule/cargo-bazel-lock_global_alias_annotation_opt.json
examples/crate_universe/alias_rule/cargo-bazel-lock_global_custom_annotation_none.json
examples/crate_universe/alias_rule/cargo-bazel-lock_global_dbg_annotation_fastbuild.json
examples/crate_universe/alias_rule/cargo-bazel-lock_global_opt_annotation_alias.json
examples/crate_universe/alias_rule/cargo-bazel-lock_global_opt_annotation_dbg.json
examples/crate_universe/alias_rule/cargo-bazel-lock_global_opt_annotation_none.json
examples/crate_universe/cargo_aliases/cargo-bazel-lock.json
examples/crate_universe/cargo_conditional_deps/cargo-bazel-lock.json
examples/crate_universe/cargo_workspace/cargo-bazel-lock.json
examples/crate_universe/complicated_dependencies/cargo-bazel-lock.json
examples/crate_universe/multi_package/cargo-bazel-lock.json
examples/crate_universe/override_target/cargo-bazel-lock.json
examples/crate_universe/using_cxx/cargo-bazel-lock.json
examples/crate_universe/using_cxx/cxxbridge-cmd.cargo-bazel-lock.json
examples/nix_cross_compiling/bazel/cargo/cargo-bazel-lock.json

... by only plumbing local patched paths.
Change-Id: Idfaf53d93fe11776a70d706726ed4bff0bf5233e

[path_patching] Shrink size of lockfiles

---

cargo/cargo_toml_variable_extractor/main.rs

Fixes[ issue](https://github.com/bazelbuild/rules_rust/issues/3349)
Tested and verified

Fix temp value is freed

---

rust/runfiles/runfiles.rs

This introduces a small re-implementation of https://crates.io/crates/temp-env while keeping the tests free of dependencies. This should make it substantially easier to write meaningful tests for runfiles.

Updated unit tests for runfiles

---

test/unit/pipelined_compilation/pipelined_compilation_test.bzl

See https://github.com/bazelbuild/rules_rust/issues/3383

Disable pipeline compilation tests on windows

---

crate_universe/private/crate.bzl

The current docs are misleading.

Fix annotation docs

---

rust/rust_binary.bzl
rust/rust_library.bzl
rust/rust_library_group.bzl
rust/rust_proc_macro.bzl
rust/rust_shared_library.bzl
rust/rust_static_library.bzl
rust/rust_test.bzl

This matches what we see in other rules.

Added granular interfaces for core rules

---

docs/src/index.md
docs/src/rules.md

Hi, this is referencing issue #2973 , i'm sorry i kinda forgot this was open too. Let me know if it is clear or if it needs modification.
Parallelly, i removed refernces to a no longer existing file `flatten.md`. Is this correct, or do you want to open a separate issue/pr? Thanks!

[Doc] Improve documentation on toolchain registration with bzlmod

---

.bazelci/presubmit.yml
WORKSPACE.bazel
extensions/prost/WORKSPACE.bazel
extensions/prost/private/internal_extensions.bzl
extensions/protobuf/private/internal_extensions.bzl

Try to fix the RBE errors like:
```
external/abseil-cpp+/absl/hash/internal/hash.h:66:10: fatal error: filesystem: No such file or directory
```
Followed the fix for python https://github.com/bazel-contrib/rules_python/pull/3083.

update RBE workers platform to `ubuntu2204`

---

crate_universe/src/metadata/cargo_tree_resolver.rs

Not spawning everything at once makes sense, but doing it in batches per-host can lead to some bottlenecking as well as CPU contention if there are many platforms. Use a "semaphore" instead.

Improve concurrency control for cargo_tree_resolver
